import type { PlatformFeaturePage } from "../platform-feature-pages";

const inputs: Record<string, readonly [string, string]> = {
  "staff-to-jianpu": ["Start with a structured score imported from MusicXML, MIDI or Jianpu, or a reviewed recognition result from a score PDF or image.", "Parte de una partitura estructurada importada desde MusicXML, MIDI o Jianpu, o de un resultado de reconocimiento de PDF o imagen que hayas revisado."],
  "jianpu-to-staff": ["Enter or paste structured Jianpu text with a key, meter and note durations. This tool does not directly recognize arbitrary images of numbered notation.", "Escribe o pega texto Jianpu estructurado con tonalidad, compás y duraciones. Esta herramienta no reconoce directamente imágenes arbitrarias de notación numerada."],
  "transpose-score": ["Open an editable score revision imported from MusicXML, MIDI, Jianpu, a project backup or a reviewed scan. Choose semitones, a target key or a transposing-instrument profile.", "Abre una revisión editable importada desde MusicXML, MIDI, Jianpu, una copia del proyecto o un escaneo revisado. Elige semitonos, una tonalidad de destino o un perfil de instrumento transpositor."],
  "score-editor": ["Import MusicXML, MIDI or structured Jianpu, restore a project backup, or review a score recognized from a PDF or image before editing it.", "Importa MusicXML, MIDI o Jianpu estructurado, restaura una copia del proyecto o revisa una partitura reconocida desde PDF o imagen antes de editarla."],
  "musicxml-midi": ["Import a MusicXML or MIDI file. Review the resulting notation, since MIDI may not preserve all engraving, voice or expression details.", "Importa un archivo MusicXML o MIDI. Revisa la notación resultante, ya que MIDI puede no conservar todos los detalles de escritura, voces o expresión."],
  "sheet-music-scanner": ["Upload a score PDF, PNG, JPG, WebP or TIFF that you have permission to process. Clear images of printed staff notation generally provide a better starting point.", "Sube un PDF, PNG, JPG, WebP o TIFF de una partitura que tengas permiso para procesar. Las imágenes nítidas de pentagramas impresos suelen ofrecer un mejor punto de partida."],
  "pdf-to-musicxml": ["Use a score PDF or a PNG, JPG, WebP or TIFF image. Recognition creates a candidate that you must review before exporting MusicXML.", "Usa un PDF de partitura o una imagen PNG, JPG, WebP o TIFF. El reconocimiento crea una propuesta que debes revisar antes de exportar MusicXML."],
  "score-to-audio": ["Use an accepted structured score, for example from MusicXML or a reviewed PDF recognition result. Set the tempo, parts and loop before playing or exporting audio.", "Usa una partitura estructurada aceptada, por ejemplo desde MusicXML o un PDF reconocido y revisado. Ajusta el tempo, las partes y el bucle antes de reproducir o exportar audio."],
  "audio-to-score": ["When this experimental import is enabled, use an authorized WAV or MP3 melody recording. Check the availability notice before uploading.", "Cuando se habilite esta importación experimental, utiliza una grabación autorizada de una melodía en WAV o MP3. Comprueba el aviso de disponibilidad antes de subirla."],
};

export function getEnEsFeatureFaq(page: PlatformFeaturePage, locale: "en" | "es", available: boolean) {
  const en = locale === "en";
  if (page.slug === "teaching") return [
    { question: en ? "What do I need to use the teaching tools?" : "¿Qué necesito para usar las herramientas educativas?", answer: en ? "Sign in with an account that has teaching access enabled and open a score in your workspace. Classroom features are in beta and depend on your assigned role and access." : "Inicia sesión en una cuenta con acceso educativo habilitado y abre una partitura del espacio de trabajo. Las funciones de clase están en beta y dependen de tu rol y permisos." },
    { question: en ? "How do students receive assignments and feedback?" : "¿Cómo reciben los estudiantes las tareas y los comentarios?", answer: en ? "Create an assignment and share its student link. Students can submit work through the enabled workflow; teachers can review submissions, recordings and grading feedback. Check the sharing permissions before distributing the link." : "Crea una tarea y comparte su enlace para estudiantes. Pueden entregar el trabajo mediante el flujo habilitado; los docentes pueden revisar entregas, grabaciones y evaluaciones. Comprueba los permisos antes de distribuir el enlace." },
    { question: en ? "Does the beta replace a complete learning management system?" : "¿La beta sustituye a un sistema completo de gestión del aprendizaje?", answer: en ? "No. Classes, assignments, feedback and the LTI pilot support specific teaching workflows. Check the available features and limits before planning a full course around them." : "No. Las clases, tareas, comentarios y el piloto LTI apoyan determinados flujos educativos. Comprueba las funciones y los límites antes de organizar un curso completo con ellos." },
  ];
  const audioOutput = page.slug === "score-to-audio";
  return [
    { question: en ? "What source material can I use?" : "¿Qué material de origen puedo usar?", answer: !available ? page.guardrail : inputs[page.slug]?.[en ? 0 : 1] ?? page.workflow[0]?.body ?? page.description },
    { question: audioOutput ? (en ? "Can I edit the score before creating audio?" : "¿Puedo editar la partitura antes de crear el audio?") : (en ? "Can I review and edit the score?" : "¿Puedo revisar y editar la partitura?"), answer: !available ? page.guardrail : en ? "Yes. Review the imported score, correct notes and rhythms, then use the available transposition, playback and export tools. Changes are kept as score revisions." : "Sí. Revisa la partitura importada, corrige las notas y el ritmo y usa las herramientas disponibles de transposición, reproducción y exportación. Los cambios se guardan como revisiones." },
    { question: en ? "What limitations should I check?" : "¿Qué limitaciones debo comprobar?", answer: page.guardrail },
  ];
}
