import type { SupportedLocale } from "@score/i18n";
import type { FeatureIndexCatalog } from "./types";

const featureIndexCatalogs = {
  en: {
    metadata: {
      title: "Sheet Music Software & Online Tools | ScoreTransposer",
      description: "Explore online sheet music software for notation editing, part extraction, collaboration, practice feedback, classroom work, and PDF, MP3, SVG, or PNG export.",
      keywords: ["online sheet music software", "sheet music editor", "extract parts from score", "collaborative notation", "sheet music to MP3", "export sheet music to PDF"],
      imageAlt: "ScoreTransposer online sheet music editor and feature workspace",
    },
    page: {
      eyebrow: "Online sheet music software", title: "One score workspace from recognition to collaboration",
      body: "Edit notation, extract parts, collaborate, practise, teach, and export from versioned Score JSON and MusicXML instead of sending one score through disconnected tools.",
      available: "Available", beta: "Beta capability", betaTitle: "Released behind production gates",
      betaBody: "Beta features have working product paths while retaining clear accuracy, browser, external-engine, or production-scale boundaries.",
      open: "Open feature", workspace: "Open my score workspace", structuredDataName: "ScoreTransposer sheet music tools",
    },
    formal: {
      "online-editor": { title: "Online Sheet Music Editor", body: "Edit notes, rhythm, lyrics, harmony, dynamics, score structure, and correction candidates." },
      "playback-practice": { title: "Playback & Practice Mode", body: "Change tempo, loop measures, use a metronome and count-in, and solo or mute parts." },
      "smart-transposer": { title: "Smart Sheet Music Transposer", body: "Transpose by semitone, interval, target key, or transposing-instrument profile with range review." },
      "staff-jianpu": { title: "Staff ↔ Jianpu Converter", body: "Move between staff notation and structured numbered notation from the same score model." },
      "version-history": { title: "Version History & Restore", body: "Keep immutable score revisions and restore an earlier state without deleting later history." },
      "share-collaborate": { title: "Share & Collaborate", body: "Use revocable view, comment, and edit access with score annotations in a collaborative editor." },
      "musicxml-midi": { title: "MusicXML & MIDI Converter", body: "Import, edit, and export portable notation and MIDI files without locking the score to PDF pixels." },
    },
    betaFeatures: {
      "part-copy": { title: "Part Copy Generator Beta", body: "Extract parts or split a full score into independent practice projects. Copies do not yet follow later full-score edits." },
      "recording-feedback": { title: "Browser Recording & Practice Feedback Beta", body: "Record monophonic practice and receive reviewable pitch and timing observations." },
      "real-time-collaboration": { title: "Real-time Collaboration Beta", body: "Co-edit with presence, conflict handling, offline queues, and role-aware access." },
      "image-export": { title: "High-quality PDF, SVG & PNG Export", body: "Render page-aware PDF and high-resolution SVG or PNG from an immutable Score JSON/MusicXML revision." },
      "audio-export": { title: "WAV & MP3 Audio Export", body: "Create practice audio through MIDI, a licensed SoundFont, FluidSynth, and ffmpeg." },
      "school-beta": { title: "Classroom / School Beta", body: "Manage classes, assignments, submissions, recordings, rubrics, feedback, and an LTI pilot." },
    },
  },
  "zh-CN": {
    metadata: {
      title: "在线五线谱软件与乐谱工具 | ScoreTransposer",
      description: "集中使用在线五线谱编辑、分谱提取、多人协作、练习反馈、音乐课堂和 PDF、MP3、SVG、PNG 乐谱导出工具。",
      keywords: ["在线五线谱软件", "五线谱编辑器", "乐谱工具", "总谱提取声部", "多人协作乐谱", "乐谱转 MP3", "乐谱导出 PDF"],
      imageAlt: "ScoreTransposer 在线五线谱编辑与功能工作台（英文界面）",
    },
    page: {
      eyebrow: "正式功能", title: "从识谱到协作的完整乐谱工作台",
      body: "首批正式功能使用统一的 Score JSON 与 MusicXML 版本，不会为播放、移调、简谱或导出各建一套互不兼容的数据。",
      available: "正式开放", beta: "Beta 能力", betaTitle: "按生产门禁逐步开放",
      betaBody: "Beta 功能已有产品路径，但仍保留准确率、浏览器兼容、外部引擎或生产规模边界。",
      open: "打开功能", workspace: "进入我的乐谱工作台", structuredDataName: "ScoreTransposer 乐谱功能",
    },
    formal: {
      "online-editor": { title: "在线乐谱编辑与校正", body: "编辑音符、节奏、歌词、和弦、力度、乐谱结构和识谱候选稿。" },
      "playback-practice": { title: "练习播放模式", body: "调节速度、循环小节、使用节拍器与预备拍，并独奏或静音声部。" },
      "smart-transposer": { title: "智能乐谱移调", body: "按半音、音程、目标调或移调乐器配置移调，并检查音域。" },
      "staff-jianpu": { title: "五线谱 / 简谱转换", body: "从同一个乐谱结构在五线谱和结构化简谱之间转换。" },
      "version-history": { title: "版本历史与恢复", body: "保存不可变乐谱版本，并在不删除后续记录的情况下恢复早期状态。" },
      "share-collaborate": { title: "分享与协作", body: "创建可撤销的查看、评论和编辑权限，并支持谱面批注。" },
      "musicxml-midi": { title: "MusicXML 与 MIDI 转换", body: "导入、编辑和导出可迁移的乐谱与 MIDI 文件，不把 PDF 像素当作编辑源。" },
    },
    betaFeatures: {
      "part-copy": { title: "声部分谱副本 Beta", body: "从总谱提取声部并拆成独立练习工程；副本暂不会自动跟随总谱后续修改。" },
      "recording-feedback": { title: "浏览器录音与练习反馈 Beta", body: "录制单旋律练习，并获得需要人工复核的音高和节奏观察。" },
      "real-time-collaboration": { title: "多人实时协作 Beta", body: "通过在线状态、冲突处理、离线队列和角色权限共同编辑乐谱。" },
      "image-export": { title: "PDF、SVG、PNG 高质量导出", body: "从固定的 Score JSON／MusicXML 版本导出分页 PDF 与高分辨率 SVG、PNG。" },
      "audio-export": { title: "WAV、MP3 音频导出", body: "通过 MIDI、许可清晰的 SoundFont、FluidSynth 和 ffmpeg 生成练习音频。" },
      "school-beta": { title: "Classroom / School Beta", body: "管理班级、作业、学生提交、录音、评分量规、反馈和 LTI 试点。" },
    },
  },
  "zh-TW": {
    metadata: {
      title: "線上五線譜軟體與樂譜工具 | ScoreTransposer",
      description: "整合線上五線譜編輯、分譜擷取、多人協作、練習回饋、音樂課堂，以及 PDF、MP3、SVG、PNG 匯出工具。",
      keywords: ["線上五線譜軟體", "五線譜編輯器", "樂譜工具", "總譜擷取聲部", "協作樂譜", "樂譜轉 MP3", "樂譜匯出 PDF"],
      imageAlt: "ScoreTransposer 線上五線譜編輯與功能工作區（英文介面）",
    },
    page: {
      eyebrow: "線上樂譜軟體", title: "從辨識到協作的一體化樂譜工作區",
      body: "以版本化 Score JSON 與 MusicXML 編輯、擷取聲部、協作、練習、教學與匯出，不必把同一份樂譜交給彼此分離的工具。",
      available: "已開放", beta: "Beta 功能", betaTitle: "依正式環境門檻逐步開放",
      betaBody: "Beta 功能已有可用流程，同時保留準確率、瀏覽器、外部引擎與正式規模的明確限制。",
      open: "開啟功能", workspace: "開啟我的樂譜工作區", structuredDataName: "ScoreTransposer 樂譜工具",
    },
    formal: {
      "online-editor": { title: "線上樂譜編輯與校正", body: "編輯音符、節奏、歌詞、和聲、力度、樂譜結構與辨識候選稿。" },
      "playback-practice": { title: "播放與練習模式", body: "調整速度、循環小節、使用節拍器與預備拍，並獨奏或靜音聲部。" },
      "smart-transposer": { title: "智慧樂譜移調", body: "依半音、音程、目標調或移調樂器設定移調，並檢查音域。" },
      "staff-jianpu": { title: "五線譜 ↔ 簡譜轉換", body: "從同一個樂譜模型在五線譜與結構化數字簡譜之間轉換。" },
      "version-history": { title: "版本歷史與還原", body: "保留不可變樂譜修訂，還原早期狀態時不刪除後續歷史。" },
      "share-collaborate": { title: "分享與協作", body: "使用可撤銷的檢視、留言、編輯權限與譜面註解共同編輯。" },
      "musicxml-midi": { title: "MusicXML 與 MIDI 轉換", body: "匯入、編輯與匯出可攜式樂譜和 MIDI，不把 PDF 像素當作編輯來源。" },
    },
    betaFeatures: {
      "part-copy": { title: "聲部分譜副本 Beta", body: "從總譜擷取聲部並拆成獨立練習專案；副本暫不會跟隨總譜後續修改。" },
      "recording-feedback": { title: "瀏覽器錄音與練習回饋 Beta", body: "錄製單旋律練習，取得可人工複核的音高與節奏觀察。" },
      "real-time-collaboration": { title: "多人即時協作 Beta", body: "透過上線狀態、衝突處理、離線佇列與角色權限共同編輯。" },
      "image-export": { title: "高品質 PDF、SVG、PNG 匯出", body: "從固定 Score JSON／MusicXML 修訂產生分頁 PDF 與高解析 SVG、PNG。" },
      "audio-export": { title: "WAV 與 MP3 音訊匯出", body: "透過 MIDI、授權清楚的 SoundFont、FluidSynth 與 ffmpeg 建立練習音訊。" },
      "school-beta": { title: "Classroom / School Beta", body: "管理班級、作業、提交、錄音、評分規準、回饋與 LTI 試點。" },
    },
  },
  ja: {
    metadata: {
      title: "オンライン楽譜ソフトと音楽ツール | ScoreTransposer",
      description: "楽譜編集、パート抽出、共同編集、練習フィードバック、授業、PDF・MP3・SVG・PNG 書き出しを1つのオンライン環境で利用できます。",
      keywords: ["オンライン楽譜ソフト", "楽譜編集", "パート抽出", "共同楽譜編集", "楽譜 MP3 変換", "楽譜 PDF 書き出し"],
      imageAlt: "ScoreTransposer のオンライン楽譜編集機能（英語画面）",
    },
    page: {
      eyebrow: "オンライン楽譜ソフト", title: "認識から共同編集まで、1つの楽譜ワークスペースで",
      body: "バージョン管理された Score JSON と MusicXML を使い、編集、パート抽出、共同作業、練習、授業、書き出しを一貫して行えます。",
      available: "利用可能", beta: "ベータ機能", betaTitle: "本番条件を満たしながら段階的に公開",
      betaBody: "ベータ機能には動作する製品経路があり、精度、ブラウザー、外部エンジン、本番規模の制約も明示しています。",
      open: "機能を開く", workspace: "楽譜ワークスペースを開く", structuredDataName: "ScoreTransposer 楽譜ツール",
    },
    formal: {
      "online-editor": { title: "オンライン楽譜編集・修正", body: "音符、リズム、歌詞、和音、強弱、楽譜構造、認識候補を編集します。" },
      "playback-practice": { title: "再生・練習モード", body: "テンポ、小節ループ、メトロノーム、カウントイン、パートのソロ/ミュートを操作します。" },
      "smart-transposer": { title: "スマート移調", body: "半音、音程、目標調、移調楽器の設定で移調し、音域を確認します。" },
      "staff-jianpu": { title: "五線譜 ↔ 数字譜変換", body: "同じ楽譜モデルから五線譜と構造化数字譜を相互変換します。" },
      "version-history": { title: "バージョン履歴と復元", body: "変更不能なリビジョンを保ち、後続履歴を消さずに以前の状態へ戻せます。" },
      "share-collaborate": { title: "共有と共同編集", body: "取り消し可能な閲覧・コメント・編集権限と楽譜注釈を使います。" },
      "musicxml-midi": { title: "MusicXML・MIDI 変換", body: "PDF 画像に固定せず、移植可能な楽譜と MIDI を取り込み、編集、書き出しできます。" },
    },
    betaFeatures: {
      "part-copy": { title: "パート譜コピー生成 Beta", body: "総譜からパートを抽出して独立した練習プロジェクトにします。コピーは後の総譜編集にはまだ追従しません。" },
      "recording-feedback": { title: "ブラウザー録音・練習フィードバック Beta", body: "単旋律の練習を録音し、確認可能な音高とタイミングの所見を受け取れます。" },
      "real-time-collaboration": { title: "リアルタイム共同編集 Beta", body: "在席表示、競合処理、オフラインキュー、役割別権限で共同編集します。" },
      "image-export": { title: "高品質 PDF・SVG・PNG 書き出し", body: "固定した Score JSON／MusicXML リビジョンからページ対応 PDF と高解像度画像を生成します。" },
      "audio-export": { title: "WAV・MP3 音声書き出し", body: "MIDI、ライセンス済み SoundFont、FluidSynth、ffmpeg を使って練習音声を生成します。" },
      "school-beta": { title: "Classroom / School Beta", body: "クラス、課題、提出、録音、ルーブリック、フィードバック、LTI 試験運用を管理します。" },
    },
  },
  ko: {
    metadata: {
      title: "온라인 악보 소프트웨어와 음악 도구 | ScoreTransposer",
      description: "악보 편집, 파트 추출, 공동 작업, 연습 피드백, 음악 수업과 PDF·MP3·SVG·PNG 내보내기를 한곳에서 사용하세요.",
      keywords: ["온라인 악보 소프트웨어", "악보 편집기", "악보 파트 추출", "공동 악보 편집", "악보 MP3 변환", "악보 PDF 내보내기"],
      imageAlt: "ScoreTransposer 온라인 악보 편집 기능(영어 인터페이스)",
    },
    page: {
      eyebrow: "온라인 악보 소프트웨어", title: "인식부터 공동 작업까지 하나의 악보 작업 공간",
      body: "버전 관리되는 Score JSON과 MusicXML을 바탕으로 편집, 파트 추출, 공동 작업, 연습, 수업과 내보내기를 이어서 수행합니다.",
      available: "사용 가능", beta: "베타 기능", betaTitle: "프로덕션 기준에 따라 단계적으로 공개",
      betaBody: "베타 기능에는 작동하는 제품 경로가 있으며 정확도, 브라우저, 외부 엔진과 운영 규모의 한계가 명확합니다.",
      open: "기능 열기", workspace: "내 악보 작업 공간 열기", structuredDataName: "ScoreTransposer 악보 도구",
    },
    formal: {
      "online-editor": { title: "온라인 악보 편집 및 교정", body: "음표, 리듬, 가사, 화성, 셈여림, 악보 구조와 인식 후보를 편집합니다." },
      "playback-practice": { title: "재생 및 연습 모드", body: "템포, 마디 반복, 메트로놈, 카운트인과 파트 솔로/음소거를 제어합니다." },
      "smart-transposer": { title: "스마트 악보 조옮김", body: "반음, 음정, 목표 조 또는 조옮김 악기 설정으로 변환하고 음역을 확인합니다." },
      "staff-jianpu": { title: "오선보 ↔ 숫자보 변환", body: "같은 악보 모델에서 오선보와 구조화된 숫자보를 서로 변환합니다." },
      "version-history": { title: "버전 기록 및 복원", body: "변경 불가능한 리비전을 보존하고 이후 기록을 지우지 않은 채 이전 상태로 복원합니다." },
      "share-collaborate": { title: "공유 및 공동 작업", body: "취소 가능한 보기·댓글·편집 권한과 악보 주석으로 함께 작업합니다." },
      "musicxml-midi": { title: "MusicXML 및 MIDI 변환", body: "악보를 PDF 픽셀에 가두지 않고 이식 가능한 악보와 MIDI를 가져오고 편집해 내보냅니다." },
    },
    betaFeatures: {
      "part-copy": { title: "파트 사본 생성 Beta", body: "총보에서 파트를 추출해 독립 연습 프로젝트로 만듭니다. 사본은 이후 총보 변경을 아직 따라가지 않습니다." },
      "recording-feedback": { title: "브라우저 녹음 및 연습 피드백 Beta", body: "단선율 연습을 녹음하고 검토 가능한 음높이와 타이밍 관찰을 받습니다." },
      "real-time-collaboration": { title: "실시간 공동 작업 Beta", body: "접속 상태, 충돌 처리, 오프라인 대기열과 역할 기반 접근으로 함께 편집합니다." },
      "image-export": { title: "고품질 PDF·SVG·PNG 내보내기", body: "고정된 Score JSON/MusicXML 리비전에서 페이지 PDF와 고해상도 이미지를 생성합니다." },
      "audio-export": { title: "WAV 및 MP3 오디오 내보내기", body: "MIDI, 라이선스가 명확한 SoundFont, FluidSynth와 ffmpeg로 연습 오디오를 만듭니다." },
      "school-beta": { title: "Classroom / School Beta", body: "수업, 과제, 제출, 녹음, 루브릭, 피드백과 LTI 파일럿을 관리합니다." },
    },
  },
  fr: {
    metadata: {
      title: "Logiciel de partition et outils musicaux en ligne | ScoreTransposer",
      description: "Éditez des partitions, extrayez des parties, collaborez, travaillez avec des retours de pratique, enseignez et exportez en PDF, MP3, SVG ou PNG.",
      keywords: ["logiciel de partition en ligne", "éditeur de partitions", "extraire des parties", "notation collaborative", "partition en MP3", "export PDF de partition"],
      imageAlt: "Éditeur de partitions et fonctions ScoreTransposer (interface en anglais)",
    },
    page: {
      eyebrow: "Logiciel de partition en ligne", title: "Un seul espace musical, de la reconnaissance à la collaboration",
      body: "Éditez, extrayez des parties, collaborez, pratiquez, enseignez et exportez depuis des versions Score JSON et MusicXML communes.",
      available: "Disponible", beta: "Fonction bêta", betaTitle: "Ouverture progressive selon les contrôles de production",
      betaBody: "Les fonctions bêta disposent d’un parcours réel tout en indiquant leurs limites de précision, de navigateur, de moteur externe ou d’échelle.",
      open: "Ouvrir la fonction", workspace: "Ouvrir mon espace de partitions", structuredDataName: "Outils de partition ScoreTransposer",
    },
    formal: {
      "online-editor": { title: "Éditeur de partitions en ligne", body: "Modifiez notes, rythmes, paroles, harmonies, nuances, structure et candidats de reconnaissance." },
      "playback-practice": { title: "Lecture et mode d’entraînement", body: "Réglez le tempo, bouclez des mesures, utilisez métronome et décompte, puis isolez ou coupez des parties." },
      "smart-transposer": { title: "Transpositeur intelligent", body: "Transposez par demi-ton, intervalle, tonalité cible ou profil d’instrument et contrôlez la tessiture." },
      "staff-jianpu": { title: "Portée ↔ Jianpu", body: "Passez de la portée à la notation chiffrée structurée depuis le même modèle musical." },
      "version-history": { title: "Historique et restauration", body: "Conservez des révisions immuables et restaurez un état antérieur sans supprimer la suite de l’historique." },
      "share-collaborate": { title: "Partager et collaborer", body: "Utilisez des droits révocables de lecture, commentaire et édition avec annotations de partition." },
      "musicxml-midi": { title: "Convertisseur MusicXML et MIDI", body: "Importez, éditez et exportez des formats portables sans réduire la partition aux pixels d’un PDF." },
    },
    betaFeatures: {
      "part-copy": { title: "Générateur de parties Beta", body: "Extrayez des parties vers des projets d’entraînement indépendants. Les copies ne suivent pas encore les modifications ultérieures du conducteur." },
      "recording-feedback": { title: "Enregistrement et retour de pratique Beta", body: "Enregistrez une pratique monophonique et obtenez des observations de hauteur et de rythme à vérifier." },
      "real-time-collaboration": { title: "Collaboration en temps réel Beta", body: "Coéditez avec présence, gestion des conflits, file hors ligne et rôles d’accès." },
      "image-export": { title: "Export PDF, SVG et PNG haute qualité", body: "Générez un PDF paginé et des images haute résolution depuis une révision Score JSON/MusicXML immuable." },
      "audio-export": { title: "Export audio WAV et MP3", body: "Créez l’audio de pratique via MIDI, un SoundFont sous licence, FluidSynth et ffmpeg." },
      "school-beta": { title: "Classroom / School Beta", body: "Gérez classes, devoirs, travaux, enregistrements, grilles, retours et pilote LTI." },
    },
  },
  es: {
    metadata: {
      title: "Software de partituras y herramientas musicales en línea | ScoreTransposer",
      description: "Edita partituras, extrae partes, colabora, recibe observaciones de práctica, enseña y exporta a PDF, MP3, SVG o PNG desde un mismo espacio.",
      keywords: ["software de partituras en línea", "editor de partituras", "extraer partes", "notación colaborativa", "partitura a MP3", "exportar partitura a PDF"],
      imageAlt: "Editor de partituras y funciones de ScoreTransposer (interfaz en inglés)",
    },
    page: {
      eyebrow: "Software de partituras en línea", title: "Un espacio musical desde el reconocimiento hasta la colaboración",
      body: "Edita, extrae partes, colabora, practica, enseña y exporta desde versiones compartidas de Score JSON y MusicXML.",
      available: "Disponible", beta: "Función beta", betaTitle: "Publicación gradual con controles de producción",
      betaBody: "Las funciones beta tienen recorridos reales y límites claros de precisión, navegador, motor externo o escala operativa.",
      open: "Abrir función", workspace: "Abrir mi espacio de partituras", structuredDataName: "Herramientas de partituras ScoreTransposer",
    },
    formal: {
      "online-editor": { title: "Editor de partituras en línea", body: "Edita notas, ritmo, letra, armonía, dinámica, estructura y candidatos de reconocimiento." },
      "playback-practice": { title: "Reproducción y modo de práctica", body: "Cambia el tempo, repite compases, usa metrónomo y cuenta previa, y aísla o silencia partes." },
      "smart-transposer": { title: "Transportador inteligente", body: "Transporta por semitono, intervalo, tonalidad objetivo o perfil de instrumento y revisa el registro." },
      "staff-jianpu": { title: "Pentagrama ↔ Jianpu", body: "Pasa entre pentagrama y notación numerada estructurada desde el mismo modelo musical." },
      "version-history": { title: "Historial y restauración", body: "Conserva revisiones inmutables y recupera un estado anterior sin borrar el historial posterior." },
      "share-collaborate": { title: "Compartir y colaborar", body: "Usa acceso revocable de lectura, comentario y edición con anotaciones sobre la partitura." },
      "musicxml-midi": { title: "Conversor MusicXML y MIDI", body: "Importa, edita y exporta formatos portátiles sin limitar la partitura a los píxeles de un PDF." },
    },
    betaFeatures: {
      "part-copy": { title: "Generador de partes Beta", body: "Extrae partes a proyectos de práctica independientes. Las copias aún no siguen cambios posteriores de la partitura completa." },
      "recording-feedback": { title: "Grabación y observaciones de práctica Beta", body: "Graba práctica monofónica y recibe observaciones revisables de afinación y tiempo." },
      "real-time-collaboration": { title: "Colaboración en tiempo real Beta", body: "Coedita con presencia, gestión de conflictos, cola sin conexión y acceso por roles." },
      "image-export": { title: "Exportación PDF, SVG y PNG de alta calidad", body: "Genera PDF paginado e imágenes de alta resolución desde una revisión Score JSON/MusicXML inmutable." },
      "audio-export": { title: "Exportación de audio WAV y MP3", body: "Crea audio de práctica mediante MIDI, un SoundFont con licencia, FluidSynth y ffmpeg." },
      "school-beta": { title: "Classroom / School Beta", body: "Gestiona clases, tareas, entregas, grabaciones, rúbricas, comentarios y un piloto LTI." },
    },
  },
  de: {
    metadata: {
      title: "Online-Notensoftware und Musikwerkzeuge | ScoreTransposer",
      description: "Noten bearbeiten, Stimmen extrahieren, zusammenarbeiten, üben, unterrichten und als PDF, MP3, SVG oder PNG exportieren – in einem Arbeitsbereich.",
      keywords: ["Online Notensoftware", "Noteneditor", "Stimmen aus Partitur extrahieren", "kollaborative Notation", "Noten zu MP3", "Noten als PDF exportieren"],
      imageAlt: "ScoreTransposer-Noteneditor und Funktionen (englische Oberfläche)",
    },
    page: {
      eyebrow: "Online-Notensoftware", title: "Ein Notenarbeitsbereich von der Erkennung bis zur Zusammenarbeit",
      body: "Bearbeite Noten, extrahiere Stimmen, arbeite zusammen, übe, unterrichte und exportiere aus gemeinsamen Score-JSON- und MusicXML-Versionen.",
      available: "Verfügbar", beta: "Beta-Funktion", betaTitle: "Schrittweise Freigabe nach Produktionsprüfungen",
      betaBody: "Beta-Funktionen haben reale Produktwege und klare Grenzen für Genauigkeit, Browser, externe Engines oder Produktionsmaßstab.",
      open: "Funktion öffnen", workspace: "Meinen Notenarbeitsbereich öffnen", structuredDataName: "ScoreTransposer-Notenwerkzeuge",
    },
    formal: {
      "online-editor": { title: "Online-Noteneditor", body: "Noten, Rhythmus, Text, Harmonie, Dynamik, Struktur und Erkennungskandidaten bearbeiten." },
      "playback-practice": { title: "Wiedergabe und Übungsmodus", body: "Tempo ändern, Takte wiederholen, Metronom und Einzählen nutzen sowie Stimmen solo oder stumm schalten." },
      "smart-transposer": { title: "Intelligentes Transponieren", body: "Nach Halbton, Intervall, Zieltonart oder Instrumentenprofil transponieren und den Tonumfang prüfen." },
      "staff-jianpu": { title: "Notensystem ↔ Jianpu", body: "Vom selben Notenmodell zwischen Notensystem und strukturierter Ziffernnotation wechseln." },
      "version-history": { title: "Versionsverlauf und Wiederherstellung", body: "Unveränderliche Revisionen behalten und ältere Zustände wiederherstellen, ohne spätere Historie zu löschen." },
      "share-collaborate": { title: "Teilen und zusammenarbeiten", body: "Widerrufbare Lese-, Kommentar- und Bearbeitungsrechte mit Notenannotationen nutzen." },
      "musicxml-midi": { title: "MusicXML- und MIDI-Konverter", body: "Portable Noten- und MIDI-Dateien importieren, bearbeiten und exportieren, ohne die Partitur an PDF-Pixel zu binden." },
    },
    betaFeatures: {
      "part-copy": { title: "Stimmenkopie-Generator Beta", body: "Stimmen als eigenständige Übungsprojekte extrahieren. Kopien folgen späteren Änderungen der Gesamtpartitur noch nicht." },
      "recording-feedback": { title: "Browseraufnahme und Übungsfeedback Beta", body: "Einstimmige Übungen aufnehmen und überprüfbare Tonhöhen- und Timing-Hinweise erhalten." },
      "real-time-collaboration": { title: "Echtzeit-Zusammenarbeit Beta", body: "Mit Präsenz, Konfliktbehandlung, Offline-Warteschlange und rollenbasiertem Zugriff gemeinsam bearbeiten." },
      "image-export": { title: "Hochwertiger PDF-, SVG- und PNG-Export", body: "Seitenbezogene PDFs und hochauflösende Bilder aus einer unveränderlichen Score-JSON/MusicXML-Revision erzeugen." },
      "audio-export": { title: "WAV- und MP3-Audioexport", body: "Übungsaudio über MIDI, ein lizenziertes SoundFont, FluidSynth und ffmpeg erstellen." },
      "school-beta": { title: "Classroom / School Beta", body: "Klassen, Aufgaben, Abgaben, Aufnahmen, Bewertungsraster, Feedback und LTI-Pilot verwalten." },
    },
  },
  ru: {
    metadata: {
      title: "Онлайн-программа для нот и музыкальные инструменты | ScoreTransposer",
      description: "Редактируйте ноты, извлекайте партии, работайте вместе, получайте обратную связь, обучайте и экспортируйте PDF, MP3, SVG или PNG.",
      keywords: ["нотная программа онлайн", "нотный редактор", "извлечение партий", "совместное редактирование нот", "ноты в MP3", "экспорт нот в PDF"],
      imageAlt: "Нотный редактор и функции ScoreTransposer (английский интерфейс)",
    },
    page: {
      eyebrow: "Нотная программа онлайн", title: "Единая рабочая область от распознавания до совместной работы",
      body: "Редактируйте, извлекайте партии, работайте вместе, практикуйтесь, обучайте и экспортируйте из общих версий Score JSON и MusicXML.",
      available: "Доступно", beta: "Бета-функция", betaTitle: "Постепенный выпуск после производственных проверок",
      betaBody: "У бета-функций есть рабочие сценарии и ясные ограничения точности, браузера, внешних движков и рабочего масштаба.",
      open: "Открыть функцию", workspace: "Открыть рабочую область", structuredDataName: "Нотные инструменты ScoreTransposer",
    },
    formal: {
      "online-editor": { title: "Онлайн-редактор нот", body: "Редактируйте ноты, ритм, текст, гармонию, динамику, структуру и кандидаты распознавания." },
      "playback-practice": { title: "Воспроизведение и практика", body: "Меняйте темп, зацикливайте такты, используйте метроном и отсчёт, включайте соло или заглушайте партии." },
      "smart-transposer": { title: "Умное транспонирование", body: "Транспонируйте по полутонам, интервалу, целевой тональности или профилю инструмента и проверяйте диапазон." },
      "staff-jianpu": { title: "Нотный стан ↔ Jianpu", body: "Переходите между нотным станом и структурированной цифровой нотацией из общей модели." },
      "version-history": { title: "История версий и восстановление", body: "Храните неизменяемые ревизии и возвращайтесь к прошлому состоянию без удаления последующей истории." },
      "share-collaborate": { title: "Совместная работа", body: "Используйте отзываемые права просмотра, комментария и редактирования с аннотациями на нотах." },
      "musicxml-midi": { title: "Конвертер MusicXML и MIDI", body: "Импортируйте, редактируйте и экспортируйте переносимые форматы, не привязывая партитуру к пикселям PDF." },
    },
    betaFeatures: {
      "part-copy": { title: "Генератор партий Beta", body: "Извлекайте партии в отдельные проекты практики. Копии пока не следуют последующим изменениям полной партитуры." },
      "recording-feedback": { title: "Запись и обратная связь Beta", body: "Записывайте одноголосную практику и получайте проверяемые наблюдения о высоте и времени." },
      "real-time-collaboration": { title: "Совместная работа в реальном времени Beta", body: "Редактируйте вместе с индикацией присутствия, обработкой конфликтов, автономной очередью и ролями." },
      "image-export": { title: "Качественный экспорт PDF, SVG и PNG", body: "Создавайте постраничный PDF и изображения высокого разрешения из неизменяемой ревизии Score JSON/MusicXML." },
      "audio-export": { title: "Экспорт аудио WAV и MP3", body: "Создавайте учебное аудио через MIDI, лицензированный SoundFont, FluidSynth и ffmpeg." },
      "school-beta": { title: "Classroom / School Beta", body: "Управляйте классами, заданиями, работами, записями, рубриками, отзывами и пилотом LTI." },
    },
  },
} satisfies Record<SupportedLocale, FeatureIndexCatalog>;

export function getFeatureIndexCatalog(locale: SupportedLocale): FeatureIndexCatalog {
  return featureIndexCatalogs[locale];
}
