import type { SupportedLocale } from "@score/i18n";
import type { FeaturePracticeCopy } from "./types";

const featurePracticeCatalogs = {
  en: {
    eyebrow: "Dedicated practice controls",
    title: "Control loops, tempo, and the metronome on the dedicated practice page",
    body: "This public demo uses the same self-authored MusicXML/WAV as the homepage. The full workspace adds measure loops, count-in, part solo/mute, and a Tone.js metronome.",
    play: "Play practice phrase", pause: "Pause", muted: "Muted by default", sound: "Sound enabled",
    tempo: "Practice tempo", loop: "Loop section", metronome: "Visual metronome", start: "Start beat", end: "End beat", beat: "Current beat",
    ready: "Real product scope", readyDetail: "Score JSON → playback events", actionAvailable: "Practice in the workspace", actionUnavailable: "Check workspace availability",
    error: "The audio did not load. Try again later or download the WAV to inspect it.",
    experiment: "Experimental practice lab", experimentTitle: "Take this exact practice setup with you",
    experimentBody: "Tempo, loop boundaries, and the metronome live in the URL. Sound always stays muted by default and is never shared.",
    copyLink: "Copy practice link", copied: "Practice link copied.", copyFallback: "The browser blocked automatic copying. The setup is ready in the address bar.",
    reset: "Reset defaults", resetDone: "Reset to 96 BPM, beats 2–3, and the visual metronome.",
    shortcuts: "Keyboard controls are available when this practice stage is focused",
    shortcutRegion: "Practice stage. Press Space to play or pause, M for metronome, L for loop, plus or minus for tempo, and R to reset.",
    shortcutPlay: "Play/pause", shortcutTempo: "Change tempo", shortcutLoop: "Loop", shortcutMetronome: "Metronome", shortcutReset: "Reset",
  },
  "zh-CN": {
    eyebrow: "练习控制专项展示",
    title: "在专门的练习页里控制循环、速度和节拍",
    body: "这段公开演示使用与首页相同的自制 MusicXML/WAV。完整工作区再提供按小节循环、预备拍、声部独奏/静音和 Tone.js 节拍器。",
    play: "播放练习段", pause: "暂停", muted: "默认静音", sound: "声音已开启",
    tempo: "练习速度", loop: "循环片段", metronome: "可视节拍器", start: "起始拍", end: "结束拍", beat: "当前拍",
    ready: "真实产品范围", readyDetail: "Score JSON → 播放事件", actionAvailable: "进入工作区练习", actionUnavailable: "查看工作区开放状态",
    error: "音频没有成功加载，请稍后重试或下载 WAV 检查。",
    experiment: "实验练习工具", experimentTitle: "把这一组练习设置作为链接带走",
    experimentBody: "速度、循环区间和节拍器会写入当前 URL；声音始终默认静音，不会写入分享链接。",
    copyLink: "复制练习链接", copied: "练习链接已复制。", copyFallback: "浏览器阻止了自动复制，设置已写入地址栏。",
    reset: "恢复默认", resetDone: "已恢复 96 BPM、循环第 2～3 拍和可视节拍器。",
    shortcuts: "聚焦此练习舞台后可用快捷键",
    shortcutRegion: "练习舞台。按空格播放或暂停，M 切换节拍器，L 切换循环，加减号调整速度，R 恢复默认。",
    shortcutPlay: "播放/暂停", shortcutTempo: "调整速度", shortcutLoop: "循环", shortcutMetronome: "节拍器", shortcutReset: "重置",
  },
  "zh-TW": {
    eyebrow: "專用練習控制",
    title: "在專用練習頁控制循環、速度與節拍器",
    body: "此公開示範使用與首頁相同的自製 MusicXML/WAV。完整工作區另提供小節循環、預備拍、聲部獨奏/靜音與 Tone.js 節拍器。",
    play: "播放練習樂句", pause: "暫停", muted: "預設靜音", sound: "聲音已開啟",
    tempo: "練習速度", loop: "循環片段", metronome: "視覺節拍器", start: "起始拍", end: "結束拍", beat: "目前拍點",
    ready: "真實產品範圍", readyDetail: "Score JSON → 播放事件", actionAvailable: "前往工作區練習", actionUnavailable: "查看工作區開放狀態",
    error: "音訊載入失敗，請稍後再試或下載 WAV 檢查。",
    experiment: "實驗練習工具", experimentTitle: "帶走這組完整練習設定",
    experimentBody: "速度、循環邊界與節拍器會寫入目前 URL；聲音始終預設靜音，也不會包含在分享連結中。",
    copyLink: "複製練習連結", copied: "已複製練習連結。", copyFallback: "瀏覽器阻止自動複製；設定已顯示在網址列。",
    reset: "恢復預設值", resetDone: "已恢復 96 BPM、第 2～3 拍循環與視覺節拍器。",
    shortcuts: "聚焦練習舞台後可使用鍵盤快捷鍵",
    shortcutRegion: "練習舞台。按空白鍵播放或暫停，M 切換節拍器，L 切換循環，加減號調整速度，R 恢復預設值。",
    shortcutPlay: "播放/暫停", shortcutTempo: "調整速度", shortcutLoop: "循環", shortcutMetronome: "節拍器", shortcutReset: "重設",
  },
  ja: {
    eyebrow: "練習専用コントロール",
    title: "練習ページでループ、テンポ、メトロノームを操作",
    body: "この公開デモでは、ホームページと同じ自作の MusicXML/WAV を使用します。完全版ワークスペースでは、小節ループ、カウントイン、パートのソロ/ミュート、Tone.js メトロノームも利用できます。",
    play: "練習フレーズを再生", pause: "一時停止", muted: "初期設定はミュート", sound: "音声オン",
    tempo: "練習テンポ", loop: "ループ区間", metronome: "視覚メトロノーム", start: "開始拍", end: "終了拍", beat: "現在の拍",
    ready: "実製品の範囲", readyDetail: "Score JSON → 再生イベント", actionAvailable: "ワークスペースで練習", actionUnavailable: "ワークスペースの公開状況を確認",
    error: "音声を読み込めませんでした。後でもう一度試すか、WAV をダウンロードして確認してください。",
    experiment: "実験的な練習ラボ", experimentTitle: "この練習設定をリンクで保存",
    experimentBody: "テンポ、ループ範囲、メトロノームは URL に保存されます。音声は常に初期状態でミュートされ、共有されません。",
    copyLink: "練習リンクをコピー", copied: "練習リンクをコピーしました。", copyFallback: "ブラウザーが自動コピーをブロックしました。設定はアドレスバーに反映されています。",
    reset: "初期設定に戻す", resetDone: "96 BPM、2～3拍のループ、視覚メトロノームに戻しました。",
    shortcuts: "この練習ステージにフォーカスするとキーボード操作が使えます",
    shortcutRegion: "練習ステージ。Space で再生/一時停止、M でメトロノーム、L でループ、プラス/マイナスでテンポ変更、R でリセットします。",
    shortcutPlay: "再生/一時停止", shortcutTempo: "テンポ変更", shortcutLoop: "ループ", shortcutMetronome: "メトロノーム", shortcutReset: "リセット",
  },
  ko: {
    eyebrow: "전용 연습 컨트롤",
    title: "연습 페이지에서 반복, 템포와 메트로놈 제어",
    body: "이 공개 데모는 홈페이지와 같은 자체 제작 MusicXML/WAV를 사용합니다. 전체 작업 공간에서는 마디 반복, 카운트인, 파트 솔로/음소거와 Tone.js 메트로놈도 제공합니다.",
    play: "연습 구절 재생", pause: "일시 정지", muted: "기본 음소거", sound: "소리 켜짐",
    tempo: "연습 템포", loop: "반복 구간", metronome: "시각 메트로놈", start: "시작 박", end: "끝 박", beat: "현재 박",
    ready: "실제 제품 범위", readyDetail: "Score JSON → 재생 이벤트", actionAvailable: "작업 공간에서 연습", actionUnavailable: "작업 공간 사용 가능 여부 확인",
    error: "오디오를 불러오지 못했습니다. 나중에 다시 시도하거나 WAV를 다운로드해 확인하세요.",
    experiment: "실험적 연습 도구", experimentTitle: "이 연습 설정을 링크로 저장",
    experimentBody: "템포, 반복 경계와 메트로놈이 URL에 저장됩니다. 소리는 항상 기본 음소거이며 공유되지 않습니다.",
    copyLink: "연습 링크 복사", copied: "연습 링크를 복사했습니다.", copyFallback: "브라우저가 자동 복사를 차단했습니다. 설정은 주소 표시줄에 준비되어 있습니다.",
    reset: "기본값 복원", resetDone: "96 BPM, 2~3박 반복과 시각 메트로놈으로 복원했습니다.",
    shortcuts: "연습 스테이지에 초점을 두면 키보드 단축키를 사용할 수 있습니다",
    shortcutRegion: "연습 스테이지. Space로 재생/일시 정지, M으로 메트로놈, L로 반복, 더하기/빼기로 템포 조절, R로 초기화합니다.",
    shortcutPlay: "재생/일시 정지", shortcutTempo: "템포 변경", shortcutLoop: "반복", shortcutMetronome: "메트로놈", shortcutReset: "초기화",
  },
  fr: {
    eyebrow: "Commandes d’entraînement dédiées",
    title: "Contrôlez les boucles, le tempo et le métronome sur la page d’entraînement",
    body: "Cette démo publique utilise le même MusicXML/WAV original que la page d’accueil. L’espace complet ajoute les boucles par mesure, le décompte, le solo/muet par partie et un métronome Tone.js.",
    play: "Lire la phrase", pause: "Pause", muted: "Muet par défaut", sound: "Son activé",
    tempo: "Tempo d’entraînement", loop: "Boucler la section", metronome: "Métronome visuel", start: "Premier temps", end: "Dernier temps", beat: "Temps actuel",
    ready: "Périmètre réel du produit", readyDetail: "Score JSON → événements de lecture", actionAvailable: "S’entraîner dans l’espace de travail", actionUnavailable: "Vérifier la disponibilité",
    error: "Le son n’a pas été chargé. Réessayez plus tard ou téléchargez le WAV pour le vérifier.",
    experiment: "Laboratoire d’entraînement", experimentTitle: "Emportez exactement ces réglages",
    experimentBody: "Le tempo, les limites de boucle et le métronome sont enregistrés dans l’URL. Le son reste muet par défaut et n’est jamais partagé.",
    copyLink: "Copier le lien", copied: "Lien d’entraînement copié.", copyFallback: "Le navigateur a bloqué la copie automatique. Les réglages figurent dans la barre d’adresse.",
    reset: "Rétablir les valeurs", resetDone: "Réglages rétablis à 96 BPM, temps 2–3 et métronome visuel.",
    shortcuts: "Les raccourcis sont disponibles lorsque cette zone d’entraînement a le focus",
    shortcutRegion: "Zone d’entraînement. Espace lance ou met en pause, M contrôle le métronome, L la boucle, plus ou moins le tempo et R réinitialise.",
    shortcutPlay: "Lecture/pause", shortcutTempo: "Changer le tempo", shortcutLoop: "Boucle", shortcutMetronome: "Métronome", shortcutReset: "Réinitialiser",
  },
  es: {
    eyebrow: "Controles de práctica dedicados",
    title: "Controla los bucles, el tempo y el metrónomo en la página de práctica",
    body: "Esta demo pública usa el mismo MusicXML/WAV propio que la página de inicio. El espacio completo añade bucles por compás, cuenta previa, solo/silencio por parte y un metrónomo Tone.js.",
    play: "Reproducir frase", pause: "Pausa", muted: "Silenciado por defecto", sound: "Sonido activado",
    tempo: "Tempo de práctica", loop: "Repetir sección", metronome: "Metrónomo visual", start: "Pulso inicial", end: "Pulso final", beat: "Pulso actual",
    ready: "Alcance real del producto", readyDetail: "Score JSON → eventos de reproducción", actionAvailable: "Practicar en el espacio de trabajo", actionUnavailable: "Comprobar disponibilidad",
    error: "El audio no se ha cargado. Inténtalo más tarde o descarga el WAV para revisarlo.",
    experiment: "Laboratorio de práctica", experimentTitle: "Llévate exactamente esta configuración",
    experimentBody: "El tempo, los límites del bucle y el metrónomo se guardan en la URL. El sonido siempre empieza silenciado y nunca se comparte.",
    copyLink: "Copiar enlace", copied: "Enlace de práctica copiado.", copyFallback: "El navegador bloqueó la copia automática. La configuración está lista en la barra de direcciones.",
    reset: "Restablecer valores", resetDone: "Restablecido a 96 BPM, pulsos 2–3 y metrónomo visual.",
    shortcuts: "Los controles de teclado están disponibles cuando esta zona de práctica tiene el foco",
    shortcutRegion: "Zona de práctica. Pulsa Espacio para reproducir o pausar, M para el metrónomo, L para el bucle, más o menos para el tempo y R para restablecer.",
    shortcutPlay: "Reproducir/pausar", shortcutTempo: "Cambiar tempo", shortcutLoop: "Bucle", shortcutMetronome: "Metrónomo", shortcutReset: "Restablecer",
  },
  de: {
    eyebrow: "Eigene Übungssteuerung",
    title: "Schleife, Tempo und Metronom auf der Übungsseite steuern",
    body: "Diese öffentliche Demo nutzt dieselbe selbst erstellte MusicXML/WAV-Datei wie die Startseite. Der vollständige Arbeitsbereich ergänzt Taktschleifen, Einzählen, Solo/Stumm pro Stimme und ein Tone.js-Metronom.",
    play: "Übungsphrase abspielen", pause: "Pause", muted: "Standardmäßig stumm", sound: "Ton aktiviert",
    tempo: "Übungstempo", loop: "Abschnitt wiederholen", metronome: "Visuelles Metronom", start: "Startschlag", end: "Endschlag", beat: "Aktueller Schlag",
    ready: "Realer Produktumfang", readyDetail: "Score JSON → Wiedergabeereignisse", actionAvailable: "Im Arbeitsbereich üben", actionUnavailable: "Verfügbarkeit prüfen",
    error: "Die Audiodatei wurde nicht geladen. Versuche es später erneut oder lade die WAV-Datei zur Prüfung herunter.",
    experiment: "Experimentelles Übungslabor", experimentTitle: "Diese Übungseinstellungen mitnehmen",
    experimentBody: "Tempo, Schleifengrenzen und Metronom stehen in der URL. Der Ton bleibt standardmäßig stumm und wird nie geteilt.",
    copyLink: "Übungslink kopieren", copied: "Übungslink kopiert.", copyFallback: "Der Browser hat das automatische Kopieren blockiert. Die Einstellungen stehen in der Adressleiste.",
    reset: "Standardwerte laden", resetDone: "Auf 96 BPM, Schläge 2–3 und visuelles Metronom zurückgesetzt.",
    shortcuts: "Tastaturbefehle sind verfügbar, wenn diese Übungsfläche fokussiert ist",
    shortcutRegion: "Übungsfläche. Leertaste startet oder pausiert, M schaltet das Metronom, L die Schleife, Plus oder Minus ändert das Tempo und R setzt zurück.",
    shortcutPlay: "Abspielen/Pause", shortcutTempo: "Tempo ändern", shortcutLoop: "Schleife", shortcutMetronome: "Metronom", shortcutReset: "Zurücksetzen",
  },
  ru: {
    eyebrow: "Специальные элементы практики",
    title: "Управляйте циклом, темпом и метрономом на странице практики",
    body: "В этой публичной демонстрации используется тот же авторский MusicXML/WAV, что и на главной странице. Полная рабочая область добавляет циклы по тактам, отсчёт, соло/заглушение партий и метроном Tone.js.",
    play: "Воспроизвести фразу", pause: "Пауза", muted: "Без звука по умолчанию", sound: "Звук включён",
    tempo: "Темп практики", loop: "Зациклить фрагмент", metronome: "Визуальный метроном", start: "Начальная доля", end: "Конечная доля", beat: "Текущая доля",
    ready: "Реальные возможности", readyDetail: "Score JSON → события воспроизведения", actionAvailable: "Практиковаться в рабочей области", actionUnavailable: "Проверить доступность",
    error: "Аудио не загрузилось. Повторите попытку позже или скачайте WAV для проверки.",
    experiment: "Экспериментальная практика", experimentTitle: "Сохраните именно эти настройки",
    experimentBody: "Темп, границы цикла и метроном записываются в URL. Звук всегда выключен по умолчанию и никогда не передаётся.",
    copyLink: "Копировать ссылку", copied: "Ссылка на практику скопирована.", copyFallback: "Браузер заблокировал копирование. Настройки уже находятся в адресной строке.",
    reset: "Вернуть настройки", resetDone: "Восстановлены 96 BPM, доли 2–3 и визуальный метроном.",
    shortcuts: "Клавиши доступны, когда область практики находится в фокусе",
    shortcutRegion: "Область практики. Пробел — воспроизведение или пауза, M — метроном, L — цикл, плюс и минус — темп, R — сброс.",
    shortcutPlay: "Воспроизведение/пауза", shortcutTempo: "Изменить темп", shortcutLoop: "Цикл", shortcutMetronome: "Метроном", shortcutReset: "Сброс",
  },
} satisfies Record<SupportedLocale, FeaturePracticeCopy>;

export function getFeaturePracticeCopy(locale: SupportedLocale): FeaturePracticeCopy {
  return featurePracticeCatalogs[locale];
}
