import type { SupportedLocale } from "@score/i18n";
import type { FeaturePageUi } from "./types";

export const FEATURE_OPEN_GRAPH_LOCALES = {
  en: "en_US",
  "zh-CN": "zh_CN",
  "zh-TW": "zh_TW",
  ja: "ja_JP",
  ko: "ko_KR",
  fr: "fr_FR",
  es: "es_ES",
  de: "de_DE",
  ru: "ru_RU",
} as const satisfies Record<SupportedLocale, string>;

const featurePageUiCatalogs = {
  en: {
    home: "Home",
    unavailable: "Pending production verification",
    actions: { upload: "Edit for free", checkout: "View access options", scores: "Open score projects", unavailable: "Check release availability" },
    pricing: "Pricing",
    moduleEyebrow: "Platform modules",
    moduleTitle: "Built on MusicXML and Score JSON",
    moduleBody: "Each feature page maps back to the same score project model rather than a separate one-off converter.",
    moduleLabel: "Module",
    moduleCardBody: "Connected to the score project workflow.",
    exampleEyebrow: "Real product example",
    exampleTitle: "One score, structured input and reusable output",
    captured: "Captured",
    englishInterfaceNote: "The screenshot shows the current English-language product interface.",
    input: "Input",
    output: "Output",
    downloadInput: "Download input case",
    downloadOutput: "Download output case",
    workflowEyebrow: "Workflow",
    workflowTitle: "How this path works",
    workflowBody: "The public page leads into the authenticated app workflow when users are ready to process a score.",
    detailEyebrow: "Product detail",
    detailTitle: "What to expect",
    faqEyebrow: "FAQ",
    faqTitle: (title) => `Questions about ${title}`,
    faqBody: "Practical limits and the expected workflow for this score tool.",
    faqInput: (title) => `What input does ${title} accept?`,
    faqEdit: "Can I edit the result after conversion?",
    faqEditAnswer: "Yes. Successful imports become Score JSON revisions that can be corrected, transposed, played, and exported from the score workspace.",
    faqCheck: "What should I check before relying on the result?",
    relatedEyebrow: "Related workflows",
    relatedTitle: "Continue with the same score project",
    relatedBody: "These pages use the same MusicXML and Score JSON source instead of sending the score through disconnected converters.",
    statuses: { Available: "Available", Beta: "Beta", Preview: "Preview" },
    softwareSubcategory: "Music notation software",
    operatingSystem: "Web browser",
    screenshotEvidence: "Captured from the current product interface as evidence of the real workflow.",
    screenshotAlt: (title) => `${title} in the current product interface`,
    exampleNotes: "The input and output stay in one structured score project; complex results still require human review.",
  },
  "zh-CN": {
    home: "首页",
    unavailable: "等待生产环境验证",
    actions: { upload: "免费编辑", checkout: "查看积分套餐", scores: "打开我的乐谱", unavailable: "查看功能开放状态" },
    pricing: "价格",
    moduleEyebrow: "平台模块",
    moduleTitle: "基于 MusicXML 与 Score JSON",
    moduleBody: "所有功能都回到同一个乐谱工程，而不是互不相通的一次性转换器。",
    moduleLabel: "模块",
    moduleCardBody: "连接到同一个结构化乐谱工作流。",
    exampleEyebrow: "真实产品案例",
    exampleTitle: "一份乐谱，结构化输入并持续复用",
    captured: "截图日期",
    englishInterfaceNote: "截图沿用当前英文产品界面。",
    input: "输入",
    output: "输出",
    downloadInput: "下载输入案例",
    downloadOutput: "下载输出案例",
    workflowEyebrow: "使用流程",
    workflowTitle: "这个功能如何使用",
    workflowBody: "了解功能后进入登录工作台，继续处理同一份结构化乐谱。",
    detailEyebrow: "产品说明",
    detailTitle: "使用前需要知道",
    faqEyebrow: "常见问题",
    faqTitle: (title) => `${title}常见问题`,
    faqBody: "开始处理乐谱前需要了解的能力与边界。",
    faqInput: (title) => `${title}支持什么输入？`,
    faqEdit: "转换以后还可以继续编辑吗？",
    faqEditAnswer: "可以。成功导入后会创建 Score JSON 版本，可以继续校正、移调、播放和导出。",
    faqCheck: "依赖结果前需要检查什么？",
    relatedEyebrow: "相关工作流",
    relatedTitle: "继续处理同一个乐谱工程",
    relatedBody: "这些功能使用同一份 MusicXML 与 Score JSON，不会把乐谱反复交给互不相通的转换器。",
    statuses: { Available: "已开放", Beta: "测试版", Preview: "预览版" },
    softwareSubcategory: "乐谱记谱软件",
    operatingSystem: "网页浏览器",
    screenshotEvidence: "来自当前产品英文界面的真实功能截图，用于证明现有工作流。",
    screenshotAlt: (title) => `${title}的真实产品截图（英文界面）`,
    exampleNotes: "输入和输出都保留在同一个结构化乐谱工程中，复杂结果仍需人工检查。",
  },
  "zh-TW": {
    home: "首頁",
    unavailable: "等待正式環境驗證",
    actions: { upload: "免費編輯", checkout: "查看使用方案", scores: "開啟樂譜專案", unavailable: "查看功能開放狀態" },
    pricing: "價格",
    moduleEyebrow: "平台模組",
    moduleTitle: "以 MusicXML 與 Score JSON 為基礎",
    moduleBody: "每項功能都回到同一個樂譜專案模型，而不是彼此分離的一次性轉換器。",
    moduleLabel: "模組",
    moduleCardBody: "連接同一套結構化樂譜流程。",
    exampleEyebrow: "真實產品範例",
    exampleTitle: "一份樂譜、結構化輸入與可重複使用的輸出",
    captured: "截圖日期",
    englishInterfaceNote: "截圖沿用目前的英文產品介面。",
    input: "輸入",
    output: "輸出",
    downloadInput: "下載輸入範例",
    downloadOutput: "下載輸出範例",
    workflowEyebrow: "使用流程",
    workflowTitle: "這項流程如何運作",
    workflowBody: "準備處理樂譜時，可從公開頁面進入需要登入的工作區繼續操作。",
    detailEyebrow: "產品說明",
    detailTitle: "使用前須知",
    faqEyebrow: "常見問題",
    faqTitle: (title) => `${title}常見問題`,
    faqBody: "開始處理樂譜前應了解的能力、限制與流程。",
    faqInput: (title) => `${title}接受哪些輸入？`,
    faqEdit: "轉換後還能繼續編輯嗎？",
    faqEditAnswer: "可以。成功匯入後會建立 Score JSON 修訂，可在樂譜工作區繼續校正、移調、播放與匯出。",
    faqCheck: "採用結果前應檢查什麼？",
    relatedEyebrow: "相關流程",
    relatedTitle: "繼續使用同一個樂譜專案",
    relatedBody: "這些頁面共用同一份 MusicXML 與 Score JSON，不會把樂譜送進彼此分離的轉換器。",
    statuses: { Available: "已開放", Beta: "測試版", Preview: "預覽版" },
    softwareSubcategory: "樂譜記譜軟體",
    operatingSystem: "網頁瀏覽器",
    screenshotEvidence: "取自目前英文產品介面的真實功能截圖，用於呈現現有流程。",
    screenshotAlt: (title) => `${title}的真實產品截圖（英文介面）`,
    exampleNotes: "輸入與輸出都保留在同一個結構化樂譜專案中，複雜結果仍須人工檢查。",
  },
  ja: {
    home: "ホーム",
    unavailable: "本番環境での確認待ち",
    actions: { upload: "無料で編集", checkout: "利用プランを見る", scores: "楽譜プロジェクトを開く", unavailable: "公開状況を確認" },
    pricing: "料金",
    moduleEyebrow: "プラットフォーム機能",
    moduleTitle: "MusicXML と Score JSON を基盤に構築",
    moduleBody: "各機能は個別の変換ツールではなく、同じ楽譜プロジェクトモデルにつながります。",
    moduleLabel: "モジュール",
    moduleCardBody: "共通の楽譜プロジェクトワークフローに接続します。",
    exampleEyebrow: "実際の製品例",
    exampleTitle: "1つの楽譜、構造化入力、再利用できる出力",
    captured: "撮影日",
    englishInterfaceNote: "スクリーンショットは現在の英語版製品画面です。",
    input: "入力",
    output: "出力",
    downloadInput: "入力例をダウンロード",
    downloadOutput: "出力例をダウンロード",
    workflowEyebrow: "ワークフロー",
    workflowTitle: "この処理の流れ",
    workflowBody: "楽譜を処理する準備ができたら、公開ページからログイン済みワークスペースへ進みます。",
    detailEyebrow: "製品詳細",
    detailTitle: "利用前の確認事項",
    faqEyebrow: "よくある質問",
    faqTitle: (title) => `${title}についての質問`,
    faqBody: "この楽譜ツールの実用上の制限と想定ワークフローです。",
    faqInput: (title) => `${title}では何を入力できますか？`,
    faqEdit: "変換後の結果を編集できますか？",
    faqEditAnswer: "はい。正常に取り込まれたデータは Score JSON のリビジョンとなり、ワークスペースで修正、移調、再生、書き出しができます。",
    faqCheck: "結果を利用する前に何を確認すべきですか？",
    relatedEyebrow: "関連ワークフロー",
    relatedTitle: "同じ楽譜プロジェクトで続ける",
    relatedBody: "各機能は共通の MusicXML と Score JSON を使用し、別々の変換ツールへ楽譜を渡しません。",
    statuses: { Available: "利用可能", Beta: "ベータ", Preview: "プレビュー" },
    softwareSubcategory: "楽譜作成ソフトウェア",
    operatingSystem: "ウェブブラウザー",
    screenshotEvidence: "現在の英語版製品画面から取得した、実際のワークフローを示すスクリーンショットです。",
    screenshotAlt: (title) => `${title}の実製品スクリーンショット（英語画面）`,
    exampleNotes: "入力と出力は同じ構造化楽譜プロジェクトに保持され、複雑な結果は人による確認が必要です。",
  },
  ko: {
    home: "홈",
    unavailable: "프로덕션 검증 대기 중",
    actions: { upload: "무료로 편집", checkout: "이용 플랜 보기", scores: "악보 프로젝트 열기", unavailable: "출시 상태 확인" },
    pricing: "요금",
    moduleEyebrow: "플랫폼 모듈",
    moduleTitle: "MusicXML과 Score JSON 기반",
    moduleBody: "각 기능은 분리된 일회성 변환기가 아니라 동일한 악보 프로젝트 모델로 연결됩니다.",
    moduleLabel: "모듈",
    moduleCardBody: "공통 악보 프로젝트 작업 흐름에 연결됩니다.",
    exampleEyebrow: "실제 제품 예시",
    exampleTitle: "하나의 악보, 구조화된 입력과 재사용 가능한 출력",
    captured: "캡처 날짜",
    englishInterfaceNote: "스크린샷은 현재 영어 제품 인터페이스를 보여 줍니다.",
    input: "입력",
    output: "출력",
    downloadInput: "입력 예시 다운로드",
    downloadOutput: "출력 예시 다운로드",
    workflowEyebrow: "작업 흐름",
    workflowTitle: "이 경로의 작동 방식",
    workflowBody: "악보를 처리할 준비가 되면 공개 페이지에서 로그인된 작업 공간으로 이동합니다.",
    detailEyebrow: "제품 상세",
    detailTitle: "사용 전 확인 사항",
    faqEyebrow: "자주 묻는 질문",
    faqTitle: (title) => `${title} 관련 질문`,
    faqBody: "이 악보 도구의 실제 한계와 예상 작업 흐름입니다.",
    faqInput: (title) => `${title}에서 어떤 입력을 지원하나요?`,
    faqEdit: "변환 후 결과를 편집할 수 있나요?",
    faqEditAnswer: "예. 정상적으로 가져온 결과는 Score JSON 리비전이 되어 작업 공간에서 교정, 조옮김, 재생 및 내보내기를 할 수 있습니다.",
    faqCheck: "결과를 사용하기 전에 무엇을 확인해야 하나요?",
    relatedEyebrow: "관련 작업 흐름",
    relatedTitle: "같은 악보 프로젝트에서 계속하기",
    relatedBody: "이 기능들은 동일한 MusicXML과 Score JSON을 사용하며 서로 분리된 변환기로 악보를 보내지 않습니다.",
    statuses: { Available: "사용 가능", Beta: "베타", Preview: "미리 보기" },
    softwareSubcategory: "악보 작성 소프트웨어",
    operatingSystem: "웹 브라우저",
    screenshotEvidence: "현재 영어 제품 인터페이스에서 캡처한 실제 작업 흐름 증거입니다.",
    screenshotAlt: (title) => `${title} 실제 제품 스크린샷(영어 인터페이스)`,
    exampleNotes: "입력과 출력은 하나의 구조화된 악보 프로젝트에 유지되며 복잡한 결과는 사람이 검토해야 합니다.",
  },
  fr: {
    home: "Accueil",
    unavailable: "En attente de validation en production",
    actions: { upload: "Modifier gratuitement", checkout: "Voir les offres", scores: "Ouvrir mes projets", unavailable: "Vérifier la disponibilité" },
    pricing: "Tarifs",
    moduleEyebrow: "Modules de la plateforme",
    moduleTitle: "Fondé sur MusicXML et Score JSON",
    moduleBody: "Chaque fonction revient au même modèle de projet musical au lieu d’utiliser un convertisseur isolé.",
    moduleLabel: "Module",
    moduleCardBody: "Relié au flux de travail du projet musical.",
    exampleEyebrow: "Exemple réel du produit",
    exampleTitle: "Une partition, une entrée structurée et une sortie réutilisable",
    captured: "Capture",
    englishInterfaceNote: "La capture montre l’interface actuelle du produit en anglais.",
    input: "Entrée",
    output: "Sortie",
    downloadInput: "Télécharger l’exemple d’entrée",
    downloadOutput: "Télécharger l’exemple de sortie",
    workflowEyebrow: "Processus",
    workflowTitle: "Fonctionnement de ce parcours",
    workflowBody: "Lorsque la partition est prête à être traitée, la page publique mène à l’espace de travail authentifié.",
    detailEyebrow: "Détails du produit",
    detailTitle: "À quoi s’attendre",
    faqEyebrow: "FAQ",
    faqTitle: (title) => `Questions sur ${title}`,
    faqBody: "Limites pratiques et processus prévu pour cet outil de partition.",
    faqInput: (title) => `Quelles entrées ${title} accepte-t-il ?`,
    faqEdit: "Puis-je modifier le résultat après la conversion ?",
    faqEditAnswer: "Oui. Une importation réussie devient une révision Score JSON qui peut être corrigée, transposée, lue et exportée depuis l’espace de travail.",
    faqCheck: "Que faut-il vérifier avant d’utiliser le résultat ?",
    relatedEyebrow: "Processus associés",
    relatedTitle: "Continuer avec le même projet musical",
    relatedBody: "Ces fonctions utilisent la même source MusicXML et Score JSON au lieu d’envoyer la partition vers des convertisseurs séparés.",
    statuses: { Available: "Disponible", Beta: "Bêta", Preview: "Aperçu" },
    softwareSubcategory: "Logiciel de notation musicale",
    operatingSystem: "Navigateur web",
    screenshotEvidence: "Capture de l’interface actuelle du produit en anglais attestant le flux de travail réel.",
    screenshotAlt: (title) => `${title} dans le produit réel (interface en anglais)`,
    exampleNotes: "L’entrée et la sortie restent dans le même projet structuré ; les résultats complexes doivent être vérifiés manuellement.",
  },
  es: {
    home: "Inicio",
    unavailable: "Pendiente de verificación en producción",
    actions: { upload: "Editar gratis", checkout: "Ver planes", scores: "Abrir proyectos de partituras", unavailable: "Comprobar disponibilidad" },
    pricing: "Precios",
    moduleEyebrow: "Módulos de la plataforma",
    moduleTitle: "Creado sobre MusicXML y Score JSON",
    moduleBody: "Cada función vuelve al mismo modelo de proyecto musical en vez de usar un conversor aislado.",
    moduleLabel: "Módulo",
    moduleCardBody: "Conectado al flujo del proyecto musical.",
    exampleEyebrow: "Ejemplo real del producto",
    exampleTitle: "Una partitura, entrada estructurada y salida reutilizable",
    captured: "Captura",
    englishInterfaceNote: "La captura muestra la interfaz actual del producto en inglés.",
    input: "Entrada",
    output: "Salida",
    downloadInput: "Descargar caso de entrada",
    downloadOutput: "Descargar caso de salida",
    workflowEyebrow: "Flujo de trabajo",
    workflowTitle: "Cómo funciona este recorrido",
    workflowBody: "Cuando la partitura está lista para procesarse, la página pública lleva al espacio de trabajo autenticado.",
    detailEyebrow: "Detalle del producto",
    detailTitle: "Qué puedes esperar",
    faqEyebrow: "Preguntas frecuentes",
    faqTitle: (title) => `Preguntas sobre ${title}`,
    faqBody: "Límites prácticos y flujo previsto para esta herramienta de partituras.",
    faqInput: (title) => `¿Qué entradas admite ${title}?`,
    faqEdit: "¿Puedo editar el resultado después de convertirlo?",
    faqEditAnswer: "Sí. Una importación correcta se convierte en una revisión Score JSON que puede corregirse, transportarse, reproducirse y exportarse desde el espacio de trabajo.",
    faqCheck: "¿Qué debo revisar antes de usar el resultado?",
    relatedEyebrow: "Flujos relacionados",
    relatedTitle: "Continúa con el mismo proyecto musical",
    relatedBody: "Estas funciones usan la misma fuente MusicXML y Score JSON en lugar de enviar la partitura a conversores desconectados.",
    statuses: { Available: "Disponible", Beta: "Beta", Preview: "Vista previa" },
    softwareSubcategory: "Software de notación musical",
    operatingSystem: "Navegador web",
    screenshotEvidence: "Captura de la interfaz actual del producto en inglés que demuestra el flujo real.",
    screenshotAlt: (title) => `${title} en el producto real (interfaz en inglés)`,
    exampleNotes: "La entrada y la salida permanecen en el mismo proyecto estructurado; los resultados complejos requieren revisión humana.",
  },
  de: {
    home: "Startseite",
    unavailable: "Produktionsprüfung steht aus",
    actions: { upload: "Kostenlos bearbeiten", checkout: "Tarife ansehen", scores: "Notenprojekte öffnen", unavailable: "Verfügbarkeit prüfen" },
    pricing: "Preise",
    moduleEyebrow: "Plattformmodule",
    moduleTitle: "Auf MusicXML und Score JSON aufgebaut",
    moduleBody: "Jede Funktion nutzt dasselbe Notenprojektmodell statt eines getrennten Einmal-Konverters.",
    moduleLabel: "Modul",
    moduleCardBody: "Mit dem Notenprojekt-Workflow verbunden.",
    exampleEyebrow: "Reales Produktbeispiel",
    exampleTitle: "Eine Partitur, strukturierte Eingabe und wiederverwendbare Ausgabe",
    captured: "Aufgenommen",
    englishInterfaceNote: "Der Screenshot zeigt die aktuelle englische Produktoberfläche.",
    input: "Eingabe",
    output: "Ausgabe",
    downloadInput: "Eingabebeispiel herunterladen",
    downloadOutput: "Ausgabebeispiel herunterladen",
    workflowEyebrow: "Arbeitsablauf",
    workflowTitle: "So funktioniert dieser Weg",
    workflowBody: "Sobald die Partitur bereit ist, führt die öffentliche Seite in den angemeldeten Arbeitsbereich.",
    detailEyebrow: "Produktdetails",
    detailTitle: "Was zu erwarten ist",
    faqEyebrow: "FAQ",
    faqTitle: (title) => `Fragen zu ${title}`,
    faqBody: "Praktische Grenzen und erwarteter Ablauf dieses Notenwerkzeugs.",
    faqInput: (title) => `Welche Eingaben akzeptiert ${title}?`,
    faqEdit: "Kann ich das Ergebnis nach der Konvertierung bearbeiten?",
    faqEditAnswer: "Ja. Erfolgreiche Importe werden zu Score-JSON-Revisionen, die im Arbeitsbereich korrigiert, transponiert, abgespielt und exportiert werden können.",
    faqCheck: "Was sollte ich prüfen, bevor ich das Ergebnis verwende?",
    relatedEyebrow: "Verwandte Abläufe",
    relatedTitle: "Im selben Notenprojekt weiterarbeiten",
    relatedBody: "Diese Funktionen verwenden dieselbe MusicXML- und Score-JSON-Quelle statt voneinander getrennte Konverter.",
    statuses: { Available: "Verfügbar", Beta: "Beta", Preview: "Vorschau" },
    softwareSubcategory: "Notationssoftware",
    operatingSystem: "Webbrowser",
    screenshotEvidence: "Aufnahme der aktuellen englischen Produktoberfläche als Nachweis des realen Arbeitsablaufs.",
    screenshotAlt: (title) => `${title} im realen Produkt (englische Oberfläche)`,
    exampleNotes: "Eingabe und Ausgabe bleiben im selben strukturierten Notenprojekt; komplexe Ergebnisse benötigen eine manuelle Prüfung.",
  },
  ru: {
    home: "Главная",
    unavailable: "Ожидает проверки в рабочей среде",
    actions: { upload: "Редактировать бесплатно", checkout: "Посмотреть тарифы", scores: "Открыть проекты", unavailable: "Проверить доступность" },
    pricing: "Тарифы",
    moduleEyebrow: "Модули платформы",
    moduleTitle: "Основа — MusicXML и Score JSON",
    moduleBody: "Каждая функция работает с общей моделью нотного проекта, а не с отдельным одноразовым конвертером.",
    moduleLabel: "Модуль",
    moduleCardBody: "Связан с единым процессом работы над партитурой.",
    exampleEyebrow: "Реальный пример продукта",
    exampleTitle: "Одна партитура, структурированный ввод и повторно используемый результат",
    captured: "Дата снимка",
    englishInterfaceNote: "На снимке показан текущий англоязычный интерфейс продукта.",
    input: "Ввод",
    output: "Результат",
    downloadInput: "Скачать пример ввода",
    downloadOutput: "Скачать пример результата",
    workflowEyebrow: "Процесс",
    workflowTitle: "Как работает этот сценарий",
    workflowBody: "Когда партитура готова к обработке, публичная страница ведёт в авторизованную рабочую область.",
    detailEyebrow: "Описание продукта",
    detailTitle: "Чего ожидать",
    faqEyebrow: "Вопросы и ответы",
    faqTitle: (title) => `Вопросы о ${title}`,
    faqBody: "Практические ограничения и ожидаемый процесс работы с этим инструментом.",
    faqInput: (title) => `Какие данные принимает ${title}?`,
    faqEdit: "Можно ли редактировать результат после преобразования?",
    faqEditAnswer: "Да. Успешный импорт становится ревизией Score JSON, которую можно исправлять, транспонировать, воспроизводить и экспортировать.",
    faqCheck: "Что проверить перед использованием результата?",
    relatedEyebrow: "Связанные сценарии",
    relatedTitle: "Продолжить в том же нотном проекте",
    relatedBody: "Эти функции используют один источник MusicXML и Score JSON, а не передают партитуру разрозненным конвертерам.",
    statuses: { Available: "Доступно", Beta: "Бета", Preview: "Предпросмотр" },
    softwareSubcategory: "Программа для нотной записи",
    operatingSystem: "Веб-браузер",
    screenshotEvidence: "Снимок текущего англоязычного интерфейса продукта, подтверждающий реальный рабочий процесс.",
    screenshotAlt: (title) => `${title} в реальном продукте (английский интерфейс)`,
    exampleNotes: "Ввод и результат остаются в одном структурированном нотном проекте; сложные результаты требуют ручной проверки.",
  },
} satisfies Record<SupportedLocale, FeaturePageUi>;

export function getFeaturePageUi(locale: SupportedLocale): FeaturePageUi {
  return featurePageUiCatalogs[locale];
}
