import type { WorkspaceMessages } from "../types";
import { enWorkspaceMessages } from "./en";

export const deWorkspaceMessages = {
  ...enWorkspaceMessages,
  pages: { dashboard: { eyebrow: "Dashboard", title: "Konto- und Zugriffsübersicht", body: "Prüfe Anmeldung, Zugriffszeitraum und den nächsten Schritt im Ablauf Noten-PDF → Jianpu.", note: "Aktivierung, Uploads und Warteschlangenaufträge werden in einem Noten-Arbeitsbereich verwaltet." }, jobs: { eyebrow: "Konvertierungsbereich", title: "Konvertierungsaufträge und Ergebnisse", body: "Starte Noten-PDF → Jianpu-Aufträge, verfolge den Status, prüfe die Vorschau und lade das endgültige PDF oder das Entwurfspaket herunter." } },
  banner: { payNow: "Jetzt bezahlen", activationOptions: "Aktivierungsoptionen anzeigen", accountSetup: "Konto einrichten", importScore: "PDF oder Bild importieren", openJobs: "Aufträge öffnen" },
  dashboard: {
    signInFirst: "Melde dich an, um das Dashboard zu sehen.", loadingEyebrow: "Profil wird geladen", loadingTitle: "Kontodaten werden geladen...", accessEyebrow: "Anmeldung erforderlich", accessTitle: "Dieser Arbeitsbereich erfordert eine gültige Anmeldung.", signIn: "Anmelden", createAccount: "Konto erstellen", lookupEyebrow: "Kontosuche", lookupTitle: "Konto nicht gefunden.",
    metrics: { email: "Konto-E-Mail", emailBody: "Angemeldet und bereit für Uploads oder neue Aufträge.", freeEmailBody: "Angemeldet. Du kannst aus einem vollständigen PDF oder Notenbild ein lebenslang kostenloses Projekt erstellen.", entitlement: "Zugriffsrecht", entitlementBody: "Der einjährige Zugriff wird über Aktivierungscodes verwaltet.", route: "Notenstudio", routeValue: "Scannen, bearbeiten, konvertieren, transponieren", routeBody: "MusicXML und Score JSON bilden die Grundlage für Notation, Wiedergabe, Übung und Exporte in mehreren Formaten.", freeRouteValue: "Ein vollständiges Gratisprojekt", freeRouteBody: "Das Gratisprojekt umfasst die aktuellen Projektwerkzeuge und 25 Credits pro Monat. Für mehr Credits ist ein Upgrade möglich." },
    statuses: { active: "Aktiv", expired: "Abgelaufen", inactive: "Inaktiv" }, profile: { eyebrow: "Profil", title: "Kontoübersicht", email: "E-Mail", created: "Erstellt" }, entitlement: { eyebrow: "Zugriffsrecht", title: "Zugriffszeitraum", starts: "Beginn", ends: "Ende", inactive: "Noch nicht aktiv", missing: "Kein Zugriffsrecht" },
    workflow: { eyebrow: "Arbeitsablauf", title: "Nächste Schritte", step1Title: "1. Noten importieren oder erstellen", step1Body: "Starte mit PDF, Bildern, MusicXML, MIDI, Jianpu oder Audio im strukturierten Notenablauf.", step1FreeBody: "Lade ein vollständiges mehrseitiges PDF oder Notenbild hoch, um ein korrigierbares Erkennungsergebnis zu erstellen.", step2Title: "2. Korrigieren, bearbeiten und üben", step2Body: "Nutze einen Versionsverlauf für OMR-Korrektur, grafische Bearbeitung, Transposition, Wiedergabe und Stimmenübung.", step2FreeBody: "Korrigiere das Ergebnis unter Meine Noten und fahre mit Wiedergabe, Transposition, Jianpu, Versionen, Teilen und Export fort.", step3Title: "3. Lieferfassung exportieren", step3Body: "Erzeuge aus der akzeptierten Version MusicXML, MIDI, PDF, Bilder oder hochwertiges Audio.", step3FreeBody: "Wähle Starter, Converter Pro oder einen vorhandenen Code, wenn du mehr Noten oder monatliche Auftragskapazität brauchst." },
    actions: { eyebrow: "Aktionen", title: "Studio verwalten", checkout: "Online bezahlen", uploads: "Uploads öffnen", freeEditing: "Kostenlose Bearbeitung öffnen", jobs: "Aufträge öffnen", redeem: "Weiteren Code einlösen", supportAdmin: "Support-Verwaltung öffnen", signOut: "Abmelden" },
    privacy: { eyebrow: "Datenschutz und Daten", title: "Datenkopie und Kontolebenszyklus verwalten", body: "Exporte enthalten keine Passwörter, Sitzungs- oder Rücksetztoken und keine Freigabeschlüssel. Für die Kontolöschung gilt eine 14-tägige Frist; danach werden Noten, Unterrichtsdaten und Dateien gelöscht und aufzubewahrende Zahlungsprotokolle anonymisiert.", export: "Meine Daten herunterladen", exporting: "Datenexport wird vorbereitet...", exportFailed: "Datenexport fehlgeschlagen.", password: "Aktuelles Passwort", confirmation: "Zur Bestätigung DELETE eingeben", schedule: "Kontolöschung beantragen", scheduling: "Löschung wird geplant...", pending: "Kontolöschung befindet sich in der Frist", pendingBody: "Geplante Löschung", cancel: "Kontolöschung abbrechen", cancelling: "Wird abgebrochen...", required: "Gib dein aktuelles Passwort und genau DELETE ein.", scheduled: "Die Löschung ist geplant. Diese Sitzung wurde abgemeldet; melde dich innerhalb der Frist erneut an, um abzubrechen.", cancelled: "Die Kontolöschung wurde abgebrochen.", exportReady: "Deine Datenkopie wurde heruntergeladen.", statusAria: "Status der Kontodatenanfrage" },
  },
  operations: {
    operations: { eyebrow: "Betrieb", title: "Grundlegender Systemzustand", loading: "API, Speicher, Worker, Zahlung und E-Mail werden geprüft...", error: "Der aktuelle Laufzeitstatus konnte nicht geladen werden.", checked: "Zuletzt geprüft", technicalDetails: "Technische Details", servicesAria: "Status der Laufzeitdienste" },
    support: { eyebrow: "Support", title: "Supportformular auf der Website", body: "Jeder Link öffnet das Formular mit vorausgewählter Kategorie. Die API speichert die Anfrage und sendet automatisch eine Bestätigung.", openForm: "Formular öffnen", publicPage: "Öffentliche Supportseite", templates: { payment: { title: "Zahlungs- und Auftragsprüfung", description: "Wenn der Zugriff nach der Zahlung fehlt oder eine manuelle Prüfung nötig ist." }, activation: { title: "Aktivierung und Zugriffsrecht", description: "Bei abgelehntem Code, fehlendem Zugriff oder falschen Laufzeiten." }, job: { title: "Upload- oder Ergebnisproblem", description: "Bei PDF-Fehlern, blockierten Aufträgen, defekten Downloads oder manueller Ergebnisprüfung." }, privacy: { title: "Datenschutz- oder Löschanfrage", description: "Für Löschung, Export oder manuelle Datenschutzprüfung." } } },
    statuses: { ok: "OK", warning: "Warnung", error: "Fehler", disabled: "Deaktiviert" }, serviceLabels: { api: "Anwendungs-API", database: "Datenbank", storage: "Dateispeicher", worker: "Erkennungs-Worker", payment: "Zahlungskonfiguration", email: "E-Mail-Benachrichtigungen", unknown: "Systemdienst" }, serviceMessages: { ok: "Funktioniert normal.", warning: "Verfügbar, aber Konfiguration oder Laufzeit sollten geprüft werden.", error: "Nicht verfügbar. Versuche es später erneut oder kontaktiere den Support.", disabled: "Derzeit deaktiviert." },
  },
  jobs: {
    signInFirst: "Melde dich zuerst an.", uploadFirst: "Lade zuerst ein PDF hoch.", downloadFailed: "Download fehlgeschlagen.", createdJob: "Auftrag {id} wurde erstellt.", summary: { queued: ["In Warteschlange", "Wartet auf den Worker."], processing: ["In Bearbeitung", "Vorschau und Ausgabepaket werden erzeugt."], completed: ["Abgeschlossen", "Endgültiges PDF oder Entwurfspaket kann heruntergeladen werden."] },
    create: { eyebrow: "Konvertierung erstellen", title: "Noten-zu-Jianpu-Auftrag starten", body: "Wähle eine hochgeladene Quelle, lasse die Richtung gesperrt und sende das PDF in die Warteschlange.", input: "Eingabedatei", inputPlaceholder: "Hochgeladenes PDF auswählen", direction: "Richtung", lockedDirection: "Noten-PDF zu Jianpu", draftTitle: "Entwurfsorientierter Ablauf", draftBody: "Seiten mit geringer Sicherheit können Entwürfe bleiben, statt zu früh hochgestuft zu werden.", source: "Ausgewählte Quelle", noSource: "Keine Quelle ausgewählt", uploadHint: "Lade zuerst ein PDF hoch, wenn die Auswahl leer ist.", createButton: "Auftrag erstellen", creating: "Wird erstellt...", refresh: "Warteschlange aktualisieren", uploads: "Uploads öffnen", recentSources: "Letzte Quellen", emptySources: "Noch keine PDFs. Lade zuerst eines hoch und starte anschließend die Konvertierung.", useThis: "Diese Datei verwenden" },
    monitor: { eyebrow: "Warteschlangenmonitor", title: "Live-Konvertierung", auto: "Automatische Aktualisierung", loading: "Aufträge werden geladen...", empty: "Noch keine Aufträge. Wähle links ein PDF und erstelle den ersten Auftrag.", latest: "Neuester Auftrag", created: "Erstellt", resultCenter: "Ergebnis", final: "Dieser Lauf ist als endgültiges Ergebnis eingestuft.", draft: "Dieser Lauf bleibt als Entwurf erhalten.", none: "Dieser Lauf hat noch kein herunterladbares Ergebnis.", previewWaiting: "Die Vorschau erscheint, sobald der Worker sie erzeugt.", primary: "Hauptausgabe", primaryTitle: "Endgültiges PDF", primaryBody: "Verfügbar, wenn der Lauf erfolgreich zum Endergebnis wird.", fallback: "Ersatzausgabe", fallbackTitle: "Entwurfspaket", fallbackBody: "Verfügbar, wenn eine manuelle Korrektur außerhalb des Browsers nötig ist.", downloadPdf: "Ergebnis-PDF herunterladen", downloadDraft: "Entwurfspaket herunterladen", notReady: "Nicht bereit", liveAria: "Live-Konvertierungswarteschlange" },
    archive: { eyebrow: "Letzte Aufträge", title: "Warteschlangenverlauf", body: "Vorschau, Ergebnistyp und Downloads bleiben zur Prüfung älterer Läufe erhalten." }, statuses: { queued: "In Warteschlange", processing: "In Bearbeitung", completed: "Abgeschlossen", failed: "Fehlgeschlagen" }, resultKinds: { none: "Keines", final: "Endgültig", draft: "Entwurf" }, directions: { staff_pdf_to_numbered: "Noten-PDF → Jianpu" }, phases: { completed: "Abgeschlossen", running: "Läuft", waiting: "Wartet" },
  },
  uploads: {
    signInFirst: "Melde dich zuerst an.", chooseFile: "Wähle eine PDF-Datei.", uploadFailed: "Upload fehlgeschlagen.", downloadFailed: "Download fehlgeschlagen.", uploaded: "{name} wurde hochgeladen.", previewAwaiting: "Warten auf PDF-Upload", metrics: { stored: ["Gespeicherte Noten", "Jeder Upload wird zu einer wiederverwendbaren Quelle."], format: ["Akzeptiertes Format", "Der aktuelle Produktionsumfang akzeptiert nur Noten-PDFs."], storage: ["Gesamtspeicher", "Hilfreich zur Kontrolle von Stapel-Uploads vor neuen Aufträgen."] },
    upload: { eyebrow: "Noten hochladen", title: "Noten ins Studio bringen", body: "Füge über den Uploadbereich und die Vorschau eine wiederverwendbare Quelldatei hinzu.", dropTitle: "Noten hier ablegen oder Datei auswählen", dropBody: "Derzeit werden nur Noten-PDFs unterstützt. Bilder und Rückkonvertierung gehören nicht zu dieser Version.", maxSize: "Maximale Größe gemäß API-Limit", cloud: "Aus der Cloud importieren", planned: "Geplant", selected: "ausgewählt und uploadbereit.", empty: "Keine Datei ausgewählt. Wähle ein PDF als wiederverwendbare Quelle.", uploadButton: "PDF hochladen", uploading: "Upload läuft...", clear: "Auswahl löschen", jobs: "Zu den Aufträgen", inputAria: "Noten-PDF auswählen" },
    preview: { eyebrow: "Live-Vorschau", title: "Aktueller Upload", ready: "Bereit für die Warteschlange", numbered: "Jianpu-Vorschau", previewBody: "Ein klares PDF kann zum Endergebnis werden; schwaches Material bleibt als Entwurf verfügbar.", latest: "Neueste gespeicherte Quelle", latestEmpty: "Keine gespeicherte Quelle", latestHint: "Lade ein PDF hoch, um die Warteschlange zu aktivieren.", next: "Nächster Schritt", nextTitle: "Konvertierungsauftrag erstellen", nextBody: "Nach dem Speichern bleibt die Richtung Noten-PDF → Jianpu gesperrt.", openQueue: "Warteschlange öffnen", downloadSource: "Quelle herunterladen" },
    stored: { eyebrow: "Gespeicherte Dateien", title: "Hochgeladene Noten-PDFs", body: "Diese Dateien können als Auftragseingabe dienen. Der Download prüft die genaue, von der API gespeicherte Quelle.", loading: "Dateien werden geladen...", empty: "Noch keine Dateien. Lade zuerst ein Noten-PDF hoch.", download: "Herunterladen" }, fileKinds: { input_pdf: "Eingabe-PDF", unknown: "Datei" },
  },
} satisfies WorkspaceMessages;
