import type { WorkspaceMessages } from "../types";
import { enWorkspaceMessages } from "./en";

export const esWorkspaceMessages = {
  ...enWorkspaceMessages,
  pages: { dashboard: { eyebrow: "Panel", title: "Resumen de cuenta y acceso", body: "Revisa el inicio de sesión, las fechas de acceso y el siguiente paso del flujo PDF en pentagrama → Jianpu.", note: "La activación, las cargas y las tareas en cola se gestionan en un único espacio de partituras." }, jobs: { eyebrow: "Espacio de conversión", title: "Tareas de conversión y resultados", body: "Crea tareas PDF en pentagrama → Jianpu, consulta su estado y vista previa, y descarga el PDF final o el paquete borrador." } },
  banner: { payNow: "Pagar ahora", activationOptions: "Ver opciones de activación", accountSetup: "Configurar cuenta", importScore: "Importar PDF o imagen", openJobs: "Abrir tareas" },
  dashboard: {
    signInFirst: "Inicia sesión para ver el panel.", loadingEyebrow: "Cargando perfil", loadingTitle: "Cargando datos de la cuenta...", accessEyebrow: "Acceso necesario", accessTitle: "Esta zona requiere una sesión válida.", signIn: "Iniciar sesión", createAccount: "Crear cuenta", lookupEyebrow: "Búsqueda de cuenta", lookupTitle: "No se encontró la cuenta.",
    metrics: { email: "Correo de la cuenta", emailBody: "Sesión iniciada; puedes cargar archivos o crear tareas.", freeEmailBody: "Sesión iniciada. Puedes crear un proyecto gratuito de por vida a partir de un PDF completo o una imagen de partitura.", entitlement: "Acceso", entitlementBody: "El acceso de un año se administra con códigos de activación.", route: "Estudio de partituras", routeValue: "Escanear, editar, convertir y transportar", routeBody: "MusicXML y Score JSON sustentan la notación, reproducción, práctica y exportación multiformato.", freeRouteValue: "Un proyecto gratuito completo", freeRouteBody: "El proyecto gratuito incluye las herramientas actuales y 25 créditos al mes. Mejora el plan para obtener más." },
    statuses: { active: "Activo", expired: "Caducado", inactive: "Inactivo" }, profile: { eyebrow: "Perfil", title: "Resumen de cuenta", email: "Correo", created: "Creada" }, entitlement: { eyebrow: "Acceso", title: "Periodo de acceso", starts: "Inicio", ends: "Fin", inactive: "Aún no activo", missing: "Sin acceso" },
    workflow: { eyebrow: "Flujo de trabajo", title: "Siguientes pasos", step1Title: "1. Importar o crear una partitura", step1Body: "Comienza con PDF, imágenes, MusicXML, MIDI, Jianpu o audio y entra al flujo estructurado.", step1FreeBody: "Carga un PDF completo de varias páginas o una imagen de partitura para crear un resultado de reconocimiento corregible.", step2Title: "2. Corregir, editar y practicar", step2Body: "Usa un único historial para corrección OMR, edición gráfica, transporte, reproducción y práctica por partes.", step2FreeBody: "Corrige el resultado en Mis partituras y continúa con reproducción, transporte, Jianpu, versiones, compartir y exportar.", step3Title: "3. Exportar una versión final", step3Body: "Genera MusicXML, MIDI, PDF, imágenes o audio de alta calidad desde la revisión aceptada.", step3FreeBody: "Elige Starter, Converter Pro o un código existente cuando necesites más partituras o capacidad mensual." },
    actions: { eyebrow: "Acciones", title: "Administrar el estudio", checkout: "Pagar en línea", uploads: "Abrir cargas", freeEditing: "Abrir edición gratuita", jobs: "Abrir tareas", redeem: "Canjear otro código", supportAdmin: "Abrir administración de soporte", signOut: "Cerrar sesión" },
    privacy: { eyebrow: "Privacidad y datos", title: "Administra tu copia de datos y tu cuenta", body: "La exportación excluye contraseñas, tokens de sesión y restablecimiento, y secretos compartidos. La eliminación tiene 14 días de gracia; después borra partituras, datos de clase y archivos, y anonimiza los registros de pago que deban conservarse.", export: "Descargar mis datos", exporting: "Preparando exportación...", exportFailed: "La exportación de datos falló.", password: "Contraseña actual", confirmation: "Escribe DELETE para confirmar", schedule: "Solicitar eliminación", scheduling: "Programando eliminación...", pending: "La eliminación está en periodo de gracia", pendingBody: "Eliminación programada", cancel: "Cancelar eliminación", cancelling: "Cancelando...", required: "Introduce tu contraseña actual y escribe DELETE exactamente.", scheduled: "La eliminación está programada. La sesión se cerró; inicia sesión durante el periodo de gracia para cancelarla.", cancelled: "La eliminación de la cuenta se canceló.", exportReady: "Se descargó tu copia de datos.", statusAria: "Estado de la solicitud de datos" },
  },
  operations: {
    operations: { eyebrow: "Operaciones", title: "Estado básico del sistema", loading: "Comprobando API, almacenamiento, Worker, pagos y correo...", error: "No se pudo cargar el estado actual del sistema.", checked: "Última comprobación", technicalDetails: "Detalles técnicos", servicesAria: "Estado de los servicios" },
    support: { eyebrow: "Soporte", title: "Formulario de soporte del sitio", body: "Cada enlace abre el formulario con la categoría seleccionada. La API registra la solicitud y envía automáticamente un correo de confirmación.", openForm: "Abrir formulario", publicPage: "Página pública de soporte", templates: { payment: { title: "Revisión de pago y pedido", description: "Úsalo si el acceso no aparece tras pagar o se necesita una revisión manual." }, activation: { title: "Problema de activación o acceso", description: "Para códigos rechazados, acceso sin activar o fechas incorrectas." }, job: { title: "Problema de carga o resultado", description: "Para PDF fallidos, tareas bloqueadas, descargas rotas o revisión manual del resultado." }, privacy: { title: "Solicitud de privacidad o eliminación", description: "Para eliminaciones, exportaciones o revisiones manuales de privacidad." } } },
    statuses: { ok: "Correcto", warning: "Atención", error: "Error", disabled: "Desactivado" }, serviceLabels: { api: "API de la aplicación", database: "Base de datos", storage: "Almacenamiento", worker: "Worker de reconocimiento", payment: "Configuración de pagos", email: "Notificaciones por correo", unknown: "Servicio del sistema" }, serviceMessages: { ok: "Funciona con normalidad.", warning: "Está disponible, pero requiere revisar la configuración o ejecución.", error: "No está disponible. Inténtalo más tarde o contacta con soporte.", disabled: "Actualmente desactivado." },
  },
  jobs: {
    signInFirst: "Inicia sesión primero.", uploadFirst: "Carga primero un PDF.", downloadFailed: "La descarga falló.", createdJob: "Se creó la tarea {id}.", summary: { queued: ["En cola", "Esperando a que el Worker la recoja."], processing: ["Procesando", "Generando la vista previa y los archivos de salida."], completed: ["Completada", "El PDF final o paquete borrador está disponible."] },
    create: { eyebrow: "Crear conversión", title: "Enviar pentagrama a Jianpu", body: "Elige una fuente cargada, mantén la dirección bloqueada y envía el PDF a la cola.", input: "Archivo de entrada", inputPlaceholder: "Selecciona un PDF cargado", direction: "Dirección", lockedDirection: "PDF en pentagrama a Jianpu", draftTitle: "Flujo consciente de borradores", draftBody: "Las páginas con baja confianza pueden mantenerse como borrador en vez de ascender demasiado pronto.", source: "Fuente seleccionada", noSource: "No hay fuente seleccionada", uploadHint: "Carga primero un PDF si la lista está vacía.", createButton: "Crear tarea", creating: "Creando...", refresh: "Actualizar cola", uploads: "Abrir cargas", recentSources: "Fuentes recientes", emptySources: "No hay PDF cargados. Carga uno y vuelve para crear la conversión.", useThis: "Usar este archivo" },
    monitor: { eyebrow: "Monitor de cola", title: "Conversión en directo", auto: "Actualización automática", loading: "Cargando tareas...", empty: "No hay tareas. Elige un PDF a la izquierda y crea la primera.", latest: "Última tarea", created: "Creada", resultCenter: "Centro de resultados", final: "Esta ejecución está clasificada como final.", draft: "Esta ejecución se conserva como borrador.", none: "Esta ejecución aún no produjo un resultado descargable.", previewWaiting: "La vista previa aparecerá cuando el Worker la genere.", primary: "Salida principal", primaryTitle: "PDF final", primaryBody: "Disponible cuando la ejecución asciende correctamente a final.", fallback: "Salida alternativa", fallbackTitle: "Paquete borrador", fallbackBody: "Disponible cuando los resultados necesitan corrección manual externa.", downloadPdf: "Descargar PDF", downloadDraft: "Descargar borrador", notReady: "No disponible", liveAria: "Cola de conversión en directo" },
    archive: { eyebrow: "Tareas recientes", title: "Historial de la cola", body: "La vista previa, el tipo de resultado y las descargas quedan disponibles para revisar ejecuciones anteriores." }, statuses: { queued: "En cola", processing: "Procesando", completed: "Completada", failed: "Fallida" }, resultKinds: { none: "Ninguno", final: "Final", draft: "Borrador" }, directions: { staff_pdf_to_numbered: "PDF en pentagrama → Jianpu" }, phases: { completed: "Completada", running: "En curso", waiting: "Esperando" },
  },
  uploads: {
    signInFirst: "Inicia sesión primero.", chooseFile: "Selecciona un archivo PDF.", uploadFailed: "La carga falló.", downloadFailed: "La descarga falló.", uploaded: "Se cargó {name} correctamente.", previewAwaiting: "Esperando un PDF", metrics: { stored: ["Partituras guardadas", "Cada carga se convierte en una fuente reutilizable para conversiones."], format: ["Formato admitido", "El entorno actual solo admite PDF en pentagrama."], storage: ["Almacenamiento total", "Útil para revisar cargas por lotes antes de crear tareas."] },
    upload: { eyebrow: "Cargar partitura", title: "Añadir una partitura al estudio", body: "Añade una fuente reutilizable desde el área de carga y su contexto de vista previa.", dropTitle: "Suelta una partitura o elige un archivo", dropBody: "Solo se admiten PDF en pentagrama. Las imágenes y la conversión inversa quedan fuera de esta versión.", maxSize: "El tamaño máximo sigue los límites de la API", cloud: "Importar desde la nube", planned: "Previsto", selected: "seleccionado y listo para cargar.", empty: "No hay archivo seleccionado. Elige un PDF para crear una fuente reutilizable.", uploadButton: "Cargar PDF", uploading: "Cargando...", clear: "Borrar selección", jobs: "Ir a tareas", inputAria: "Elegir un PDF de partitura" },
    preview: { eyebrow: "Vista previa en tiempo real", title: "Carga actual", ready: "Lista para la cola", numbered: "Vista previa Jianpu", previewBody: "Un PDF claro puede ascender a resultado final; material deficiente seguirá como borrador.", latest: "Última fuente guardada", latestEmpty: "No hay fuentes guardadas", latestHint: "Carga un PDF para habilitar la cola.", next: "Siguiente paso", nextTitle: "Crear la conversión", nextBody: "Al guardar el PDF, la dirección permanece PDF en pentagrama → Jianpu.", openQueue: "Abrir cola", downloadSource: "Descargar fuente" },
    stored: { eyebrow: "Archivos guardados", title: "PDF de partituras cargados", body: "Estos archivos pueden usarse como entrada. La descarga permite verificar la fuente exacta guardada por la API.", loading: "Cargando archivos...", empty: "No hay archivos. Carga primero un PDF de partitura.", download: "Descargar" }, fileKinds: { input_pdf: "PDF de entrada", unknown: "Archivo" },
  },
} satisfies WorkspaceMessages;
