import type { WorkspaceMessages } from "../types";
import { enWorkspaceMessages } from "./en";

export const frWorkspaceMessages = {
  ...enWorkspaceMessages,
  pages: { dashboard: { eyebrow: "Tableau de bord", title: "Compte et droits d’accès", body: "Consultez la connexion, les dates d’accès et la prochaine étape du flux PDF sur portée → Jianpu.", note: "Activation, imports et tâches en attente sont réunis dans un même espace de partitions." }, jobs: { eyebrow: "Espace de conversion", title: "Tâches de conversion et résultats", body: "Lancez des conversions PDF sur portée → Jianpu, suivez leur état, consultez l’aperçu et téléchargez le PDF final ou le lot brouillon." } },
  banner: { payNow: "Payer maintenant", activationOptions: "Voir les options d’activation", accountSetup: "Configurer le compte", importScore: "Importer un PDF ou une image", openJobs: "Ouvrir les tâches" },
  dashboard: {
    signInFirst: "Connectez-vous pour afficher le tableau de bord.", loadingEyebrow: "Chargement du profil", loadingTitle: "Chargement du compte…", accessEyebrow: "Connexion requise", accessTitle: "Cet espace nécessite une connexion valide.", signIn: "Se connecter", createAccount: "Créer un compte", lookupEyebrow: "Recherche du compte", lookupTitle: "Compte introuvable.",
    metrics: { email: "E-mail du compte", emailBody: "Vous êtes connecté et pouvez importer un fichier ou créer une tâche.", freeEmailBody: "Vous êtes connecté. Vous pouvez créer un projet gratuit à vie depuis un PDF complet ou une image de partition.", entitlement: "Droits d’accès", entitlementBody: "L’accès d’un an est géré par des codes d’activation.", route: "Studio de partitions", routeValue: "Numériser, modifier, convertir, transposer", routeBody: "MusicXML et Score JSON alimentent la notation, la lecture, la pratique et les exports multiformats.", freeRouteValue: "Un projet gratuit complet", freeRouteBody: "Le projet gratuit inclut les outils actuels et 25 crédits par mois. Passez à une offre supérieure pour en obtenir davantage." },
    statuses: { active: "Actif", expired: "Expiré", inactive: "Inactif" }, profile: { eyebrow: "Profil", title: "Aperçu du compte", email: "E-mail", created: "Créé le" }, entitlement: { eyebrow: "Droits d’accès", title: "Période d’accès", starts: "Début", ends: "Fin", inactive: "Pas encore actif", missing: "Aucun droit d’accès" },
    workflow: { eyebrow: "Flux de travail", title: "Prochaines étapes", step1Title: "1. Importer ou créer une partition", step1Body: "Partez d’un PDF, d’une image, de MusicXML, MIDI, Jianpu ou d’un audio pour entrer dans le flux structuré.", step1FreeBody: "Importez un PDF multipage complet ou une image de partition pour créer un résultat de reconnaissance corrigible.", step2Title: "2. Corriger, modifier et pratiquer", step2Body: "Utilisez un même historique pour la correction OMR, l’édition graphique, la transposition, la lecture et la pratique par partie.", step2FreeBody: "Corrigez le résultat dans Mes partitions, puis poursuivez avec la lecture, la transposition, Jianpu, les versions, le partage et l’export.", step3Title: "3. Exporter une version livrable", step3Body: "Produisez MusicXML, MIDI, PDF, images ou audio haute qualité depuis la révision validée.", step3FreeBody: "Choisissez Starter, Converter Pro ou un code existant lorsque vous avez besoin de plus de partitions ou de capacité mensuelle." },
    actions: { eyebrow: "Actions", title: "Gérer le studio", checkout: "Payer en ligne", uploads: "Ouvrir les imports", freeEditing: "Ouvrir l’édition gratuite", jobs: "Ouvrir les tâches", redeem: "Utiliser un autre code", supportAdmin: "Ouvrir l’administration du support", signOut: "Se déconnecter" },
    privacy: { eyebrow: "Confidentialité et données", title: "Gérer votre copie de données et votre compte", body: "L’export exclut mots de passe, jetons de session et de réinitialisation, ainsi que les secrets de partage. La suppression comporte un délai de grâce de 14 jours, puis efface partitions, données de cours et fichiers tout en anonymisant les traces de paiement à conserver.", export: "Télécharger mes données", exporting: "Préparation de l’export…", exportFailed: "Échec de l’export des données.", password: "Mot de passe actuel", confirmation: "Saisissez DELETE pour confirmer", schedule: "Demander la suppression", scheduling: "Planification de la suppression…", pending: "La suppression est dans son délai de grâce", pendingBody: "Suppression prévue", cancel: "Annuler la suppression", cancelling: "Annulation…", required: "Saisissez votre mot de passe actuel et exactement DELETE.", scheduled: "La suppression est planifiée. Cette session est déconnectée ; reconnectez-vous pendant le délai de grâce pour l’annuler.", cancelled: "La suppression du compte a été annulée.", exportReady: "Votre copie de données a été téléchargée.", statusAria: "État de la demande de données" },
  },
  operations: {
    operations: { eyebrow: "Exploitation", title: "État de santé essentiel", loading: "Vérification de l’API, du stockage, du Worker, du paiement et des e-mails…", error: "Impossible de charger l’état actuel des services.", checked: "Dernière vérification", technicalDetails: "Détails techniques", servicesAria: "État des services d’exécution" },
    support: { eyebrow: "Assistance", title: "Formulaire d’assistance intégré", body: "Chaque lien ouvre le formulaire avec la catégorie présélectionnée. L’API enregistre la demande et envoie automatiquement un e-mail de confirmation.", openForm: "Ouvrir le formulaire", publicPage: "Page publique d’assistance", templates: { payment: { title: "Paiement et commande", description: "À utiliser si l’accès n’apparaît pas après paiement ou si une vérification manuelle est nécessaire." }, activation: { title: "Activation et droits d’accès", description: "Pour un code refusé, un accès non activé ou des dates incorrectes." }, job: { title: "Import ou résultat", description: "Pour un PDF refusé, une tâche bloquée, un téléchargement cassé ou une vérification du résultat." }, privacy: { title: "Confidentialité ou suppression", description: "Pour une suppression, un export ou une demande manuelle liée à la confidentialité." } } },
    statuses: { ok: "Opérationnel", warning: "Attention", error: "Erreur", disabled: "Désactivé" }, serviceLabels: { api: "API de l’application", database: "Base de données", storage: "Stockage de fichiers", worker: "Worker de reconnaissance", payment: "Configuration du paiement", email: "Notifications e-mail", unknown: "Service système" }, serviceMessages: { ok: "Fonctionnement normal.", warning: "Disponible, mais la configuration ou l’exécution demande une vérification.", error: "Indisponible. Réessayez plus tard ou contactez l’assistance.", disabled: "Actuellement désactivé." },
  },
  jobs: {
    signInFirst: "Connectez-vous d’abord.", uploadFirst: "Importez d’abord un PDF.", downloadFailed: "Échec du téléchargement.", createdJob: "Tâche {id} créée.", summary: { queued: ["En attente", "En attente de prise en charge par le Worker."], processing: ["En cours", "Création de l’aperçu et des fichiers de sortie."], completed: ["Terminée", "Le PDF final ou le lot brouillon est disponible."] },
    create: { eyebrow: "Créer une conversion", title: "Lancer la conversion portée vers Jianpu", body: "Choisissez une source importée, conservez la direction verrouillée et envoyez le PDF dans la file.", input: "Fichier d’entrée", inputPlaceholder: "Choisir un PDF importé", direction: "Direction", lockedDirection: "PDF sur portée vers Jianpu", draftTitle: "Pipeline sensible aux brouillons", draftBody: "Les pages moins fiables peuvent rester en brouillon au lieu d’être promues trop tôt.", source: "Source sélectionnée", noSource: "Aucune source sélectionnée", uploadHint: "Importez d’abord un PDF si la liste est vide.", createButton: "Créer la tâche", creating: "Création…", refresh: "Actualiser la file", uploads: "Ouvrir les imports", recentSources: "Sources récentes", emptySources: "Aucun PDF importé. Importez-en un, puis revenez lancer la conversion.", useThis: "Utiliser ce fichier" },
    monitor: { eyebrow: "Suivi de la file", title: "Conversion en direct", auto: "Actualisation automatique", loading: "Chargement des tâches…", empty: "Aucune tâche. Choisissez un PDF à gauche et créez la première conversion.", latest: "Dernière tâche", created: "Créée", resultCenter: "Résultat", final: "Cette exécution est classée comme résultat final.", draft: "Cette exécution est conservée comme brouillon.", none: "Cette exécution n’a pas encore produit de résultat téléchargeable.", previewWaiting: "L’aperçu apparaîtra quand le Worker l’aura produit.", primary: "Sortie principale", primaryTitle: "PDF final", primaryBody: "Disponible lorsque l’exécution est validée comme finale.", fallback: "Sortie de secours", fallbackTitle: "Lot brouillon", fallbackBody: "Disponible lorsque les éléments nécessitent une correction manuelle externe.", downloadPdf: "Télécharger le PDF", downloadDraft: "Télécharger le brouillon", notReady: "Pas prêt", liveAria: "File de conversion en direct" },
    archive: { eyebrow: "Tâches récentes", title: "Historique de la file", body: "Aperçu, type de résultat et téléchargements restent disponibles pour revoir les anciennes exécutions." }, statuses: { queued: "En attente", processing: "En cours", completed: "Terminée", failed: "Échouée" }, resultKinds: { none: "Aucun", final: "Final", draft: "Brouillon" }, directions: { staff_pdf_to_numbered: "PDF sur portée → Jianpu" }, phases: { completed: "Terminée", running: "En cours", waiting: "En attente" },
  },
  uploads: {
    signInFirst: "Connectez-vous d’abord.", chooseFile: "Choisissez un fichier PDF.", uploadFailed: "Échec de l’import.", downloadFailed: "Échec du téléchargement.", uploaded: "{name} a été importé.", previewAwaiting: "En attente d’un PDF", metrics: { stored: ["Partitions stockées", "Chaque import devient une source réutilisable pour les conversions."], format: ["Format accepté", "La production accepte actuellement uniquement les PDF sur portée."], storage: ["Stockage total", "Utile pour contrôler les imports groupés avant de créer des tâches."] },
    upload: { eyebrow: "Importer une partition", title: "Ajouter une partition au studio", body: "Ajoutez une source réutilisable dans la zone d’import avec son aperçu.", dropTitle: "Déposez une partition ou choisissez un fichier", dropBody: "Seuls les PDF sur portée sont pris en charge. Les images et la conversion inverse ne font pas partie de cette version.", maxSize: "La taille maximale suit les limites de l’API", cloud: "Importer du cloud", planned: "Prévu", selected: "sélectionné et prêt à être importé.", empty: "Aucun fichier sélectionné. Choisissez un PDF pour créer une source réutilisable.", uploadButton: "Importer le PDF", uploading: "Import…", clear: "Effacer la sélection", jobs: "Voir les tâches", inputAria: "Choisir un PDF de partition" },
    preview: { eyebrow: "Aperçu en direct", title: "Import actuel", ready: "Prêt pour la file", numbered: "Aperçu Jianpu", previewBody: "Un PDF net peut être promu en résultat final ; un document faible reste disponible en brouillon.", latest: "Dernière source stockée", latestEmpty: "Aucune source stockée", latestHint: "Importez un PDF pour accéder à la file.", next: "Étape suivante", nextTitle: "Créer la conversion", nextBody: "Une fois le PDF stocké, la direction reste PDF sur portée → Jianpu.", openQueue: "Ouvrir la file", downloadSource: "Télécharger la source" },
    stored: { eyebrow: "Fichiers stockés", title: "PDF de partitions importés", body: "Ces fichiers peuvent alimenter une tâche. Le téléchargement permet de vérifier la source exacte stockée par l’API.", loading: "Chargement des fichiers…", empty: "Aucun fichier importé. Commencez par un PDF de partition.", download: "Télécharger" }, fileKinds: { input_pdf: "PDF d’entrée", unknown: "Fichier" },
  },
} satisfies WorkspaceMessages;
