import type { WorkspaceMessages } from "../types";
import { enWorkspaceMessages } from "./en";

export const jaWorkspaceMessages = {
  ...enWorkspaceMessages,
  pages: { dashboard: { eyebrow: "ダッシュボード", title: "アカウントと利用権限の概要", body: "ログイン状態、利用期限、五線譜 PDF → 簡譜ワークフローの次の操作を確認します。", note: "有効化、アップロード、キュー処理を一つの楽譜ワークスペースで管理します。" }, jobs: { eyebrow: "変換ワークスペース", title: "変換ジョブと出力の確認", body: "五線譜 PDF → 簡譜ジョブを登録し、状態とプレビューを確認して、最終 PDF またはドラフト一式をダウンロードします。" } },
  banner: { payNow: "今すぐ購入", activationOptions: "有効化方法を見る", accountSetup: "アカウント設定を見る", importScore: "PDF または画像を読み込む", openJobs: "ジョブを開く" },
  dashboard: {
    signInFirst: "ダッシュボードを表示するにはログインしてください。", loadingEyebrow: "プロフィールを取得中", loadingTitle: "アカウント情報を読み込んでいます...", accessEyebrow: "ログインが必要です", accessTitle: "このワークスペースには有効なログインが必要です。", signIn: "ログイン", createAccount: "アカウントを作成", lookupEyebrow: "アカウント検索", lookupTitle: "アカウントが見つかりません。",
    metrics: { email: "アカウントのメール", emailBody: "ログイン済みです。アップロードやジョブ作成を続けられます。", freeEmailBody: "ログイン済みです。完全な PDF または楽譜画像から、生涯無料の 1 プロジェクトを作成できます。", entitlement: "利用権限", entitlementBody: "1 年間のアクセスは有効化コードで管理されます。", route: "楽譜スタジオ", routeValue: "スキャン、編集、変換、移調", routeBody: "MusicXML と Score JSON を基盤に、記譜、再生、練習、複数形式への書き出しを行います。", freeRouteValue: "完全な無料プロジェクト 1 件", freeRouteBody: "無料プロジェクトでは現行のプロジェクト機能と毎月 25 クレジットを利用できます。追加分はアップグレードしてください。" },
    statuses: { active: "有効", expired: "期限切れ", inactive: "未有効化" }, profile: { eyebrow: "プロフィール", title: "アカウント概要", email: "メール", created: "作成日時" }, entitlement: { eyebrow: "利用権限", title: "アクセス期間", starts: "開始", ends: "終了", inactive: "まだ有効ではありません", missing: "利用権限なし" },
    workflow: { eyebrow: "ワークフロー", title: "次の操作", step1Title: "1. 楽譜を読み込む／作成する", step1Body: "PDF、画像、MusicXML、MIDI、簡譜、音声から構造化楽譜ワークフローを開始します。", step1FreeBody: "完全な複数ページ PDF または楽譜画像をアップロードし、修正可能な認識候補を作成します。", step2Title: "2. 修正、編集、練習", step2Body: "一つの改訂履歴で OMR 修正、グラフィカル編集、移調、再生、パート練習を行います。", step2FreeBody: "「マイスコア」で候補を修正し、再生、移調、簡譜、版管理、共有、書き出しを続けます。", step3Title: "3. 納品版を書き出す", step3Body: "承認済みの版から MusicXML、MIDI、PDF、画像、高品質音声を生成します。", step3FreeBody: "楽譜数や月間ジョブ容量がさらに必要な場合は、Starter、Converter Pro、または既存コードを利用します。" },
    actions: { eyebrow: "操作", title: "スタジオを管理", checkout: "オンラインで購入", uploads: "アップロードを開く", freeEditing: "無料編集を開く", jobs: "ジョブを開く", redeem: "別のコードを利用", supportAdmin: "サポート管理を開く", signOut: "ログアウト" },
    privacy: { eyebrow: "プライバシーとデータ", title: "データコピーとアカウントのライフサイクルを管理", body: "書き出しにはパスワード、セッショントークン、リセットトークン、共有シークレットは含まれません。アカウント削除には 14 日間の猶予があり、その後、楽譜、授業データ、ファイルを削除し、保存が必要な決済監査記録を匿名化します。", export: "自分のデータをダウンロード", exporting: "データを書き出しています...", exportFailed: "データの書き出しに失敗しました。", password: "現在のパスワード", confirmation: "確認のため DELETE と入力", schedule: "アカウント削除を申請", scheduling: "削除を予約しています...", pending: "アカウント削除の猶予期間中です", pendingBody: "削除予定日時", cancel: "アカウント削除を取り消す", cancelling: "取り消しています...", required: "現在のパスワードを入力し、DELETE と正確に入力してください。", scheduled: "削除を予約しました。このセッションはログアウト済みです。猶予期間中に再ログインすると取り消せます。", cancelled: "アカウント削除を取り消しました。", exportReady: "データコピーをダウンロードしました。", statusAria: "アカウントデータ申請の状態" },
  },
  operations: {
    operations: { eyebrow: "稼働状況", title: "基本ヘルス情報", loading: "API、ストレージ、Worker、決済、メールの状態を確認しています...", error: "現在の稼働状況を取得できません。", checked: "最終確認", technicalDetails: "技術情報", servicesAria: "ランタイムサービスの状態" },
    support: { eyebrow: "サポート", title: "サイト内サポートフォーム", body: "各リンクはカテゴリを選択した状態でサポートフォームを開きます。送信内容は API に記録され、確認メールが自動送信されます。", openForm: "フォームを開く", publicPage: "公開サポートページ", templates: { payment: { title: "決済と注文の確認", description: "決済後にアクセス権が表示されない場合や、注文の手動確認が必要な場合に使用します。" }, activation: { title: "有効化と利用権限", description: "コード利用の失敗、権限の未反映、期限の異常に使用します。" }, job: { title: "アップロードまたは結果", description: "PDF の失敗、ジョブ停止、ダウンロード不具合、結果の手動確認に使用します。" }, privacy: { title: "プライバシーまたは削除", description: "削除、書き出し、プライバシーに関する手動対応に使用します。" } } },
    statuses: { ok: "正常", warning: "注意", error: "エラー", disabled: "無効" }, serviceLabels: { api: "アプリケーション API", database: "データベース", storage: "ファイルストレージ", worker: "認識 Worker", payment: "決済設定", email: "メール通知", unknown: "システムサービス" }, serviceMessages: { ok: "正常に稼働しています。", warning: "利用できますが、設定または稼働状況の確認が必要です。", error: "利用できません。後でもう一度試すか、サポートに連絡してください。", disabled: "現在無効です。" },
  },
  jobs: {
    signInFirst: "先にログインしてください。", uploadFirst: "先に PDF をアップロードしてください。", downloadFailed: "ダウンロードに失敗しました。", createdJob: "ジョブ {id} を作成しました。", summary: { queued: ["待機中", "Worker の処理待ちです。"], processing: ["処理中", "プレビューと出力一式を生成しています。"], completed: ["完了", "最終 PDF またはドラフト一式をダウンロードできます。"] },
    create: { eyebrow: "変換ジョブを作成", title: "五線譜から簡譜への変換を登録", body: "アップロード済みのソースを選び、方向を固定したまま PDF をキューに送ります。", input: "入力ファイル", inputPlaceholder: "アップロード済み PDF を選択", direction: "方向", lockedDirection: "五線譜 PDF から簡譜", draftTitle: "ドラフト対応パイプライン", draftBody: "信頼度が低いページは早期に最終版へ昇格せず、ドラフトとして保持できます。", source: "選択中のソース", noSource: "ソース未選択", uploadHint: "選択肢がない場合は先に PDF をアップロードしてください。", createButton: "ジョブを作成", creating: "作成中...", refresh: "キューを更新", uploads: "アップロードを開く", recentSources: "最近のソース", emptySources: "PDF がありません。先にアップロードしてから変換を登録してください。", useThis: "このファイルを使う" },
    monitor: { eyebrow: "キュー監視", title: "ライブ変換パネル", auto: "自動更新中", loading: "ジョブを読み込んでいます...", empty: "ジョブはまだありません。左側で PDF を選び、最初のジョブを作成してください。", latest: "最新ジョブ", created: "作成", resultCenter: "結果センター", final: "この処理は最終結果に分類されています。", draft: "この処理はドラフト結果として保持されています。", none: "この処理にはまだダウンロード可能な結果がありません。", previewWaiting: "Worker が出力すると、ここにプレビューテキストが表示されます。", primary: "主出力", primaryTitle: "最終 PDF", primaryBody: "問題なく最終版へ昇格すると利用できます。", fallback: "代替出力", fallbackTitle: "ドラフト一式", fallbackBody: "ブラウザー外で手動修正が必要な場合に利用できます。", downloadPdf: "結果 PDF をダウンロード", downloadDraft: "ドラフト一式をダウンロード", notReady: "準備中", liveAria: "ライブ変換キュー" },
    archive: { eyebrow: "最近のジョブ", title: "キュー履歴", body: "過去の処理を確認できるよう、プレビュー、結果種別、ダウンロードを保持します。" }, statuses: { queued: "待機中", processing: "処理中", completed: "完了", failed: "失敗" }, resultKinds: { none: "なし", final: "最終版", draft: "ドラフト" }, directions: { staff_pdf_to_numbered: "五線譜 PDF → 簡譜" }, phases: { completed: "完了", running: "実行中", waiting: "待機中" },
  },
  uploads: {
    signInFirst: "先にログインしてください。", chooseFile: "PDF ファイルを選択してください。", uploadFailed: "アップロードに失敗しました。", downloadFailed: "ダウンロードに失敗しました。", uploaded: "{name} をアップロードしました。", previewAwaiting: "PDF のアップロード待ち", metrics: { stored: ["保存済み楽譜", "アップロードごとに再利用可能な変換ソースが作成されます。"], format: ["対応形式", "現在の本番環境では五線譜 PDF のみ受け付けます。"], storage: ["合計ストレージ", "ジョブ作成前に一括アップロード量を確認できます。"] },
    upload: { eyebrow: "楽譜をアップロード", title: "五線譜をスタジオに追加", body: "アップロード領域とプレビューで再利用可能なソースを追加します。", dropTitle: "楽譜をここにドロップするか、ファイルを選択", dropBody: "現在は五線譜 PDF のみ対応しています。画像と逆方向変換は対象外です。", maxSize: "最大サイズは API 制限に従います", cloud: "クラウドから読み込む", planned: "計画中", selected: "選択済み。アップロードできます。", empty: "ファイルが選択されていません。再利用可能なソースとして PDF を 1 件選んでください。", uploadButton: "PDF をアップロード", uploading: "アップロード中...", clear: "選択を解除", jobs: "ジョブへ", inputAria: "五線譜 PDF を選択" },
    preview: { eyebrow: "リアルタイムプレビュー", title: "現在のアップロード", ready: "キュー登録準備完了", numbered: "簡譜プレビュー", previewBody: "明瞭な PDF は最終出力へ昇格できます。不鮮明な素材はドラフトとして提供されます。", latest: "最新の保存済みソース", latestEmpty: "保存済みソースなし", latestHint: "PDF を 1 件アップロードするとジョブキューを利用できます。", next: "次の手順", nextTitle: "変換ジョブを作成", nextBody: "PDF 保存後も、キューの方向は五線譜 PDF → 簡譜に固定されます。", openQueue: "ジョブキューを開く", downloadSource: "ソースをダウンロード" },
    stored: { eyebrow: "保存済みファイル", title: "アップロード済み五線譜 PDF", body: "これらのファイルはジョブ入力に使用できます。ダウンロードすると API に保存されたソースを確認できます。", loading: "ファイルを読み込んでいます...", empty: "ファイルがありません。ジョブを作成するには五線譜 PDF をアップロードしてください。", download: "ダウンロード" }, fileKinds: { input_pdf: "入力 PDF", unknown: "ファイル" },
  },
} satisfies WorkspaceMessages;
