import type { WorkspaceMessages } from "../types";
import { enWorkspaceMessages } from "./en";

export const koWorkspaceMessages = {
  ...enWorkspaceMessages,
  pages: { dashboard: { eyebrow: "대시보드", title: "계정 및 이용 권한 개요", body: "로그인 상태, 이용 기간, 오선보 PDF → 숫자보 워크플로의 다음 단계를 확인하세요.", note: "활성화, 업로드, 대기열 작업을 하나의 악보 작업 공간에서 관리합니다." }, jobs: { eyebrow: "변환 작업 공간", title: "변환 작업 및 결과 검토", body: "오선보 PDF → 숫자보 작업을 등록하고 상태와 미리보기를 확인한 뒤 최종 PDF 또는 초안 묶음을 다운로드하세요." } },
  banner: { payNow: "지금 결제", activationOptions: "활성화 방법 보기", accountSetup: "계정 설정 보기", importScore: "PDF 또는 이미지 가져오기", openJobs: "작업 열기" },
  dashboard: {
    signInFirst: "대시보드를 보려면 로그인하세요.", loadingEyebrow: "프로필 불러오는 중", loadingTitle: "계정 정보를 불러오는 중...", accessEyebrow: "로그인 필요", accessTitle: "이 작업 공간에는 유효한 로그인이 필요합니다.", signIn: "로그인", createAccount: "계정 만들기", lookupEyebrow: "계정 조회", lookupTitle: "계정을 찾을 수 없습니다.",
    metrics: { email: "계정 이메일", emailBody: "로그인되었습니다. 업로드하거나 작업을 만들 수 있습니다.", freeEmailBody: "로그인되었습니다. 완전한 PDF 또는 악보 이미지로 평생 무료 프로젝트 하나를 만들 수 있습니다.", entitlement: "이용 권한", entitlementBody: "1년 이용 권한은 활성화 코드로 관리됩니다.", route: "악보 스튜디오", routeValue: "스캔, 편집, 변환, 조옮김", routeBody: "MusicXML과 Score JSON을 기반으로 기보, 재생, 연습, 다중 형식 내보내기를 제공합니다.", freeRouteValue: "완전한 무료 프로젝트 1개", freeRouteBody: "무료 프로젝트에는 현재 프로젝트 기능과 매월 25 크레딧이 포함됩니다. 더 필요하면 업그레이드하세요." },
    statuses: { active: "활성", expired: "만료됨", inactive: "비활성" }, profile: { eyebrow: "프로필", title: "계정 개요", email: "이메일", created: "생성일" }, entitlement: { eyebrow: "이용 권한", title: "이용 기간", starts: "시작", ends: "종료", inactive: "아직 활성화되지 않음", missing: "이용 권한 없음" },
    workflow: { eyebrow: "워크플로", title: "다음 단계", step1Title: "1. 악보 가져오기 또는 만들기", step1Body: "PDF, 이미지, MusicXML, MIDI, 숫자보 또는 오디오에서 구조화 악보 워크플로를 시작하세요.", step1FreeBody: "완전한 다중 페이지 PDF 또는 악보 이미지를 업로드해 수정 가능한 인식 후보를 만드세요.", step2Title: "2. 교정, 편집 및 연습", step2Body: "하나의 개정 이력에서 OMR 교정, 그래픽 편집, 조옮김, 재생, 파트 연습을 수행하세요.", step2FreeBody: "내 악보에서 후보를 교정한 뒤 재생, 조옮김, 숫자보, 버전, 공유, 내보내기를 계속하세요.", step3Title: "3. 전달용 버전 내보내기", step3Body: "승인된 개정을 MusicXML, MIDI, PDF, 이미지 또는 고품질 오디오로 렌더링하세요.", step3FreeBody: "더 많은 악보나 월간 작업 용량이 필요할 때 Starter, Converter Pro 또는 기존 활성화 코드를 사용하세요." },
    actions: { eyebrow: "작업", title: "스튜디오 관리", checkout: "온라인 결제", uploads: "업로드 열기", freeEditing: "무료 편집 열기", jobs: "작업 열기", redeem: "다른 코드 등록", supportAdmin: "지원 관리자 열기", signOut: "로그아웃" },
    privacy: { eyebrow: "개인정보 및 데이터", title: "데이터 사본과 계정 수명 주기 관리", body: "내보내기에는 비밀번호, 세션 토큰, 재설정 토큰, 공유 비밀키가 포함되지 않습니다. 계정 삭제에는 14일의 유예 기간이 있으며 이후 악보, 수업 데이터, 파일을 삭제하고 보관 의무가 있는 결제 감사 기록을 비식별화합니다.", export: "내 데이터 다운로드", exporting: "데이터 내보내는 중...", exportFailed: "데이터 내보내기에 실패했습니다.", password: "현재 비밀번호", confirmation: "확인을 위해 DELETE 입력", schedule: "계정 삭제 요청", scheduling: "삭제 예약 중...", pending: "계정 삭제 유예 기간입니다", pendingBody: "예정 삭제일", cancel: "계정 삭제 취소", cancelling: "취소 중...", required: "현재 비밀번호와 DELETE를 정확히 입력하세요.", scheduled: "삭제가 예약되었습니다. 현재 세션은 로그아웃되었으며 유예 기간에 다시 로그인하여 취소할 수 있습니다.", cancelled: "계정 삭제가 취소되었습니다.", exportReady: "데이터 사본을 다운로드했습니다.", statusAria: "계정 데이터 요청 상태" },
  },
  operations: {
    operations: { eyebrow: "운영 상태", title: "기본 상태 정보", loading: "API, 저장소, Worker, 결제, 이메일 상태를 확인하는 중...", error: "현재 런타임 상태를 불러올 수 없습니다.", checked: "마지막 확인", technicalDetails: "기술 세부 정보", servicesAria: "런타임 서비스 상태" },
    support: { eyebrow: "지원", title: "사이트 내 지원 양식", body: "각 링크는 분류가 선택된 지원 양식을 엽니다. 제출 내용은 API에 기록되고 확인 이메일이 자동 전송됩니다.", openForm: "양식 열기", publicPage: "공개 지원 페이지", templates: { payment: { title: "결제 및 주문 검토", description: "결제 후 권한이 표시되지 않거나 수동 주문 검토가 필요할 때 사용하세요." }, activation: { title: "활성화 및 권한 문제", description: "코드 등록 실패, 권한 미적용, 기간 오류에 사용하세요." }, job: { title: "업로드 또는 결과 문제", description: "PDF 실패, 작업 정지, 다운로드 오류 또는 결과 수동 검토에 사용하세요." }, privacy: { title: "개인정보 또는 삭제 요청", description: "삭제, 내보내기 또는 개인정보 관련 수동 처리에 사용하세요." } } },
    statuses: { ok: "정상", warning: "주의", error: "오류", disabled: "비활성" }, serviceLabels: { api: "애플리케이션 API", database: "데이터베이스", storage: "파일 저장소", worker: "인식 Worker", payment: "결제 설정", email: "이메일 알림", unknown: "시스템 서비스" }, serviceMessages: { ok: "정상 작동 중입니다.", warning: "사용 가능하지만 설정 또는 실행 상태를 확인해야 합니다.", error: "사용할 수 없습니다. 나중에 다시 시도하거나 지원팀에 문의하세요.", disabled: "현재 비활성화되어 있습니다." },
  },
  jobs: {
    signInFirst: "먼저 로그인하세요.", uploadFirst: "먼저 PDF를 업로드하세요.", downloadFailed: "다운로드에 실패했습니다.", createdJob: "작업 {id}을(를) 만들었습니다.", summary: { queued: ["대기 중", "Worker가 가져가기를 기다리는 중입니다."], processing: ["처리 중", "미리보기와 출력 묶음을 만드는 중입니다."], completed: ["완료", "최종 PDF 또는 초안 묶음을 다운로드할 수 있습니다."] },
    create: { eyebrow: "변환 작업 만들기", title: "오선보-숫자보 변환 등록", body: "업로드한 원본을 선택하고 방향을 고정한 채 PDF를 대기열에 추가하세요.", input: "입력 파일", inputPlaceholder: "업로드한 PDF 선택", direction: "방향", lockedDirection: "오선보 PDF를 숫자보로", draftTitle: "초안 인식 파이프라인", draftBody: "신뢰도가 낮은 페이지는 너무 일찍 최종본으로 승격하지 않고 초안으로 유지할 수 있습니다.", source: "선택한 원본", noSource: "선택한 원본 없음", uploadHint: "목록이 비어 있으면 먼저 원본 PDF를 업로드하세요.", createButton: "작업 만들기", creating: "만드는 중...", refresh: "대기열 새로고침", uploads: "업로드 열기", recentSources: "최근 원본", emptySources: "업로드한 PDF가 없습니다. 먼저 업로드한 후 변환을 등록하세요.", useThis: "이 파일 사용" },
    monitor: { eyebrow: "대기열 모니터", title: "실시간 변환 패널", auto: "자동 새로고침 중", loading: "작업 불러오는 중...", empty: "아직 작업이 없습니다. 왼쪽에서 PDF를 골라 첫 작업을 만드세요.", latest: "최신 작업", created: "생성", resultCenter: "결과 센터", final: "이 실행은 현재 최종 결과로 분류됩니다.", draft: "이 실행은 현재 초안 결과로 유지됩니다.", none: "아직 다운로드 가능한 결과가 없습니다.", previewWaiting: "Worker가 출력하면 여기에 미리보기 텍스트가 나타납니다.", primary: "주 출력", primaryTitle: "최종 PDF", primaryBody: "실행이 최종본으로 정상 승격되면 사용할 수 있습니다.", fallback: "대체 출력", fallbackTitle: "초안 묶음", fallbackBody: "브라우저 밖에서 수동 교정이 필요할 때 사용할 수 있습니다.", downloadPdf: "결과 PDF 다운로드", downloadDraft: "초안 묶음 다운로드", notReady: "준비되지 않음", liveAria: "실시간 변환 대기열" },
    archive: { eyebrow: "최근 작업", title: "작업 기록", body: "이전 실행을 검토할 수 있도록 미리보기, 결과 유형, 다운로드를 유지합니다." }, statuses: { queued: "대기 중", processing: "처리 중", completed: "완료", failed: "실패" }, resultKinds: { none: "없음", final: "최종본", draft: "초안" }, directions: { staff_pdf_to_numbered: "오선보 PDF → 숫자보" }, phases: { completed: "완료", running: "실행 중", waiting: "대기 중" },
  },
  uploads: {
    signInFirst: "먼저 로그인하세요.", chooseFile: "PDF 파일을 선택하세요.", uploadFailed: "업로드에 실패했습니다.", downloadFailed: "다운로드에 실패했습니다.", uploaded: "{name}을(를) 업로드했습니다.", previewAwaiting: "PDF 업로드 대기 중", metrics: { stored: ["저장된 악보", "각 업로드는 이후 변환 작업에 재사용할 수 있는 원본이 됩니다."], format: ["지원 형식", "현재 운영 환경은 오선보 PDF만 받습니다."], storage: ["전체 저장 용량", "작업 생성 전 일괄 업로드 용량을 확인할 수 있습니다."] },
    upload: { eyebrow: "악보 업로드", title: "오선보를 스튜디오에 추가", body: "업로드 영역과 미리보기에서 재사용 가능한 원본 파일을 추가하세요.", dropTitle: "악보를 놓거나 파일 선택", dropBody: "현재 오선보 PDF만 지원합니다. 이미지 업로드와 역변환은 지원 범위 밖입니다.", maxSize: "최대 크기는 API 제한을 따릅니다", cloud: "클라우드에서 가져오기", planned: "예정", selected: "선택되어 업로드할 수 있습니다.", empty: "파일을 선택하지 않았습니다. 재사용할 PDF 하나를 선택하세요.", uploadButton: "PDF 업로드", uploading: "업로드 중...", clear: "선택 지우기", jobs: "작업으로 이동", inputAria: "오선보 PDF 선택" },
    preview: { eyebrow: "실시간 미리보기", title: "현재 업로드", ready: "대기열 등록 준비", numbered: "숫자보 미리보기", previewBody: "선명한 PDF는 최종 출력으로 승격될 수 있습니다. 품질이 낮은 자료는 초안으로 제공됩니다.", latest: "최근 저장 원본", latestEmpty: "저장된 원본 없음", latestHint: "PDF 하나를 업로드하면 작업 대기열을 사용할 수 있습니다.", next: "다음 단계", nextTitle: "변환 작업 만들기", nextBody: "PDF 저장 후 대기열 방향은 오선보 PDF → 숫자보로 고정됩니다.", openQueue: "작업 대기열 열기", downloadSource: "원본 다운로드" },
    stored: { eyebrow: "저장된 파일", title: "업로드한 오선보 PDF", body: "이 파일은 작업 입력으로 사용할 수 있습니다. 다운로드하면 API에 저장된 원본을 확인할 수 있습니다.", loading: "파일 불러오는 중...", empty: "업로드한 파일이 없습니다. 작업을 만들려면 오선보 PDF를 먼저 업로드하세요.", download: "다운로드" }, fileKinds: { input_pdf: "입력 PDF", unknown: "파일" },
  },
} satisfies WorkspaceMessages;
