import type { EducationMessages } from "../types";

export const deEducationMessages = {
  pages: {
    classrooms: { metadataTitle: "Zusammenarbeit für Klassen und Schulen", metadataDescription: "Klassen, Listen, Ressourcen, Mitteilungen und Unterrichtszusammenarbeit verwalten.", eyebrow: "Klasse / Schule Beta", title: "Klasse / Schule Beta", body: "Klassen, Schülerlisten, Ressourcen, Mitteilungen und Unterrichtszusammenarbeit an einem Ort verwalten." },
    student: { metadataTitle: "Meine Klassen", metadataDescription: "Notenaufgaben, Lernmaterialien, Mitteilungen, Bewertungen und Feedback ansehen." },
  },
  shared: {
    roles: { owner: "Eigentümer", admin: "Administrator", teacher: "Lehrkraft", assistant: "Assistenz", observer: "Beobachter", student: "Schüler", guardian: "Erziehungsberechtigter" },
    statuses: { invited: "Eingeladen", active: "Aktiv", archived: "Archiviert", removed: "Entfernt", pending: "Ausstehend", published: "Veröffentlicht", scheduled: "Geplant", cancelled: "Abgebrochen", draft: "Entwurf", verified: "Verifiziert" },
    resourceTypes: { score: "Partitur", audio: "Audio", video: "Video", document: "Dokument" }, resourceSources: { external: "Link", file: "Hochgeladene Datei" }, resourceVisibilities: { classroom: "Ganze Klasse", selected: "Ausgewählte Schüler", staff: "Nur Team" },
  },
  classrooms: {
    eyebrow: "Unterricht", title: "Klassenverwaltung", body: "Klassen und Schülerlisten für Lehrkräfte, Chöre und Musikschulen verwalten. Aufgaben können Klassen zugeordnet und Abgaben pro Schüler organisiert werden.", createTitle: "Klasse erstellen", name: "Klassenname", description: "Beschreibung", create: "Klasse erstellen", creating: "Wird erstellt ...", empty: "Noch keine Klassen.", students: "Schüler", addStudent: "Schüler hinzufügen", displayName: "Name des Schülers", contactEmail: "Kontakt-E-Mail", externalRef: "Schüler-ID / Notiz", removeStudent: "Entfernen", archiveClassroom: "Klasse archivieren", loading: "Klassen werden geladen ...", created: "Klasse erstellt.", studentAdded: "Schüler hinzugefügt.", bulkRoster: "Sammelliste", bulkHint: "Name, E-Mail und Schüler-ID/Notiz tabulatorgetrennt aus einer Tabelle einfügen.", importRoster: "Liste importieren", rosterImported: "Liste importiert.", guardian: "Erziehungsberechtigter", guardianName: "Name des Erziehungsberechtigten", guardianEmail: "Anmelde-E-Mail des Erziehungsberechtigten", relationship: "Beziehung, z. B. Mutter", inviteGuardian: "Erziehungsberechtigten einladen", guardianInvited: "Erziehungsberechtigter eingeladen.", archived: "Archiviert.", statusAria: "Status der Klassenaktion", loadingAria: "Ladestatus der Klassen", rosterAria: "Klassenlisten",
  },
  organization: {
    eyebrow: "Organisationszugriff", title: "Organisationen, Standorte und Klassenteams", body: "Administratoren verwalten Standorte und Mitglieder. Lehrkräfte und Assistenzen betreiben Klassen; Beobachter haben nur Lesezugriff. E-Mail-Einladungen werden bei der Anmeldung serverseitig zugeordnet.", createOrganization: "Organisation erstellen", organizationName: "Organisationsname", addCampus: "Standort hinzufügen", selectOrganization: "Organisation auswählen", campusName: "Standortname", campusCode: "Standortcode", saveCampus: "Standort speichern", inviteOrganizationMember: "Organisationsmitglied einladen", displayName: "Anzeigename", signInEmail: "Anmelde-E-Mail", inviteMember: "Mitglied einladen", campuses: "Standorte", remove: "Entfernen", classroomPlacement: "Klassenzuordnung", selectClassroom: "Klasse auswählen", personalClassroom: "Persönliche Klasse", noCampus: "Kein Standort", savePlacement: "Zuordnung speichern", assignClassroomStaff: "Klassenteam zuweisen", assignStaff: "Team zuweisen", classroomStaff: "Klassenteam", noStaff: "Niemand zugewiesen.", accessUpdated: "Unterrichtszugriff aktualisiert.", placementUpdated: "Klassenzuordnung aktualisiert.", memberRemoved: "Mitglied entfernt.", statusAria: "Status der Organisationsaktion", organizationSelectAria: "Organisation", classroomSelectAria: "Klasse", memberRoleAria: "Rolle des Organisationsmitglieds", staffRoleAria: "Rolle im Klassenteam",
  },
  operations: {
    eyebrow: "Klassenbetrieb", title: "Mitteilungen, Ressourcen und LMS", body: "Schülerkonten werden über die E-Mail der Liste verknüpft. Versionierte Ressourcen, geplante Mitteilungen und Lesebestätigungen werden hier verwaltet.", classroom: "Klasse", currentClassroomAria: "Aktuelle Klasse", selectClassroom: "Klasse auswählen", statusAria: "Status der Unterrichtsaktion", saved: "In der Klasse gespeichert.", archived: "Archiviert.", retriedEmails: "{count} fehlgeschlagene E-Mails erneut eingereiht.", rosterSynced: "{imported} Lernende synchronisiert; {skipped} andere Einträge übersprungen.", retentionSaved: "Aufbewahrungsrichtlinie gespeichert.", retentionPurged: "Dateiinhalte aus {count} abgelaufenen historischen Versionen entfernt.", fileUploaded: "Datei sicher in die Klasse hochgeladen.", versionRestored: "v{from} als neue v{to} wiederhergestellt.", folderCreated: "Ordner erstellt.", resourceReused: "Ressource in dieser Klasse wiederverwendet.", folderUpdated: "Ordner aktualisiert; {count} Ressourcenversionen erstellt.", resourceMoved: "Ressource als unveränderliche v{version} verschoben.",
    resource: { add: "Ressource hinzufügen", publishVersion: "Neue Ressourcenversion veröffentlichen", sourceAria: "Ressourcenquelle", title: "Ressourcentitel", file: "Ressourcendatei", typeAria: "Ressourcentyp", visibilityAria: "Sichtbarkeit der Ressource", studentsWithAccess: "Berechtigte Schüler", noActiveStudents: "Diese Klasse hat keine aktiven Schüler für eine Berechtigung.", folderAria: "Ressourcenordner", rootFolder: "Stammordner", tags: "Kommagetrennte Schlagwörter", upload: "Ressource hochladen", save: "Ressource speichern", cancel: "Abbrechen", version: "v{version}", selectedStudents: "{count} ausgewählte Schüler", history: "Verlauf", newVersion: "Neue Version", archive: "Archivieren", moveAria: "{title} verschieben", move: "Verschieben" },
    notification: { publish: "Mitteilung veröffentlichen", title: "Titel der Mitteilung", body: "Inhalt der Mitteilung", scheduleLabel: "Planung (leer bedeutet sofort)", schedule: "Planen", publishNow: "Jetzt veröffentlichen", history: "Mitteilungsverlauf", empty: "Noch keine Mitteilungen.", read: "Gelesen", email: "E-Mail", sent: "gesendet", pending: "ausstehend", failed: "fehlgeschlagen", retryFailed: "Fehlgeschlagene E-Mails erneut senden", cancel: "Abbrechen" },
    retention: { title: "Versionsaufbewahrung", enable: "Automatische Bereinigung aktivieren", days: "Aufbewahrungstage historischer Versionen", minimumVersions: "Mindestanzahl historischer Versionen pro Gruppe", note: "Aktuelle und manuell gehaltene Versionen werden nie bereinigt. Die Datei wird entfernt, der Verlauf bleibt erhalten.", previewSummary: "{count} Versionen mit etwa {size} sind berechtigt.", save: "Richtlinie speichern", preview: "Vorschau", purge: "Berechtigte bereinigen" },
    lms: { title: "LTI-1.3-Verbindung", courseRef: "Kursreferenz", baseUrl: "LMS-URL (optional)", issuer: "Aussteller (https://...)", clientId: "Client-ID", deploymentId: "Bereitstellungs-ID", oidcAuthUrl: "OIDC-Autorisierungs-URL", tokenUrl: "OAuth-Token-URL", jwksUrl: "Plattform-JWKS-URL", note: "Nach dem Speichern das Tool einmal vom LMS aus starten. Die Verbindung wird erst nach erfolgreicher Prüfung von Signatur, Nonce, Bereitstellung und Ziellink aktiviert.", saveDraft: "Entwurf speichern", deploymentMissing: "Bereitstellungs-ID nicht konfiguriert", rosterSynced: "Liste synchronisiert", syncRoster: "Liste synchronisieren", section: "LMS / LTI", providers: { manual: "Manuell / LTI", canvas: "Canvas", moodle: "Moodle", "google-classroom": "Google Classroom" } },
    library: { eyebrow: "Ressourcenbibliothek", resourceCount: "{count} Ressourcen", search: "Titel, Ordner oder Schlagwort suchen", noMatches: "Keine passenden Ressourcen.", newFolder: "Neuer Ordnername", parentFolderAria: "Übergeordneter Ordner", underRoot: "Unter Stammordner", createFolder: "Ordner erstellen", sourceClassroomAria: "Quellklasse", sourceClassroom: "Quellklasse auswählen", sourceResourceAria: "Quellressource", selectResource: "Ressource auswählen", reuseFolderAria: "Zielordner", reuseRoot: "Im Stammordner wiederverwenden", reuse: "Ressource wiederverwenden", folderManagementAria: "Ordnerverwaltung", renameAria: "{path} umbenennen", parentForAria: "Übergeordneter Ordner für {path}", save: "Speichern", cancel: "Abbrechen", edit: "Bearbeiten", archiveEmptyFolder: "Leeren Ordner archivieren", root: "Stammordner" },
    history: { aria: "Versionsverlauf von {title}", note: "Der Verlauf ist schreibgeschützt. Eine Wiederherstellung erstellt eine neue aktuelle Version.", contentExpired: "Inhalt abgelaufen", historical: "Historisch", current: "Aktuell", held: "Gehalten", restoredFromHistory: "Aus Verlauf wiederhergestellt", download: "Herunterladen", open: "Öffnen", removeHold: "Halten aufheben", keep: "Behalten", restore: "Wiederherstellen" },
  },
  student: {
    eyebrow: "Lernbereich", title: "Meine Klassen", body: "Zugewiesene Partituren, Lernmaterialien, Mitteilungen, Bewertungen und Feedback an einem Ort ansehen.", loading: "Klasseninhalte werden geladen ...", login: "Melde dich an, um Klassen zu deiner Konto-E-Mail zu sehen.", empty: "Noch keine Klasse verknüpft. Bitte die Lehrkraft, deine Anmelde-E-Mail zur Liste hinzuzufügen.", assignments: "Notenaufgaben", resources: "Lernmaterialien", notifications: "Klassenmitteilungen", unread: "ungelesen", due: "Fällig", noDue: "Kein Fälligkeitsdatum", score: "Partitur", openScore: "Partitur öffnen", noShare: "Die Partitur wurde noch nicht freigegeben", submissionStatuses: { pending: "Nicht eingereicht", submitted: "Eingereicht", reviewed: "Bewertet" }, feedback: "Feedback der Lehrkraft", grade: "Bewertung", noAssignments: "Noch keine Aufgaben.", noResources: "Noch keine Lernmaterialien.", noNotifications: "Noch keine Mitteilungen.", markRead: "Als gelesen markieren", read: "Gelesen", guardianView: "Ansicht des Erziehungsberechtigten", studentView: "Schüleransicht", exitClass: "Klasse verlassen", exitReason: "Grund (optional)", requestExit: "Austritt beantragen", awaitingGuardian: "Zustimmung ausstehend", cancelExit: "Antrag zurückziehen", approveExit: "Austritt genehmigen", rejectExit: "Austritt ablehnen", exitRejected: "Der vorherige Antrag wurde abgelehnt. Ein neuer Antrag kann gestellt werden.", preferences: "Benachrichtigungseinstellungen", emailAnnouncements: "Klassenmitteilungen per E-Mail erhalten", emailHint: "Standardmäßig aus. Nach Aktivierung werden neue Mitteilungen an deine Anmelde-E-Mail gesendet.", summaryAria: "Zusammenfassung der Klassen und ungelesenen Mitteilungen", loadingAria: "Ladestatus der Schülerklassen", preferencesAria: "Benachrichtigungseinstellungen",
  },
} satisfies EducationMessages;
