import type { EducationMessages } from "../types";

export const esEducationMessages = {
  pages: {
    classrooms: { metadataTitle: "Colaboración de clases y centros", metadataDescription: "Gestiona clases, listas, recursos, avisos y colaboración educativa.", eyebrow: "Clase / Centro beta", title: "Clase / Centro beta", body: "Gestiona clases, listas de alumnos, recursos, avisos y colaboración educativa en un solo lugar." },
    student: { metadataTitle: "Mis clases", metadataDescription: "Consulta tareas de partituras, recursos, avisos, calificaciones y comentarios del profesor." },
  },
  shared: {
    roles: { owner: "Propietario", admin: "Administrador", teacher: "Profesor", assistant: "Asistente", observer: "Observador", student: "Alumno", guardian: "Tutor" },
    statuses: { invited: "Invitado", active: "Activo", archived: "Archivado", removed: "Eliminado", pending: "Pendiente", published: "Publicado", scheduled: "Programado", cancelled: "Cancelado", draft: "Borrador", verified: "Verificado" },
    resourceTypes: { score: "Partitura", audio: "Audio", video: "Vídeo", document: "Documento" }, resourceSources: { external: "Enlace", file: "Archivo subido" }, resourceVisibilities: { classroom: "Toda la clase", selected: "Alumnos seleccionados", staff: "Solo personal" },
  },
  classrooms: {
    eyebrow: "Enseñanza", title: "Gestión de clases", body: "Gestiona clases y listas de alumnos para profesores, coros y academias. Las tareas pueden vincularse a las clases y los envíos se organizan por alumno.", createTitle: "Crear clase", name: "Nombre de la clase", description: "Descripción", create: "Crear clase", creating: "Creando...", empty: "Todavía no hay clases.", students: "Alumnos", addStudent: "Añadir alumno", displayName: "Nombre del alumno", contactEmail: "Correo de contacto", externalRef: "ID del alumno / nota", removeStudent: "Quitar", archiveClassroom: "Archivar clase", loading: "Cargando clases...", created: "Clase creada.", studentAdded: "Alumno añadido.", bulkRoster: "Lista en bloque", bulkHint: "Pega desde una hoja el nombre, correo e ID/nota en columnas separadas por tabuladores.", importRoster: "Importar lista", rosterImported: "Lista importada.", guardian: "Tutor", guardianName: "Nombre del tutor", guardianEmail: "Correo de acceso del tutor", relationship: "Relación, p. ej., madre", inviteGuardian: "Invitar tutor", guardianInvited: "Tutor invitado.", archived: "Archivado.", statusAria: "Estado de la operación de clase", loadingAria: "Estado de carga de clases", rosterAria: "Listas de clases",
  },
  organization: {
    eyebrow: "Acceso de organización", title: "Organizaciones, sedes y personal de clase", body: "Los administradores gestionan sedes y miembros. Profesores y asistentes operan las clases; los observadores son de solo lectura. Las invitaciones por correo se vinculan en el servidor al iniciar sesión.", createOrganization: "Crear organización", organizationName: "Nombre de la organización", addCampus: "Añadir sede", selectOrganization: "Seleccionar organización", campusName: "Nombre de la sede", campusCode: "Código de la sede", saveCampus: "Guardar sede", inviteOrganizationMember: "Invitar miembro", displayName: "Nombre visible", signInEmail: "Correo de acceso", inviteMember: "Invitar miembro", campuses: "Sedes", remove: "Quitar", classroomPlacement: "Ubicación de la clase", selectClassroom: "Seleccionar clase", personalClassroom: "Clase personal", noCampus: "Sin sede", savePlacement: "Guardar ubicación", assignClassroomStaff: "Asignar personal de clase", assignStaff: "Asignar personal", classroomStaff: "Personal de clase", noStaff: "No hay personal asignado.", accessUpdated: "Acceso educativo actualizado.", placementUpdated: "Ubicación de la clase actualizada.", memberRemoved: "Miembro eliminado.", statusAria: "Estado de acceso de organización", organizationSelectAria: "Organización", classroomSelectAria: "Clase", memberRoleAria: "Rol del miembro", staffRoleAria: "Rol del personal de clase",
  },
  operations: {
    eyebrow: "Operaciones de clase", title: "Avisos, recursos y LMS", body: "Las cuentas se vinculan mediante el correo de la lista. Gestiona recursos con versiones, avisos programados y confirmaciones de lectura.", classroom: "Clase", currentClassroomAria: "Clase actual", selectClassroom: "Seleccionar clase", statusAria: "Estado de la operación educativa", saved: "Guardado en la clase.", archived: "Archivado.", retriedEmails: "Se volvieron a poner en cola {count} correos fallidos.", rosterSynced: "{imported} alumnos sincronizados; {skipped} registros no estudiantiles omitidos.", retentionSaved: "Política de conservación de versiones guardada.", retentionPurged: "Contenido eliminado de {count} versiones históricas caducadas.", fileUploaded: "Archivo subido de forma segura a la clase.", versionRestored: "v{from} restaurada como nueva v{to}.", folderCreated: "Carpeta creada.", resourceReused: "Recurso reutilizado en esta clase.", folderUpdated: "Carpeta actualizada; se crearon {count} versiones de recursos.", resourceMoved: "Recurso movido como v{version} inmutable.",
    resource: { add: "Añadir recurso", publishVersion: "Publicar nueva versión", sourceAria: "Origen del recurso", title: "Título del recurso", file: "Archivo del recurso", typeAria: "Tipo de recurso", visibilityAria: "Visibilidad del recurso", studentsWithAccess: "Alumnos con acceso", noActiveStudents: "Esta clase no tiene alumnos activos a los que autorizar.", folderAria: "Carpeta del recurso", rootFolder: "Carpeta raíz", tags: "Etiquetas separadas por comas", upload: "Subir recurso", save: "Guardar recurso", cancel: "Cancelar", version: "v{version}", selectedStudents: "{count} alumnos seleccionados", history: "Historial", newVersion: "Nueva versión", archive: "Archivar", moveAria: "Mover {title}", move: "Mover" },
    notification: { publish: "Publicar aviso", title: "Título del aviso", body: "Contenido del aviso", scheduleLabel: "Programar (en blanco publica ahora)", schedule: "Programar", publishNow: "Publicar ahora", history: "Historial de avisos", empty: "Todavía no hay avisos.", read: "Leído", email: "Correo", sent: "enviados", pending: "pendientes", failed: "fallidos", retryFailed: "Reintentar correos fallidos", cancel: "Cancelar" },
    retention: { title: "Conservación de versiones", enable: "Activar limpieza automática", days: "Días de conservación del historial", minimumVersions: "Mínimo de versiones históricas por grupo", note: "Las versiones actuales y retenidas manualmente nunca se purgan. La limpieza elimina el archivo pero conserva el historial.", previewSummary: "{count} versiones, unos {size}, son aptas.", save: "Guardar política", preview: "Vista previa", purge: "Purgar aptas" },
    lms: { title: "Conexión LTI 1.3", courseRef: "Referencia del curso", baseUrl: "URL del LMS (opcional)", issuer: "Emisor (https://...)", clientId: "ID de cliente", deploymentId: "ID de despliegue", oidcAuthUrl: "URL de autorización OIDC", tokenUrl: "URL del token OAuth", jwksUrl: "URL JWKS de la plataforma", note: "Tras guardar, inicia la herramienta una vez desde el LMS. La conexión solo se activa al verificar firma, nonce, despliegue y enlace de destino.", saveDraft: "Guardar borrador", deploymentMissing: "ID de despliegue sin configurar", rosterSynced: "lista sincronizada", syncRoster: "Sincronizar lista", section: "LMS / LTI", providers: { manual: "Manual / LTI", canvas: "Canvas", moodle: "Moodle", "google-classroom": "Google Classroom" } },
    library: { eyebrow: "Biblioteca de recursos", resourceCount: "{count} recursos", search: "Buscar título, carpeta o etiqueta", noMatches: "No hay recursos coincidentes.", newFolder: "Nombre de carpeta nueva", parentFolderAria: "Carpeta superior", underRoot: "Bajo la raíz", createFolder: "Crear carpeta", sourceClassroomAria: "Clase de origen", sourceClassroom: "Seleccionar clase de origen", sourceResourceAria: "Recurso de origen", selectResource: "Seleccionar recurso", reuseFolderAria: "Carpeta de destino", reuseRoot: "Reutilizar en la raíz", reuse: "Reutilizar recurso", folderManagementAria: "Gestión de carpetas", renameAria: "Cambiar nombre de {path}", parentForAria: "Carpeta superior de {path}", save: "Guardar", cancel: "Cancelar", edit: "Editar", archiveEmptyFolder: "Archivar carpeta vacía", root: "Raíz" },
    history: { aria: "Historial de versiones de {title}", note: "El historial es de solo lectura. Restaurar crea una nueva versión actual.", contentExpired: "Contenido caducado", historical: "Histórica", current: "Actual", held: "Retenida", restoredFromHistory: "Restaurada del historial", download: "Descargar", open: "Abrir", removeHold: "Quitar retención", keep: "Conservar", restore: "Restaurar" },
  },
  student: {
    eyebrow: "Centro de aprendizaje", title: "Mis clases", body: "Consulta en un solo lugar las partituras asignadas, recursos, avisos, notas y comentarios del profesor.", loading: "Cargando contenido de las clases...", login: "Inicia sesión para ver las clases vinculadas a tu correo.", empty: "Aún no hay clases vinculadas. Pide al profesor que añada tu correo de acceso a la lista.", assignments: "Tareas de partituras", resources: "Recursos de aprendizaje", notifications: "Avisos de clase", unread: "sin leer", due: "Fecha límite", noDue: "Sin fecha límite", score: "Partitura", openScore: "Abrir partitura", noShare: "La partitura aún no se ha compartido", submissionStatuses: { pending: "Sin enviar", submitted: "Enviada", reviewed: "Revisada" }, feedback: "Comentarios del profesor", grade: "Calificación", noAssignments: "Todavía no hay tareas.", noResources: "Todavía no hay recursos.", noNotifications: "Todavía no hay avisos.", markRead: "Marcar como leído", read: "Leído", guardianView: "Vista de tutor", studentView: "Vista de alumno", exitClass: "Salir de la clase", exitReason: "Motivo de salida (opcional)", requestExit: "Solicitar salida", awaitingGuardian: "Esperando consentimiento del tutor", cancelExit: "Retirar solicitud", approveExit: "Aprobar salida", rejectExit: "Rechazar salida", exitRejected: "El tutor rechazó la solicitud anterior. Se puede enviar una nueva.", preferences: "Ajustes de notificaciones", emailAnnouncements: "Recibir avisos de clase por correo", emailHint: "Desactivado por defecto. Al activarlo, los avisos nuevos se enviarán a tu correo de acceso.", summaryAria: "Resumen de clases y avisos sin leer", loadingAria: "Estado de carga de clases", preferencesAria: "Preferencias de notificaciones",
  },
} satisfies EducationMessages;
