import type { EducationMessages } from "../types";

export const frEducationMessages = {
  pages: {
    classrooms: { metadataTitle: "Collaboration de classe et d’établissement", metadataDescription: "Gérez les classes, listes, ressources, notifications et la collaboration pédagogique.", eyebrow: "Classe / Établissement bêta", title: "Classe / Établissement bêta", body: "Gérez les classes, listes d’élèves, ressources, notifications et la collaboration pédagogique au même endroit." },
    student: { metadataTitle: "Mes classes", metadataDescription: "Consultez les devoirs de partition, ressources, annonces, notes et commentaires du professeur." },
  },
  shared: {
    roles: { owner: "Propriétaire", admin: "Administrateur", teacher: "Professeur", assistant: "Assistant", observer: "Observateur", student: "Élève", guardian: "Responsable" },
    statuses: { invited: "Invité", active: "Actif", archived: "Archivé", removed: "Retiré", pending: "En attente", published: "Publié", scheduled: "Planifié", cancelled: "Annulé", draft: "Brouillon", verified: "Vérifié" },
    resourceTypes: { score: "Partition", audio: "Audio", video: "Vidéo", document: "Document" }, resourceSources: { external: "Lien", file: "Fichier importé" }, resourceVisibilities: { classroom: "Toute la classe", selected: "Élèves sélectionnés", staff: "Équipe uniquement" },
  },
  classrooms: {
    eyebrow: "Enseignement", title: "Gestion des classes", body: "Gérez les classes et listes d’élèves des professeurs, chorales et studios. Les devoirs peuvent être associés aux classes et les envois classés par élève.", createTitle: "Créer une classe", name: "Nom de la classe", description: "Description", create: "Créer la classe", creating: "Création...", empty: "Aucune classe pour le moment.", students: "Élèves", addStudent: "Ajouter un élève", displayName: "Nom de l’élève", contactEmail: "E-mail de contact", externalRef: "Identifiant élève / note", removeStudent: "Retirer", archiveClassroom: "Archiver la classe", loading: "Chargement des classes...", created: "Classe créée.", studentAdded: "Élève ajouté.", bulkRoster: "Liste en lot", bulkHint: "Collez depuis un tableur le nom, l’e-mail et l’identifiant/note, séparés par des tabulations.", importRoster: "Importer la liste", rosterImported: "Liste importée.", guardian: "Responsable", guardianName: "Nom du responsable", guardianEmail: "E-mail de connexion du responsable", relationship: "Lien, par ex. mère", inviteGuardian: "Inviter le responsable", guardianInvited: "Responsable invité.", archived: "Archivé.", statusAria: "État de l’opération sur la classe", loadingAria: "État de chargement des classes", rosterAria: "Listes des classes",
  },
  organization: {
    eyebrow: "Accès de l’organisation", title: "Organisations, sites et équipe de classe", body: "Les administrateurs gèrent les sites et membres. Professeurs et assistants gèrent les classes ; les observateurs restent en lecture seule. Les invitations par e-mail sont associées côté serveur à la connexion.", createOrganization: "Créer une organisation", organizationName: "Nom de l’organisation", addCampus: "Ajouter un site", selectOrganization: "Sélectionner une organisation", campusName: "Nom du site", campusCode: "Code du site", saveCampus: "Enregistrer le site", inviteOrganizationMember: "Inviter un membre", displayName: "Nom affiché", signInEmail: "E-mail de connexion", inviteMember: "Inviter le membre", campuses: "Sites", remove: "Retirer", classroomPlacement: "Rattachement de classe", selectClassroom: "Sélectionner une classe", personalClassroom: "Classe personnelle", noCampus: "Aucun site", savePlacement: "Enregistrer le rattachement", assignClassroomStaff: "Affecter l’équipe de classe", assignStaff: "Affecter", classroomStaff: "Équipe de classe", noStaff: "Aucune personne affectée.", accessUpdated: "Accès pédagogique mis à jour.", placementUpdated: "Rattachement de classe mis à jour.", memberRemoved: "Membre retiré.", statusAria: "État de l’opération d’accès", organizationSelectAria: "Organisation", classroomSelectAria: "Classe", memberRoleAria: "Rôle du membre", staffRoleAria: "Rôle dans la classe",
  },
  operations: {
    eyebrow: "Opérations de classe", title: "Notifications, ressources et LMS", body: "Les comptes élèves sont associés par l’e-mail de la liste. Gérez ici les ressources versionnées, annonces planifiées et accusés de lecture.", classroom: "Classe", currentClassroomAria: "Classe actuelle", selectClassroom: "Sélectionner une classe", statusAria: "État de l’opération pédagogique", saved: "Enregistré dans la classe.", archived: "Archivé.", retriedEmails: "{count} e-mails en échec remis en file d’attente.", rosterSynced: "{imported} élèves synchronisés ; {skipped} entrées non-élèves ignorées.", retentionSaved: "Politique de conservation des versions enregistrée.", retentionPurged: "Contenu supprimé de {count} versions historiques expirées.", fileUploaded: "Fichier importé en toute sécurité dans la classe.", versionRestored: "v{from} restaurée comme nouvelle v{to}.", folderCreated: "Dossier créé.", resourceReused: "Ressource réutilisée dans cette classe.", folderUpdated: "Dossier mis à jour ; {count} versions de ressources créées.", resourceMoved: "Ressource déplacée comme v{version} immuable.",
    resource: { add: "Ajouter une ressource", publishVersion: "Publier une nouvelle version", sourceAria: "Source de la ressource", title: "Titre de la ressource", file: "Fichier de ressource", typeAria: "Type de ressource", visibilityAria: "Visibilité de la ressource", studentsWithAccess: "Élèves autorisés", noActiveStudents: "Cette classe n’a aucun élève actif à autoriser.", folderAria: "Dossier de la ressource", rootFolder: "Dossier racine", tags: "Étiquettes séparées par des virgules", upload: "Importer la ressource", save: "Enregistrer la ressource", cancel: "Annuler", version: "v{version}", selectedStudents: "{count} élèves sélectionnés", history: "Historique", newVersion: "Nouvelle version", archive: "Archiver", moveAria: "Déplacer {title}", move: "Déplacer" },
    notification: { publish: "Publier une notification", title: "Titre de la notification", body: "Contenu de la notification", scheduleLabel: "Planification (vide : publier maintenant)", schedule: "Planifier", publishNow: "Publier maintenant", history: "Historique des notifications", empty: "Aucune notification pour le moment.", read: "Lu", email: "E-mail", sent: "envoyés", pending: "en attente", failed: "échoués", retryFailed: "Réessayer les e-mails en échec", cancel: "Annuler" },
    retention: { title: "Conservation des versions", enable: "Activer le nettoyage automatique", days: "Jours de conservation des anciennes versions", minimumVersions: "Minimum de versions historiques par groupe", note: "Les versions actuelles et conservées manuellement ne sont jamais purgées. Le nettoyage retire le fichier mais conserve l’historique.", previewSummary: "{count} versions, environ {size}, sont éligibles.", save: "Enregistrer la politique", preview: "Aperçu", purge: "Purger les éléments éligibles" },
    lms: { title: "Connexion LTI 1.3", courseRef: "Référence du cours", baseUrl: "URL du LMS (facultatif)", issuer: "Émetteur (https://...)", clientId: "ID client", deploymentId: "ID de déploiement", oidcAuthUrl: "URL d’autorisation OIDC", tokenUrl: "URL du jeton OAuth", jwksUrl: "URL JWKS de la plateforme", note: "Après l’enregistrement, lancez une fois l’outil depuis le LMS. La connexion n’est activée qu’après validation de la signature, du nonce, du déploiement et du lien cible.", saveDraft: "Enregistrer le brouillon", deploymentMissing: "ID de déploiement non configuré", rosterSynced: "liste synchronisée", syncRoster: "Synchroniser la liste", section: "LMS / LTI", providers: { manual: "Manuel / LTI", canvas: "Canvas", moodle: "Moodle", "google-classroom": "Google Classroom" } },
    library: { eyebrow: "Bibliothèque de ressources", resourceCount: "{count} ressources", search: "Rechercher un titre, dossier ou tag", noMatches: "Aucune ressource correspondante.", newFolder: "Nom du nouveau dossier", parentFolderAria: "Dossier parent", underRoot: "Sous la racine", createFolder: "Créer le dossier", sourceClassroomAria: "Classe source", sourceClassroom: "Sélectionner la classe source", sourceResourceAria: "Ressource source", selectResource: "Sélectionner la ressource", reuseFolderAria: "Dossier cible", reuseRoot: "Réutiliser à la racine", reuse: "Réutiliser la ressource", folderManagementAria: "Gestion des dossiers", renameAria: "Renommer {path}", parentForAria: "Parent de {path}", save: "Enregistrer", cancel: "Annuler", edit: "Modifier", archiveEmptyFolder: "Archiver le dossier vide", root: "Racine" },
    history: { aria: "Historique de {title}", note: "L’historique est en lecture seule. Une restauration crée une nouvelle version actuelle.", contentExpired: "Contenu expiré", historical: "Historique", current: "Actuelle", held: "Conservée", restoredFromHistory: "Restaurée depuis l’historique", download: "Télécharger", open: "Ouvrir", removeHold: "Retirer la conservation", keep: "Conserver", restore: "Restaurer" },
  },
  student: {
    eyebrow: "Espace d’apprentissage", title: "Mes classes", body: "Consultez au même endroit les partitions assignées, ressources, annonces, notes et commentaires du professeur.", loading: "Chargement du contenu des classes...", login: "Connectez-vous pour voir les classes associées à votre e-mail.", empty: "Aucune classe associée. Demandez au professeur d’ajouter votre e-mail de connexion à la liste.", assignments: "Devoirs de partition", resources: "Ressources pédagogiques", notifications: "Annonces de classe", unread: "non lus", due: "Échéance", noDue: "Aucune échéance", score: "Partition", openScore: "Ouvrir la partition", noShare: "La partition n’est pas encore partagée", submissionStatuses: { pending: "Non envoyé", submitted: "Envoyé", reviewed: "Évalué" }, feedback: "Commentaires du professeur", grade: "Note", noAssignments: "Aucun devoir pour le moment.", noResources: "Aucune ressource pour le moment.", noNotifications: "Aucune annonce pour le moment.", markRead: "Marquer comme lu", read: "Lu", guardianView: "Vue du responsable", studentView: "Vue de l’élève", exitClass: "Quitter la classe", exitReason: "Motif du départ (facultatif)", requestExit: "Demander à quitter", awaitingGuardian: "En attente de l’accord du responsable", cancelExit: "Retirer la demande", approveExit: "Approuver le départ", rejectExit: "Refuser le départ", exitRejected: "Le responsable a refusé la demande précédente. Une nouvelle demande peut être envoyée.", preferences: "Paramètres de notification", emailAnnouncements: "Recevoir les annonces par e-mail", emailHint: "Désactivé par défaut. Les nouvelles annonces seront envoyées à votre e-mail de connexion une fois activé.", summaryAria: "Résumé des classes et annonces non lues", loadingAria: "État du chargement des classes", preferencesAria: "Préférences de notification",
  },
} satisfies EducationMessages;
