import type { EducationMessages } from "../types";

export const jaEducationMessages = {
  pages: {
    classrooms: { metadataTitle: "クラスと学校の共同管理", metadataDescription: "クラス、名簿、教材、お知らせ、教育連携を管理します。", eyebrow: "クラス / 学校 ベータ", title: "クラス / 学校 ベータ", body: "クラス、名簿、教材、お知らせ、教育連携を一か所で管理します。" },
    student: { metadataTitle: "自分のクラス", metadataDescription: "楽譜課題、学習教材、お知らせ、成績、先生からのフィードバックを確認します。" },
  },
  shared: {
    roles: { owner: "所有者", admin: "管理者", teacher: "教師", assistant: "アシスタント", observer: "閲覧者", student: "生徒", guardian: "保護者" },
    statuses: { invited: "招待済み", active: "有効", archived: "アーカイブ済み", removed: "削除済み", pending: "保留中", published: "公開済み", scheduled: "予約済み", cancelled: "キャンセル済み", draft: "下書き", verified: "確認済み" },
    resourceTypes: { score: "楽譜", audio: "音声", video: "動画", document: "文書" }, resourceSources: { external: "リンク", file: "アップロードファイル" }, resourceVisibilities: { classroom: "クラス全員", selected: "選択した生徒", staff: "スタッフのみ" },
  },
  classrooms: {
    eyebrow: "教育連携", title: "クラス管理", body: "教師、合唱団、音楽教室のクラスと生徒名簿を管理します。課題をクラスに紐付け、提出物を生徒ごとに整理できます。", createTitle: "クラスを作成", name: "クラス名", description: "説明", create: "クラスを作成", creating: "作成しています...", empty: "クラスはまだありません。", students: "生徒", addStudent: "生徒を追加", displayName: "生徒名", contactEmail: "連絡先メール", externalRef: "学籍番号 / メモ", removeStudent: "削除", archiveClassroom: "クラスをアーカイブ", loading: "クラスを読み込んでいます...", created: "クラスを作成しました。", studentAdded: "生徒を追加しました。", bulkRoster: "名簿の一括登録", bulkHint: "表計算ソフトから、氏名、メール、学籍番号/メモをタブ区切りで貼り付けます。", importRoster: "名簿を取り込む", rosterImported: "名簿を取り込みました。", guardian: "保護者", guardianName: "保護者名", guardianEmail: "保護者のログインメール", relationship: "続柄（例：母）", inviteGuardian: "保護者を招待", guardianInvited: "保護者を招待しました。", archived: "アーカイブしました。", statusAria: "クラス操作の状態", loadingAria: "クラスの読み込み状態", rosterAria: "クラス名簿",
  },
  organization: {
    eyebrow: "組織の権限", title: "組織、校舎、クラススタッフ", body: "組織管理者は校舎とメンバーを管理します。教師とアシスタントはクラスを運営でき、閲覧者は読み取り専用です。招待メールはログイン時にサーバーで紐付けられます。", createOrganization: "組織を作成", organizationName: "組織名", addCampus: "校舎を追加", selectOrganization: "組織を選択", campusName: "校舎名", campusCode: "校舎コード", saveCampus: "校舎を保存", inviteOrganizationMember: "組織メンバーを招待", displayName: "表示名", signInEmail: "ログインメール", inviteMember: "メンバーを招待", campuses: "校舎", remove: "削除", classroomPlacement: "クラスの所属", selectClassroom: "クラスを選択", personalClassroom: "個人クラス", noCampus: "校舎なし", savePlacement: "所属を保存", assignClassroomStaff: "クラススタッフを割り当て", assignStaff: "スタッフを割り当て", classroomStaff: "クラススタッフ", noStaff: "スタッフは未割り当てです。", accessUpdated: "教育アクセスを更新しました。", placementUpdated: "クラスの所属を更新しました。", memberRemoved: "メンバーを削除しました。", statusAria: "組織アクセス操作の状態", organizationSelectAria: "組織", classroomSelectAria: "クラス", memberRoleAria: "組織メンバーの役割", staffRoleAria: "クラススタッフの役割",
  },
  operations: {
    eyebrow: "クラス運営", title: "お知らせ、教材ライブラリ、LMS", body: "生徒アカウントは名簿のメールで紐付きます。版管理された教材、予約通知、既読状況をここで管理します。", classroom: "クラス", currentClassroomAria: "現在のクラス", selectClassroom: "クラスを選択", statusAria: "教育運営の状態", saved: "クラスに保存しました。", archived: "アーカイブしました。", retriedEmails: "失敗したメール {count} 件を再度キューに追加しました。", rosterSynced: "生徒 {imported} 名を同期し、生徒以外 {skipped} 件をスキップしました。", retentionSaved: "教材バージョンの保持方針を保存しました。", retentionPurged: "期限切れの履歴バージョン {count} 件からファイル内容を削除しました。", fileUploaded: "ファイルをクラスへ安全にアップロードしました。", versionRestored: "v{from} を新しい v{to} として復元しました。", folderCreated: "フォルダーを作成しました。", resourceReused: "このクラスに教材を再利用しました。", folderUpdated: "フォルダーを更新し、教材バージョン {count} 件を作成しました。", resourceMoved: "教材を移動し、変更不可の v{version} を作成しました。",
    resource: { add: "教材を追加", publishVersion: "教材の新バージョンを公開", sourceAria: "教材の取得元", title: "教材タイトル", file: "教材ファイル", typeAria: "教材の種類", visibilityAria: "教材の公開範囲", studentsWithAccess: "アクセスできる生徒", noActiveStudents: "このクラスには権限を付与できる有効な生徒がいません。", folderAria: "教材フォルダー", rootFolder: "ルートフォルダー", tags: "タグ（カンマ区切り）", upload: "教材をアップロード", save: "教材を保存", cancel: "キャンセル", version: "v{version}", selectedStudents: "選択した生徒（{count}）", history: "履歴", newVersion: "新バージョン", archive: "アーカイブ", moveAria: "{title} を移動", move: "移動" },
    notification: { publish: "お知らせを公開", title: "お知らせのタイトル", body: "お知らせの本文", scheduleLabel: "公開予約（空欄なら今すぐ公開）", schedule: "予約", publishNow: "今すぐ公開", history: "お知らせの履歴", empty: "お知らせはまだありません。", read: "既読", email: "メール", sent: "送信済み", pending: "送信待ち", failed: "失敗", retryFailed: "失敗メールを再送", cancel: "キャンセル" },
    retention: { title: "バージョン保持", enable: "自動削除を有効にする", days: "履歴バージョンの保持日数", minimumVersions: "グループごとの最低保持バージョン数", note: "現在のバージョンと手動保持したバージョンは削除されません。ファイル内容のみを削除し、履歴は保持します。", previewSummary: "{count} バージョン（約 {size}）が対象です。", save: "方針を保存", preview: "プレビュー", purge: "対象を削除" },
    lms: { title: "LTI 1.3 接続", courseRef: "コース参照", baseUrl: "LMS URL（任意）", issuer: "発行者（https://...）", clientId: "クライアント ID", deploymentId: "デプロイメント ID", oidcAuthUrl: "OIDC 認証 URL", tokenUrl: "OAuth トークン URL", jwksUrl: "プラットフォーム JWKS URL", note: "保存後、LMS からツールを一度起動してください。署名、nonce、deployment、target link の検証がすべて成功した場合のみ接続が有効になります。", saveDraft: "下書きを保存", deploymentMissing: "デプロイメント ID が未設定です", rosterSynced: "名簿同期", syncRoster: "名簿を同期", section: "LMS / LTI", providers: { manual: "手動 / LTI", canvas: "Canvas", moodle: "Moodle", "google-classroom": "Google Classroom" } },
    library: { eyebrow: "教材ライブラリ", resourceCount: "教材 {count} 件", search: "タイトル、フォルダー、タグを検索", noMatches: "一致する教材はありません。", newFolder: "新しいフォルダー名", parentFolderAria: "親フォルダー", underRoot: "ルート直下", createFolder: "フォルダーを作成", sourceClassroomAria: "コピー元クラス", sourceClassroom: "コピー元クラスを選択", sourceResourceAria: "コピー元教材", selectResource: "教材を選択", reuseFolderAria: "コピー先フォルダー", reuseRoot: "ルートにコピー", reuse: "教材を再利用", folderManagementAria: "フォルダー管理", renameAria: "{path} の名前を変更", parentForAria: "{path} の親", save: "保存", cancel: "キャンセル", edit: "編集", archiveEmptyFolder: "空フォルダーをアーカイブ", root: "ルート" },
    history: { aria: "{title} のバージョン履歴", note: "履歴は読み取り専用です。復元すると新しい現在バージョンが作成されます。", contentExpired: "内容の期限切れ", historical: "履歴", current: "現在", held: "保持中", restoredFromHistory: "履歴から復元", download: "ダウンロード", open: "開く", removeHold: "保持を解除", keep: "保持", restore: "復元" },
  },
  student: {
    eyebrow: "学習ハブ", title: "自分のクラス", body: "先生が公開した楽譜課題、練習教材、お知らせ、成績、フィードバックをまとめて確認できます。", loading: "クラス内容を読み込んでいます...", login: "ログインして、アカウントのメールに紐付くクラスを確認してください。", empty: "紐付いたクラスはまだありません。先生にログインメールを名簿へ追加してもらってください。", assignments: "楽譜課題", resources: "学習教材", notifications: "クラスのお知らせ", unread: "件未読", due: "期限", noDue: "期限なし", score: "楽譜", openScore: "楽譜を開く", noShare: "楽譜はまだ共有されていません", submissionStatuses: { pending: "未提出", submitted: "提出済み", reviewed: "確認済み" }, feedback: "先生からのフィードバック", grade: "成績", noAssignments: "課題はまだありません。", noResources: "学習教材はまだありません。", noNotifications: "お知らせはまだありません。", markRead: "既読にする", read: "既読", guardianView: "保護者ビュー", studentView: "生徒ビュー", exitClass: "クラスを退出", exitReason: "退出理由（任意）", requestExit: "退出を申請", awaitingGuardian: "保護者の同意待ち", cancelExit: "申請を取り下げ", approveExit: "退出を承認", rejectExit: "退出を拒否", exitRejected: "保護者が前回の申請を拒否しました。新しい申請を送信できます。", preferences: "通知設定", emailAnnouncements: "クラスのお知らせをメールで受け取る", emailHint: "初期設定はオフです。有効にすると、新しいクラスのお知らせがログインメールへ送信されます。", summaryAria: "クラスと未読のお知らせの概要", loadingAria: "生徒クラスの読み込み状態", preferencesAria: "通知設定",
  },
} satisfies EducationMessages;
