import type { EducationMessages } from "../types";

export const koEducationMessages = {
  pages: {
    classrooms: { metadataTitle: "수업 및 학교 협업", metadataDescription: "수업, 명단, 자료, 알림 및 교육 협업을 관리합니다.", eyebrow: "수업 / 학교 베타", title: "수업 / 학교 베타", body: "수업, 학생 명단, 자료, 알림 및 교육 협업을 한곳에서 관리하세요." },
    student: { metadataTitle: "내 수업", metadataDescription: "악보 과제, 학습 자료, 공지, 성적 및 선생님 피드백을 확인하세요." },
  },
  shared: {
    roles: { owner: "소유자", admin: "관리자", teacher: "교사", assistant: "보조 교사", observer: "참관자", student: "학생", guardian: "보호자" },
    statuses: { invited: "초대됨", active: "활성", archived: "보관됨", removed: "삭제됨", pending: "대기 중", published: "게시됨", scheduled: "예약됨", cancelled: "취소됨", draft: "초안", verified: "확인됨" },
    resourceTypes: { score: "악보", audio: "오디오", video: "동영상", document: "문서" }, resourceSources: { external: "링크", file: "업로드 파일" }, resourceVisibilities: { classroom: "전체 수업", selected: "선택한 학생", staff: "교직원만" },
  },
  classrooms: {
    eyebrow: "교육 협업", title: "수업 관리", body: "교사, 합창단 및 음악 학원의 수업과 학생 명단을 관리하세요. 과제를 수업에 연결하고 제출물을 학생별로 정리할 수 있습니다.", createTitle: "수업 만들기", name: "수업 이름", description: "설명", create: "수업 만들기", creating: "만드는 중...", empty: "아직 수업이 없습니다.", students: "학생", addStudent: "학생 추가", displayName: "학생 이름", contactEmail: "연락처 이메일", externalRef: "학번 / 메모", removeStudent: "제거", archiveClassroom: "수업 보관", loading: "수업을 불러오는 중...", created: "수업을 만들었습니다.", studentAdded: "학생을 추가했습니다.", bulkRoster: "명단 일괄 등록", bulkHint: "스프레드시트에서 이름, 이메일, 학번/메모를 탭으로 구분하여 붙여넣으세요.", importRoster: "명단 가져오기", rosterImported: "명단을 가져왔습니다.", guardian: "보호자", guardianName: "보호자 이름", guardianEmail: "보호자 로그인 이메일", relationship: "관계(예: 어머니)", inviteGuardian: "보호자 초대", guardianInvited: "보호자를 초대했습니다.", archived: "보관했습니다.", statusAria: "수업 작업 상태", loadingAria: "수업 불러오기 상태", rosterAria: "수업 명단",
  },
  organization: {
    eyebrow: "기관 권한", title: "기관, 캠퍼스 및 수업 교직원", body: "기관 관리자는 캠퍼스와 구성원을 관리합니다. 교사와 보조 교사는 수업을 운영하며 참관자는 읽기 전용입니다. 이메일 초대는 로그인할 때 서버에서 연결됩니다.", createOrganization: "기관 만들기", organizationName: "기관 이름", addCampus: "캠퍼스 추가", selectOrganization: "기관 선택", campusName: "캠퍼스 이름", campusCode: "캠퍼스 코드", saveCampus: "캠퍼스 저장", inviteOrganizationMember: "기관 구성원 초대", displayName: "표시 이름", signInEmail: "로그인 이메일", inviteMember: "구성원 초대", campuses: "캠퍼스", remove: "제거", classroomPlacement: "수업 소속", selectClassroom: "수업 선택", personalClassroom: "개인 수업", noCampus: "캠퍼스 없음", savePlacement: "소속 저장", assignClassroomStaff: "수업 교직원 배정", assignStaff: "교직원 배정", classroomStaff: "수업 교직원", noStaff: "배정된 교직원이 없습니다.", accessUpdated: "교육 접근 권한을 업데이트했습니다.", placementUpdated: "수업 소속을 업데이트했습니다.", memberRemoved: "구성원을 제거했습니다.", statusAria: "기관 접근 작업 상태", organizationSelectAria: "기관", classroomSelectAria: "수업", memberRoleAria: "기관 구성원 역할", staffRoleAria: "수업 교직원 역할",
  },
  operations: {
    eyebrow: "수업 운영", title: "알림, 자료실 및 LMS", body: "학생 계정은 명단 이메일로 연결됩니다. 버전별 자료, 예약 공지 및 읽음 확인을 여기에서 관리하세요.", classroom: "수업", currentClassroomAria: "현재 수업", selectClassroom: "수업 선택", statusAria: "교육 운영 상태", saved: "수업에 저장했습니다.", archived: "보관했습니다.", retriedEmails: "실패한 이메일 {count}건을 다시 대기열에 추가했습니다.", rosterSynced: "학생 {imported}명을 동기화하고 학생이 아닌 기록 {skipped}건을 건너뛰었습니다.", retentionSaved: "자료 버전 보존 정책을 저장했습니다.", retentionPurged: "만료된 기록 버전 {count}개의 파일 내용을 삭제했습니다.", fileUploaded: "파일을 수업에 안전하게 업로드했습니다.", versionRestored: "v{from}을 새 v{to}로 복원했습니다.", folderCreated: "폴더를 만들었습니다.", resourceReused: "이 수업에 자료를 재사용했습니다.", folderUpdated: "폴더를 업데이트하고 자료 버전 {count}개를 만들었습니다.", resourceMoved: "자료를 이동하고 변경 불가 v{version}을 만들었습니다.",
    resource: { add: "자료 추가", publishVersion: "자료 새 버전 게시", sourceAria: "자료 출처", title: "자료 제목", file: "자료 파일", typeAria: "자료 유형", visibilityAria: "자료 공개 범위", studentsWithAccess: "접근 가능한 학생", noActiveStudents: "이 수업에는 권한을 부여할 활성 학생이 없습니다.", folderAria: "자료 폴더", rootFolder: "루트 폴더", tags: "쉼표로 구분한 태그", upload: "자료 업로드", save: "자료 저장", cancel: "취소", version: "v{version}", selectedStudents: "선택한 학생({count}명)", history: "기록", newVersion: "새 버전", archive: "보관", moveAria: "{title} 이동", move: "이동" },
    notification: { publish: "공지 게시", title: "공지 제목", body: "공지 내용", scheduleLabel: "예약 게시(비워 두면 즉시 게시)", schedule: "예약", publishNow: "지금 게시", history: "공지 기록", empty: "아직 공지가 없습니다.", read: "읽음", email: "이메일", sent: "전송됨", pending: "전송 대기", failed: "실패", retryFailed: "실패 이메일 재시도", cancel: "취소" },
    retention: { title: "버전 보존", enable: "자동 정리 사용", days: "기록 버전 보존 일수", minimumVersions: "그룹당 최소 보존 버전", note: "현재 버전과 수동 보존 버전은 삭제되지 않습니다. 파일 내용만 정리하고 버전 기록은 유지합니다.", previewSummary: "{count}개 버전, 약 {size}가 대상입니다.", save: "정책 저장", preview: "미리보기", purge: "대상 정리" },
    lms: { title: "LTI 1.3 연결", courseRef: "과정 참조", baseUrl: "LMS URL(선택 사항)", issuer: "발급자(https://...)", clientId: "클라이언트 ID", deploymentId: "배포 ID", oidcAuthUrl: "OIDC 인증 URL", tokenUrl: "OAuth 토큰 URL", jwksUrl: "플랫폼 JWKS URL", note: "저장한 후 LMS에서 도구를 한 번 실행하세요. 서명, nonce, deployment 및 target link 검증이 모두 통과해야 연결이 활성화됩니다.", saveDraft: "초안 저장", deploymentMissing: "배포 ID가 설정되지 않음", rosterSynced: "명단 동기화", syncRoster: "명단 동기화", section: "LMS / LTI", providers: { manual: "수동 / LTI", canvas: "Canvas", moodle: "Moodle", "google-classroom": "Google Classroom" } },
    library: { eyebrow: "자료실", resourceCount: "자료 {count}개", search: "제목, 폴더 또는 태그 검색", noMatches: "일치하는 자료가 없습니다.", newFolder: "새 폴더 이름", parentFolderAria: "상위 폴더", underRoot: "루트 아래", createFolder: "폴더 만들기", sourceClassroomAria: "원본 수업", sourceClassroom: "원본 수업 선택", sourceResourceAria: "원본 자료", selectResource: "자료 선택", reuseFolderAria: "재사용 대상 폴더", reuseRoot: "루트에 재사용", reuse: "자료 재사용", folderManagementAria: "폴더 관리", renameAria: "{path} 이름 바꾸기", parentForAria: "{path}의 상위 폴더", save: "저장", cancel: "취소", edit: "편집", archiveEmptyFolder: "빈 폴더 보관", root: "루트" },
    history: { aria: "{title} 버전 기록", note: "기록은 읽기 전용입니다. 복원하면 새 현재 버전이 만들어집니다.", contentExpired: "내용 만료", historical: "기록", current: "현재", held: "보존됨", restoredFromHistory: "기록에서 복원", download: "다운로드", open: "열기", removeHold: "보존 해제", keep: "보존", restore: "복원" },
  },
  student: {
    eyebrow: "학습 허브", title: "내 수업", body: "선생님이 게시한 악보 과제, 연습 자료, 공지, 성적 및 피드백을 한곳에서 확인하세요.", loading: "수업 내용을 불러오는 중...", login: "로그인하여 계정 이메일에 연결된 수업을 확인하세요.", empty: "연결된 수업이 아직 없습니다. 선생님에게 로그인 이메일을 명단에 추가해 달라고 요청하세요.", assignments: "악보 과제", resources: "학습 자료", notifications: "수업 공지", unread: "개 읽지 않음", due: "마감", noDue: "마감일 없음", score: "악보", openScore: "악보 열기", noShare: "악보가 아직 공유되지 않았습니다", submissionStatuses: { pending: "미제출", submitted: "제출됨", reviewed: "검토됨" }, feedback: "선생님 피드백", grade: "성적", noAssignments: "아직 과제가 없습니다.", noResources: "아직 학습 자료가 없습니다.", noNotifications: "아직 공지가 없습니다.", markRead: "읽음으로 표시", read: "읽음", guardianView: "보호자 보기", studentView: "학생 보기", exitClass: "수업 나가기", exitReason: "나가는 이유(선택 사항)", requestExit: "나가기 요청", awaitingGuardian: "보호자 동의 대기", cancelExit: "요청 철회", approveExit: "나가기 승인", rejectExit: "나가기 거부", exitRejected: "보호자가 이전 요청을 거부했습니다. 새 요청을 제출할 수 있습니다.", preferences: "알림 설정", emailAnnouncements: "수업 공지를 이메일로 받기", emailHint: "기본적으로 꺼져 있습니다. 켜면 새 수업 공지가 로그인 이메일로 전송됩니다.", summaryAria: "수업 및 읽지 않은 공지 요약", loadingAria: "학생 수업 불러오기 상태", preferencesAria: "알림 환경설정",
  },
} satisfies EducationMessages;
