import type { EducationMessages } from "../types";

export const ruEducationMessages = {
  pages: {
    classrooms: { metadataTitle: "Совместная работа классов и школ", metadataDescription: "Управляйте классами, списками, материалами, уведомлениями и учебной работой.", eyebrow: "Класс / Школа — бета", title: "Класс / Школа — бета", body: "Управляйте классами, списками учеников, материалами, уведомлениями и учебной работой в одном месте." },
    student: { metadataTitle: "Мои классы", metadataDescription: "Просматривайте задания по партитурам, материалы, объявления, оценки и отзывы преподавателя." },
  },
  shared: {
    roles: { owner: "Владелец", admin: "Администратор", teacher: "Преподаватель", assistant: "Ассистент", observer: "Наблюдатель", student: "Ученик", guardian: "Опекун" },
    statuses: { invited: "Приглашён", active: "Активен", archived: "В архиве", removed: "Удалён", pending: "Ожидает", published: "Опубликовано", scheduled: "Запланировано", cancelled: "Отменено", draft: "Черновик", verified: "Проверено" },
    resourceTypes: { score: "Партитура", audio: "Аудио", video: "Видео", document: "Документ" }, resourceSources: { external: "Ссылка", file: "Загруженный файл" }, resourceVisibilities: { classroom: "Весь класс", selected: "Выбранные ученики", staff: "Только сотрудники" },
  },
  classrooms: {
    eyebrow: "Обучение", title: "Управление классами", body: "Управляйте классами и списками учеников для преподавателей, хоров и студий. Задания можно привязывать к классам, а работы хранить по ученикам.", createTitle: "Создать класс", name: "Название класса", description: "Описание", create: "Создать класс", creating: "Создание...", empty: "Классов пока нет.", students: "Ученики", addStudent: "Добавить ученика", displayName: "Имя ученика", contactEmail: "Контактная почта", externalRef: "ID ученика / заметка", removeStudent: "Удалить", archiveClassroom: "Архивировать класс", loading: "Загрузка классов...", created: "Класс создан.", studentAdded: "Ученик добавлен.", bulkRoster: "Массовый список", bulkHint: "Вставьте из таблицы имя, почту и ID/заметку в столбцах, разделённых табуляцией.", importRoster: "Импортировать список", rosterImported: "Список импортирован.", guardian: "Опекун", guardianName: "Имя опекуна", guardianEmail: "Почта опекуна для входа", relationship: "Связь, например: мать", inviteGuardian: "Пригласить опекуна", guardianInvited: "Опекун приглашён.", archived: "Архивировано.", statusAria: "Состояние операции с классом", loadingAria: "Состояние загрузки классов", rosterAria: "Списки классов",
  },
  organization: {
    eyebrow: "Доступ организации", title: "Организации, кампусы и сотрудники классов", body: "Администраторы управляют кампусами и участниками. Преподаватели и ассистенты ведут классы, наблюдатели имеют доступ только для чтения. Приглашения по почте связываются на сервере при входе.", createOrganization: "Создать организацию", organizationName: "Название организации", addCampus: "Добавить кампус", selectOrganization: "Выбрать организацию", campusName: "Название кампуса", campusCode: "Код кампуса", saveCampus: "Сохранить кампус", inviteOrganizationMember: "Пригласить участника", displayName: "Отображаемое имя", signInEmail: "Почта для входа", inviteMember: "Пригласить участника", campuses: "Кампусы", remove: "Удалить", classroomPlacement: "Принадлежность класса", selectClassroom: "Выбрать класс", personalClassroom: "Личный класс", noCampus: "Без кампуса", savePlacement: "Сохранить принадлежность", assignClassroomStaff: "Назначить сотрудников класса", assignStaff: "Назначить", classroomStaff: "Сотрудники класса", noStaff: "Сотрудники не назначены.", accessUpdated: "Учебный доступ обновлён.", placementUpdated: "Принадлежность класса обновлена.", memberRemoved: "Участник удалён.", statusAria: "Состояние операции доступа", organizationSelectAria: "Организация", classroomSelectAria: "Класс", memberRoleAria: "Роль участника", staffRoleAria: "Роль сотрудника класса",
  },
  operations: {
    eyebrow: "Работа класса", title: "Уведомления, материалы и LMS", body: "Учётные записи связываются по почте из списка. Управляйте версиями материалов, запланированными объявлениями и отметками о прочтении.", classroom: "Класс", currentClassroomAria: "Текущий класс", selectClassroom: "Выбрать класс", statusAria: "Состояние учебной операции", saved: "Сохранено в классе.", archived: "Архивировано.", retriedEmails: "Неудачных писем снова поставлено в очередь: {count}.", rosterSynced: "Учеников синхронизировано: {imported}; прочих записей пропущено: {skipped}.", retentionSaved: "Политика хранения версий сохранена.", retentionPurged: "Удалено содержимое {count} просроченных исторических версий.", fileUploaded: "Файл безопасно загружен в класс.", versionRestored: "v{from} восстановлена как новая v{to}.", folderCreated: "Папка создана.", resourceReused: "Материал повторно использован в этом классе.", folderUpdated: "Папка обновлена; создано версий материалов: {count}.", resourceMoved: "Материал перемещён как неизменяемая v{version}.",
    resource: { add: "Добавить материал", publishVersion: "Опубликовать новую версию", sourceAria: "Источник материала", title: "Название материала", file: "Файл материала", typeAria: "Тип материала", visibilityAria: "Доступ к материалу", studentsWithAccess: "Ученики с доступом", noActiveStudents: "В этом классе нет активных учеников для выдачи доступа.", folderAria: "Папка материала", rootFolder: "Корневая папка", tags: "Теги через запятую", upload: "Загрузить материал", save: "Сохранить материал", cancel: "Отмена", version: "v{version}", selectedStudents: "Выбрано учеников: {count}", history: "История", newVersion: "Новая версия", archive: "В архив", moveAria: "Переместить {title}", move: "Переместить" },
    notification: { publish: "Опубликовать уведомление", title: "Заголовок уведомления", body: "Текст уведомления", scheduleLabel: "Расписание (пусто — опубликовать сейчас)", schedule: "Запланировать", publishNow: "Опубликовать сейчас", history: "История уведомлений", empty: "Уведомлений пока нет.", read: "Прочитано", email: "Почта", sent: "отправлено", pending: "ожидает", failed: "ошибок", retryFailed: "Повторить неудачные письма", cancel: "Отменить" },
    retention: { title: "Хранение версий", enable: "Включить автоматическую очистку", days: "Дней хранения исторических версий", minimumVersions: "Минимум исторических версий в группе", note: "Текущие и сохранённые вручную версии не удаляются. Очистка удаляет файл, сохраняя историю.", previewSummary: "Версий к очистке: {count}, около {size}.", save: "Сохранить политику", preview: "Предпросмотр", purge: "Очистить подходящие" },
    lms: { title: "Подключение LTI 1.3", courseRef: "Ссылка на курс", baseUrl: "URL LMS (необязательно)", issuer: "Издатель (https://...)", clientId: "ID клиента", deploymentId: "ID развёртывания", oidcAuthUrl: "URL авторизации OIDC", tokenUrl: "URL токена OAuth", jwksUrl: "URL JWKS платформы", note: "После сохранения один раз запустите инструмент из LMS. Подключение активируется только после проверки подписи, nonce, развёртывания и целевой ссылки.", saveDraft: "Сохранить черновик", deploymentMissing: "ID развёртывания не настроен", rosterSynced: "список синхронизирован", syncRoster: "Синхронизировать список", section: "LMS / LTI", providers: { manual: "Вручную / LTI", canvas: "Canvas", moodle: "Moodle", "google-classroom": "Google Classroom" } },
    library: { eyebrow: "Библиотека материалов", resourceCount: "Материалов: {count}", search: "Поиск по названию, папке или тегу", noMatches: "Подходящих материалов нет.", newFolder: "Название новой папки", parentFolderAria: "Родительская папка", underRoot: "В корне", createFolder: "Создать папку", sourceClassroomAria: "Исходный класс", sourceClassroom: "Выбрать исходный класс", sourceResourceAria: "Исходный материал", selectResource: "Выбрать материал", reuseFolderAria: "Целевая папка", reuseRoot: "Повторно использовать в корне", reuse: "Повторно использовать", folderManagementAria: "Управление папками", renameAria: "Переименовать {path}", parentForAria: "Родитель для {path}", save: "Сохранить", cancel: "Отмена", edit: "Изменить", archiveEmptyFolder: "Архивировать пустую папку", root: "Корень" },
    history: { aria: "История версий {title}", note: "История доступна только для чтения. Восстановление создаёт новую текущую версию.", contentExpired: "Содержимое истекло", historical: "Историческая", current: "Текущая", held: "Сохранена", restoredFromHistory: "Восстановлена из истории", download: "Скачать", open: "Открыть", removeHold: "Снять сохранение", keep: "Сохранить", restore: "Восстановить" },
  },
  student: {
    eyebrow: "Учебный центр", title: "Мои классы", body: "Просматривайте назначенные партитуры, материалы, объявления, оценки и отзывы преподавателя в одном месте.", loading: "Загрузка материалов класса...", login: "Войдите, чтобы увидеть классы, связанные с вашей почтой.", empty: "Связанных классов пока нет. Попросите преподавателя добавить вашу почту для входа в список.", assignments: "Задания по партитурам", resources: "Учебные материалы", notifications: "Объявления класса", unread: "не прочитано", due: "Срок", noDue: "Без срока", score: "Партитура", openScore: "Открыть партитуру", noShare: "Партитура ещё не опубликована", submissionStatuses: { pending: "Не отправлено", submitted: "Отправлено", reviewed: "Проверено" }, feedback: "Отзыв преподавателя", grade: "Оценка", noAssignments: "Заданий пока нет.", noResources: "Материалов пока нет.", noNotifications: "Объявлений пока нет.", markRead: "Отметить прочитанным", read: "Прочитано", guardianView: "Режим опекуна", studentView: "Режим ученика", exitClass: "Покинуть класс", exitReason: "Причина выхода (необязательно)", requestExit: "Запросить выход", awaitingGuardian: "Ожидается согласие опекуна", cancelExit: "Отозвать запрос", approveExit: "Разрешить выход", rejectExit: "Отклонить выход", exitRejected: "Опекун отклонил предыдущий запрос. Можно отправить новый.", preferences: "Настройки уведомлений", emailAnnouncements: "Получать объявления по почте", emailHint: "По умолчанию выключено. После включения новые объявления будут приходить на вашу почту для входа.", summaryAria: "Сводка классов и непрочитанных объявлений", loadingAria: "Состояние загрузки классов", preferencesAria: "Настройки уведомлений",
  },
} satisfies EducationMessages;
