import type { SupportedLocale } from "@score/i18n";
import { getScoreOperationMessages } from "./score-operation-messages";
import { getScoreReadinessMessages } from "./score-readiness-messages";

const keys = ["edit", "jianpu", "transpose", "play", "export", "more", "advanced", "share", "history", "teaching", "parts", "source", "close", "importTitle", "chooseFile", "formats", "start", "upgrade", "back", "format", "download", "retry", "processing", "savedFile", "fileLost", "unsupported", "tooLarge", "autoSave", "resume", "waitingAccess", "accountMismatch", "paymentOptions", "planDetails", "legacy", "saveBeforeLeave"] as const;
export type FlowMessages = Record<typeof keys[number], string> & { scoreReadiness: ReturnType<typeof getScoreReadinessMessages>; scoreOperations: ReturnType<typeof getScoreOperationMessages> };
const catalogs: Record<SupportedLocale, readonly string[]> = {
  en: ["Edit", "Jianpu", "Transpose", "Play", "Export", "More", "Advanced settings", "Share & comments", "Version history", "Teaching", "Parts", "Source & review", "Close", "Start with your score", "Choose a score file", "PDF, images, MusicXML, MIDI or a score backup · up to 20 MB", "Start processing", "Upgrade to continue", "Back to your score", "File format", "Download", "Try again", "Processing…", "Your file is ready. Continue when you are ready.", "Your browser could not keep this file. Please choose it again after returning.", "Choose a supported score file.", "This file exceeds 20 MB. Please choose a smaller file.", "Changes save automatically", "Continue your work", "Confirming account access…", "Sign in with the account used for this purchase.", "Payment options", "Plan details", "Previous conversion tasks", "Please save your changes before leaving."],
  "zh-CN": ["编辑", "简谱", "移调", "播放", "导出", "更多", "高级设置", "分享与批注", "版本历史", "教学", "声部分谱", "原件与校对", "关闭", "从你的乐谱开始", "选择乐谱文件", "PDF、图片、MusicXML、MIDI 或乐谱备份 · 最大 20 MB", "开始处理", "升级并继续", "返回当前乐谱", "文件格式", "下载", "重试", "正在处理…", "文件已保留，可以继续处理。", "浏览器未能保留文件，返回后请重新选择。", "请选择支持的乐谱文件。", "文件超过 20 MB，请选择较小的文件。", "修改自动保存", "继续刚才的操作", "正在确认账户权限…", "请使用此次购买的账户登录。", "其他支付方式", "套餐详情", "旧版转换任务", "离开前请先保存修改。"],
  "zh-TW": ["編輯", "簡譜", "移調", "播放", "匯出", "更多", "進階設定", "分享與註解", "版本歷史", "教學", "聲部分譜", "原件與校對", "關閉", "從你的樂譜開始", "選擇樂譜檔案", "PDF、圖片、MusicXML、MIDI 或樂譜備份 · 最大 20 MB", "開始處理", "升級並繼續", "返回目前樂譜", "檔案格式", "下載", "重試", "正在處理…", "檔案已保留，可以繼續處理。", "瀏覽器未能保留檔案，返回後請重新選擇。", "請選擇支援的樂譜檔案。", "檔案超過 20 MB，請選擇較小的檔案。", "修改自動儲存", "繼續剛才的操作", "正在確認帳戶權限…", "請使用此次購買的帳戶登入。", "其他付款方式", "方案詳情", "舊版轉換任務", "離開前請先儲存修改。"],
  ja: ["編集", "数字譜", "移調", "再生", "書き出し", "その他", "詳細設定", "共有とコメント", "変更履歴", "指導", "パート", "原本と確認", "閉じる", "楽譜から始める", "楽譜ファイルを選択", "PDF・画像・MusicXML・MIDI・バックアップ（最大20 MB）", "処理を開始", "アップグレードして続行", "楽譜に戻る", "ファイル形式", "ダウンロード", "再試行", "処理中…", "ファイルを保持しました。続行できます。", "ファイルを保持できませんでした。戻った後に再選択してください。", "対応する楽譜ファイルを選んでください。", "20 MB以下のファイルを選んでください。", "変更は自動保存されます", "作業を続ける", "アクセス権を確認中…", "購入に使用したアカウントでログインしてください。", "他の支払い方法", "プラン詳細", "以前の変換タスク", "移動する前に変更を保存してください。"],
  ko: ["편집", "숫자악보", "조옮김", "재생", "내보내기", "더 보기", "고급 설정", "공유 및 댓글", "버전 기록", "수업", "파트", "원본 및 검토", "닫기", "악보로 시작", "악보 파일 선택", "PDF, 이미지, MusicXML, MIDI 또는 백업 · 최대 20 MB", "처리 시작", "업그레이드 후 계속", "악보로 돌아가기", "파일 형식", "다운로드", "다시 시도", "처리 중…", "파일이 유지되었습니다. 계속할 수 있습니다.", "파일을 보관하지 못했습니다. 돌아온 후 다시 선택하세요.", "지원되는 악보 파일을 선택하세요.", "20 MB 이하의 파일을 선택하세요.", "변경 사항 자동 저장", "작업 계속", "계정 권한 확인 중…", "구매한 계정으로 로그인하세요.", "다른 결제 방법", "요금제 상세", "이전 변환 작업", "이동하기 전에 변경 사항을 저장하세요."],
  fr: ["Éditer", "Jianpu", "Transposer", "Écouter", "Exporter", "Plus", "Réglages avancés", "Partage et commentaires", "Historique", "Enseignement", "Parties", "Source et vérification", "Fermer", "Commencez avec votre partition", "Choisir une partition", "PDF, images, MusicXML, MIDI ou sauvegarde · 20 Mo max.", "Lancer le traitement", "Mettre à niveau et continuer", "Revenir à la partition", "Format", "Télécharger", "Réessayer", "Traitement…", "Votre fichier est conservé. Vous pouvez continuer.", "Le navigateur n’a pas conservé ce fichier. Sélectionnez-le à nouveau à votre retour.", "Choisissez un fichier pris en charge.", "Choisissez un fichier de 20 Mo maximum.", "Enregistrement automatique", "Reprendre le travail", "Vérification de l’accès…", "Connectez-vous au compte utilisé pour cet achat.", "Autres moyens de paiement", "Détails des offres", "Anciennes conversions", "Enregistrez vos modifications avant de quitter."],
  es: ["Editar", "Jianpu", "Transportar", "Reproducir", "Exportar", "Más", "Ajustes avanzados", "Compartir y comentarios", "Historial", "Enseñanza", "Partes", "Original y revisión", "Cerrar", "Empieza con tu partitura", "Elegir partitura", "PDF, imágenes, MusicXML, MIDI o copia · máx. 20 MB", "Iniciar proceso", "Mejorar plan y continuar", "Volver a la partitura", "Formato", "Descargar", "Reintentar", "Procesando…", "El archivo se ha conservado. Puedes continuar.", "El navegador no pudo conservar el archivo. Vuelve a elegirlo al regresar.", "Elige un archivo compatible.", "Elige un archivo de hasta 20 MB.", "Guardado automático", "Continuar el trabajo", "Verificando acceso…", "Inicia sesión con la cuenta de esta compra.", "Otros métodos de pago", "Detalles del plan", "Conversiones anteriores", "Guarda los cambios antes de salir."],
  de: ["Bearbeiten", "Jianpu", "Transponieren", "Abspielen", "Exportieren", "Mehr", "Erweiterte Einstellungen", "Teilen und Kommentare", "Versionsverlauf", "Unterricht", "Stimmen", "Vorlage und Prüfung", "Schließen", "Mit Ihrer Partitur beginnen", "Notendatei auswählen", "PDF, Bilder, MusicXML, MIDI oder Sicherung · max. 20 MB", "Verarbeitung starten", "Upgrade und weiter", "Zurück zur Partitur", "Dateiformat", "Herunterladen", "Erneut versuchen", "Verarbeitung…", "Ihre Datei wurde aufbewahrt. Sie können fortfahren.", "Der Browser konnte die Datei nicht aufbewahren. Bitte wählen Sie sie nach der Rückkehr erneut.", "Bitte wählen Sie eine unterstützte Datei.", "Bitte wählen Sie eine Datei bis 20 MB.", "Änderungen werden automatisch gespeichert", "Arbeit fortsetzen", "Zugriff wird geprüft…", "Melden Sie sich mit dem Konto dieses Kaufs an.", "Weitere Zahlungsarten", "Tarifdetails", "Frühere Konvertierungen", "Speichern Sie Änderungen vor dem Verlassen."],
  ru: ["Редактор", "Цифровая нотация", "Транспонировать", "Слушать", "Экспорт", "Ещё", "Дополнительные настройки", "Доступ и комментарии", "История версий", "Обучение", "Партии", "Оригинал и проверка", "Закрыть", "Начните со своей партитуры", "Выбрать файл", "PDF, изображения, MusicXML, MIDI или копия · до 20 МБ", "Начать обработку", "Улучшить тариф и продолжить", "Вернуться к партитуре", "Формат файла", "Скачать", "Повторить", "Обработка…", "Файл сохранён. Можно продолжить.", "Браузер не смог сохранить файл. Выберите его снова после возврата.", "Выберите поддерживаемый файл.", "Выберите файл размером до 20 МБ.", "Изменения сохраняются автоматически", "Продолжить работу", "Проверка доступа…", "Войдите в аккаунт, использованный для покупки.", "Другие способы оплаты", "Сведения о тарифе", "Прежние задачи конвертации", "Сохраните изменения перед выходом."],
};
export function getFlowMessages(locale: SupportedLocale): FlowMessages {
  const values = catalogs[locale];
  return { ...Object.fromEntries(keys.map((key, i) => [key, values[i] ?? catalogs.en[i]])), scoreReadiness: getScoreReadinessMessages(locale), scoreOperations: getScoreOperationMessages(locale) } as FlowMessages;
}
