import type { SupportedLocale } from "@score/i18n";

const recoveryDetails: Record<SupportedLocale, readonly string[]> = {
  en: ['Staff lines are too small for reliable recognition. Retry to apply automatic image recovery; if it still fails, use a clearer scan.', 'Recognition reached its time limit. Retry the original file.', 'No usable musical content was produced. Retry, or use a clearer scan.', 'The recognition service could not run. Retry when it is available.', 'Your original file is saved. Retry uses it directly; no upload is needed. Failed or cancelled attempts release their reserved allowance or credits. Review the result before choosing a paid export.', "Temporary server storage space is unavailable for this job. Your original is saved; try again later."],
  'zh-CN': ['谱线间距过小，识别引擎无法可靠读取。重试会自动恢复图片尺寸；仍失败时可换更清晰的扫描件。', '识谱达到处理时限，请使用原文件重试。', '未能生成可用的乐谱内容，请重试或换更清晰的扫描件。', '识谱服务暂时无法运行，请稍后重试。', '原文件已保留，点击重试即可，无需重新上传。失败或取消会释放已预留的次数／积分。先校对结果，再选择付费导出。', "服务器暂时无法提供识谱所需的存储空间。原文件已保存，请稍后重试。"],
  'zh-TW': ['譜線間距過小，辨識引擎無法可靠讀取。重試會自動恢復圖片尺寸；仍失敗時可換更清晰的掃描檔。', '識譜達到處理時限，請使用原檔案重試。', '未能產生可用的樂譜內容，請重試或換更清晰的掃描檔。', '識譜服務暫時無法運作，請稍後重試。', '原檔案已保留，點擊重試即可，無需重新上傳。失敗或取消會釋放已預留的次數／點數。先校對結果，再選擇付費匯出。', "伺服器暫時無法提供識譜所需的儲存空間。原檔案已保存，請稍後重試。"],
  ja: ['譜線の間隔が小さすぎます。再試行で画像サイズを自動回復します。失敗が続く場合は鮮明なスキャンを使ってください。', '処理時間の上限に達しました。元のファイルで再試行してください。', '使用できる楽譜を生成できませんでした。再試行するか鮮明なスキャンを使ってください。', '認識サービスを実行できません。後で再試行してください。', '元のファイルは保存済みです。再試行に再アップロードは不要です。失敗・キャンセルした処理の予約枠やクレジットは戻ります。結果を確認してから有料書き出しを選べます。', "サーバーの一時保存領域を確保できません。元のファイルは保存済みです。後で再試行してください。"],
  ko: ['오선 간격이 너무 작습니다. 재시도하면 이미지 크기를 자동 복원합니다. 계속 실패하면 더 선명한 스캔을 사용하세요.', '처리 시간이 초과되었습니다. 원본 파일로 다시 시도하세요.', '사용 가능한 악보를 만들지 못했습니다. 다시 시도하거나 더 선명한 스캔을 사용하세요.', '인식 서비스를 실행할 수 없습니다. 나중에 다시 시도하세요.', '원본 파일이 저장되어 있습니다. 다시 업로드할 필요 없이 재시도할 수 있습니다. 실패하거나 취소된 작업은 예약 횟수나 크레딧을 반환합니다. 결과를 검토한 후 유료 내보내기를 선택하세요.', "서버의 임시 저장 공간을 확보할 수 없습니다. 원본은 저장되어 있으니 나중에 재시도하세요."],
  fr: ['Les lignes sont trop rapprochées. Réessayez pour restaurer automatiquement la taille de l’image ; sinon utilisez un scan plus net.', 'Le temps de traitement est dépassé. Réessayez avec le fichier original.', 'Aucune partition exploitable n’a été produite. Réessayez ou utilisez un scan plus net.', 'Le service de reconnaissance ne peut pas démarrer. Réessayez plus tard.', 'Le fichier original est conservé. Réessayez sans nouvel envoi. Les tentatives échouées ou annulées libèrent les crédits ou essais réservés. Vérifiez le résultat avant de choisir un export payant.', "L’espace de stockage temporaire du serveur est indisponible. Votre original est conservé ; réessayez plus tard."],
  es: ['Las líneas están demasiado juntas. Reintente para recuperar automáticamente el tamaño de la imagen; si falla, use un escaneo más claro.', 'Se agotó el tiempo de procesamiento. Reintente con el archivo original.', 'No se produjo una partitura utilizable. Reintente o use un escaneo más claro.', 'El servicio de reconocimiento no puede ejecutarse. Reintente más tarde.', 'Se conserva el archivo original. Reintente sin volver a subirlo. Los intentos fallidos o cancelados liberan los créditos o usos reservados. Revise el resultado antes de elegir una exportación de pago.', "El almacenamiento temporal del servidor no está disponible. El original está guardado; reinténtalo más tarde."],
  de: ['Die Notenlinien liegen zu eng zusammen. Ein erneuter Versuch stellt die Bildgröße automatisch wieder her. Bei weiterem Fehlschlag nutzen Sie einen klareren Scan.', 'Das Zeitlimit wurde erreicht. Versuchen Sie es mit der Originaldatei erneut.', 'Es wurde keine verwendbare Partitur erstellt. Versuchen Sie es erneut oder nutzen Sie einen klareren Scan.', 'Der Erkennungsdienst kann nicht starten. Versuchen Sie es später erneut.', 'Die Originaldatei ist gespeichert. Ein erneuter Upload ist nicht nötig. Fehlgeschlagene oder abgebrochene Versuche geben reservierte Credits oder Versuche frei. Prüfen Sie das Ergebnis vor einem kostenpflichtigen Export.', "Der temporäre Serverspeicher ist nicht verfügbar. Ihr Original ist gespeichert. Versuchen Sie es später erneut."],
  ru: ['Нотные линии слишком близко. Повторная попытка автоматически восстановит размер изображения. При повторном сбое используйте более чёткий скан.', 'Достигнут лимит времени обработки. Повторите попытку с исходным файлом.', 'Не удалось получить пригодную партитуру. Повторите попытку или используйте более чёткий скан.', 'Сервис распознавания не запускается. Повторите попытку позже.', 'Исходный файл сохранён. Повторная загрузка не нужна. Неудачные или отменённые попытки освобождают зарезервированные кредиты или попытки. Проверьте результат перед выбором платного экспорта.', "Временное хранилище сервера недоступно. Оригинал сохранён. Повторите попытку позже."],
};

export function getScoreImportRecoveryMessages(locale: SupportedLocale, error: string | null | undefined) {
  const copy = recoveryDetails[locale];
  const detail = error ?? '';
  const index = /storage capacity.*unavailable|STORAGE_CAPACITY_REACHED/iu.test(detail) ? 5 :
    /too low interline|low.resolution/iu.test(detail) ? 0 :
    /time.?out|timed out|budget.*exhaust|execution budget/iu.test(detail) ? 1 :
    /not configured|could not start|missing from storage|adapter.*missing/iu.test(detail) ? 3 : 2;
  return { reason: copy[index], recovery: copy[4] };
}

const keys = ["processing", "wait", "failed", "recovery", "review", "newFile"] as const;
const messages: Record<SupportedLocale, readonly string[]> = {
  en: ["Recognizing your score", "Wait for recognition, then review and confirm the score. Transposition, playback and export become available after confirmation. This page updates automatically.", "Recognition did not finish", "Try again, or choose a clearer scan. Failed recognition does not use your free score allowance.", "Review and confirm the recognized score before transposing it.", "Choose another file"],
  "zh-CN": ["正在识别乐谱", "请等待识别完成，再检查并确认乐谱。确认后即可移调、播放和导出。此页面会自动更新。", "乐谱识别未完成", "可以重试，或上传更清晰的扫描件。识别失败不消耗免费乐谱名额。", "请先检查并确认识别结果，再进行移调。", "选择其他文件"],
  "zh-TW": ["正在辨識樂譜", "請等待辨識完成，再檢查並確認樂譜。確認後即可移調、播放和匯出。此頁面會自動更新。", "樂譜辨識未完成", "可以重試，或上傳更清晰的掃描檔。辨識失敗不會消耗免費樂譜名額。", "請先檢查並確認辨識結果，再進行移調。", "選擇其他檔案"],
  fr: ["Reconnaissance de votre partition", "Attendez la fin de la reconnaissance, puis vérifiez et confirmez la partition. La transposition, la lecture et l’export seront alors disponibles. Cette page s’actualise automatiquement.", "La reconnaissance n’a pas abouti", "Réessayez ou choisissez un scan plus net. Un échec ne consomme pas votre partition gratuite.", "Vérifiez et confirmez la partition reconnue avant de la transposer.", "Choisir un autre fichier"],
  de: ["Ihre Partitur wird erkannt", "Warten Sie auf die Erkennung und prüfen und bestätigen Sie danach die Partitur. Anschließend sind Transposition, Wiedergabe und Export verfügbar. Diese Seite aktualisiert sich automatisch.", "Die Erkennung wurde nicht abgeschlossen", "Versuchen Sie es erneut oder wählen Sie einen klareren Scan. Ein Fehlschlag verbraucht Ihre kostenlose Partitur nicht.", "Prüfen und bestätigen Sie die erkannte Partitur vor dem Transponieren.", "Andere Datei wählen"],
  es: ["Reconociendo la partitura", "Espere al reconocimiento y después revise y confirme la partitura. Entonces podrá transportar, reproducir y exportar. Esta página se actualiza automáticamente.", "El reconocimiento no se completó", "Reintente o elija un escaneo más claro. Un fallo no consume su partitura gratuita.", "Revise y confirme la partitura reconocida antes de transportarla.", "Elegir otro archivo"],
  ja: ["楽譜を認識しています", "認識が終わったら楽譜を確認して確定してください。その後、移調・再生・書き出しが使えます。このページは自動更新されます。", "楽譜の認識が完了しませんでした", "再試行するか、より鮮明なスキャンを選んでください。認識に失敗しても無料楽譜の枠は消費しません。", "移調する前に認識結果を確認して確定してください。", "別のファイルを選択"],
  ko: ["악보를 인식하고 있습니다", "인식이 끝나면 악보를 검토하고 확정하세요. 이후 조옮김, 재생, 내보내기를 사용할 수 있습니다. 이 페이지는 자동으로 갱신됩니다.", "악보 인식을 완료하지 못했습니다", "다시 시도하거나 더 선명한 스캔을 선택하세요. 인식 실패는 무료 악보 횟수를 차감하지 않습니다.", "조옮김 전에 인식된 악보를 검토하고 확정하세요.", "다른 파일 선택"],
  ru: ["Распознавание партитуры", "Дождитесь распознавания, затем проверьте и подтвердите партитуру. После этого будут доступны транспонирование, воспроизведение и экспорт. Страница обновляется автоматически.", "Распознавание не завершено", "Повторите попытку или выберите более чёткий скан. Неудачная попытка не расходует бесплатную партитуру.", "Проверьте и подтвердите распознанную партитуру перед транспонированием.", "Выбрать другой файл"],
};

export function getScoreReadinessMessages(locale: SupportedLocale) {
  return Object.fromEntries(keys.map((key, index) => [key, messages[locale][index]])) as Record<typeof keys[number], string>;
}
