export const enEsPricingCopy = {
  en: {
    title: "Pricing: one-time access or subscription", description: "Start with one free score project. Compare Starter and Converter Pro, with monthly or annual access. All prices are in US dollars (USD).", home: "Home", pricing: "Pricing", freeTitle: "Start free, with no payment card", freeBody: "Create one complete project from a multi-page PDF or score image. Your free project includes 25 credits each month and 50 MB of storage. Use the available tools to edit, transpose, play and export your score.", freeAction: "Create a free score project", oneTimeTitle: "Buy one month or one year of access", subscriptionTitle: "Choose a monthly or annual subscription", oneTimeLabel: "One payment", subscriptionLabel: "Recurring payment", creditTitle: "When are credits used?", creditBody: "Credits are reserved when a job is created; they are automatically returned if it fails or is cancelled. Viewing, playback and unsent basic edits do not use credits. Monthly credits reset at the start of each UTC calendar month and do not roll over.", review: "Review recognized notes and rhythms before using the result. Source quality and complex notation may require corrections.", faqTitle: "Questions about purchasing and access", terms: "Terms of service", support: "Contact support",
    faqs: [
      { question: "How does a one-time purchase differ from a subscription?", answer: "A one-time purchase provides the selected plan for one month or one year without automatic renewal. A subscription renews at the chosen interval until canceled. The selected plan has the same tools and monthly limits with either purchase type." },
      { question: "Does annual access provide all credits at once?", answer: "No. Starter provides 50 credits per month and Converter Pro provides 200 credits per month. Annual access still has a monthly allowance, and unused credits do not roll over." },
      { question: "Which currency will I pay in?", answer: "Prices are in US dollars (USD). The payment provider shows the total and any applicable taxes before you confirm the purchase. Your bank may charge currency conversion fees." },
      { question: "What happens when access ends?", answer: "One-time access expires without another charge. Buying the same plan tier again extends access. For a subscription, you can stop future renewals in Billing. Paid access normally remains until the end of the paid period, subject to refunds and the terms of service." },
      { question: "How can I get help with a payment?", answer: "Contact support with your order reference. If you have paid but cannot access your plan, do not pay again before the order is checked. Do not send passwords or complete activation codes." },
    ],
  },
  es: {
    title: "Precios: compra única o suscripción", description: "Empieza con un proyecto de partitura gratuito. Compara Starter y Converter Pro con acceso mensual o anual. Todos los precios están en dólares estadounidenses (USD).", home: "Inicio", pricing: "Precios", freeTitle: "Empieza gratis, sin tarjeta de pago", freeBody: "Crea un proyecto completo a partir de un PDF de varias páginas o una imagen de partitura. Incluye 25 créditos al mes y 50 MB de almacenamiento. Usa las herramientas disponibles para editar, transponer, reproducir y exportar tu partitura.", freeAction: "Crear un proyecto gratuito", oneTimeTitle: "Compra un mes o un año de acceso", subscriptionTitle: "Elige una suscripción mensual o anual", oneTimeLabel: "Un solo pago", subscriptionLabel: "Pago recurrente", creditTitle: "¿Cuándo se consumen los créditos?", creditBody: "Los créditos se reservan al crear una tarea; se devuelven automáticamente si falla o se cancela. Consultar, reproducir y editar sin enviar cambios no consume créditos. Los créditos mensuales se restablecen al comienzo de cada mes natural según UTC y no se acumulan.", review: "Revisa las notas y el ritmo reconocidos antes de usar el resultado. La calidad de la fuente y las partituras complejas pueden requerir correcciones.", faqTitle: "Preguntas sobre la compra y el acceso", terms: "Condiciones del servicio", support: "Contactar con soporte",
    faqs: [
      { question: "¿Qué diferencia hay entre una compra única y una suscripción?", answer: "La compra única proporciona el plan elegido durante un mes o un año sin renovación automática. La suscripción se renueva con la periodicidad elegida hasta que la canceles. Ambas modalidades tienen las mismas herramientas y límites mensuales del plan seleccionado." },
      { question: "¿El acceso anual incluye todos los créditos de una vez?", answer: "No. Starter incluye 50 créditos al mes y Converter Pro, 200 créditos al mes. El acceso anual mantiene la asignación mensual; los créditos no utilizados no se acumulan." },
      { question: "¿En qué moneda se realiza el pago?", answer: "Los precios están en dólares estadounidenses (USD). El proveedor muestra el importe total y los impuestos aplicables antes de confirmar la compra. Tu banco puede cobrar una comisión por cambio de moneda." },
      { question: "¿Qué ocurre al finalizar el acceso?", answer: "La compra única finaliza sin nuevos cargos. Otra compra del mismo nivel de plan amplía el acceso. Si tienes una suscripción, puedes detener futuras renovaciones en Facturación. Normalmente conservas el acceso hasta el final del periodo pagado, sujeto a los reembolsos y las condiciones del servicio." },
      { question: "¿Cómo puedo obtener ayuda con un pago?", answer: "Contacta con soporte e indica la referencia del pedido. Si ya has pagado pero no tienes acceso, espera a que se revise el pedido antes de volver a pagar. No envíes contraseñas ni códigos de activación completos." },
    ],
  },
} as const;
