import type { SupportedLocale } from "@score/i18n";

type Copy = { name: string; once: string; action: string; body: string; benefits: string[]; remaining: string; unused: string; open: string; paid: string };
const catalog: Record<SupportedLocale, Copy> = {
  en: { name: "One Score Pass", once: "One-time payment · No subscription", action: "Process one score", body: "One score to finish? Pay once and make it playable, editable and ready to share.", benefits: ["1 new PDF or image score · Up to 5 pages", "10 processing credits for this score · No expiry", "Edit, transpose, play and export your score", "Recognition and rendered exports use credits; failed jobs return them", "Uses your account’s existing storage allowance"], remaining: "Processing credits remaining", unused: "Ready for your next score", open: "Open score", paid: "Your One Score Pass is ready. Upload a PDF or image to start." },
  "zh-CN": { name: "单曲处理包", once: "一次付费 · 无订阅", action: "处理一首乐谱", body: "只想处理这一首？一次付费，让乐谱可以编辑、移调、播放和导出。", benefits: ["1 首新的 PDF 或图片乐谱 · 最多 5 页", "这首乐谱专属 10 个处理积分 · 不过期", "支持编辑、移调、播放和导出", "识别、渲染导出使用积分；失败自动退回", "使用账户现有存储额度"], remaining: "剩余处理积分", unused: "可用于下一首乐谱", open: "打开乐谱", paid: "单曲处理包已到账，上传 PDF 或图片即可开始。" },
  "zh-TW": { name: "單曲處理包", once: "一次付費 · 無訂閱", action: "處理一首樂譜", body: "只想處理這一首？一次付費，讓樂譜可以編輯、移調、播放和匯出。", benefits: ["1 首新的 PDF 或圖片樂譜 · 最多 5 頁", "這首樂譜專屬 10 個處理點數 · 不過期", "支援編輯、移調、播放和匯出", "辨識、渲染匯出使用點數；失敗自動退回", "使用帳戶現有儲存額度"], remaining: "剩餘處理點數", unused: "可用於下一首樂譜", open: "開啟樂譜", paid: "單曲處理包已入帳，上傳 PDF 或圖片即可開始。" },
  ja: { name: "1曲パス", once: "1回払い · 定期購入なし", action: "1曲を処理する", body: "この1曲だけ仕上げたい方へ。一度の支払いで、楽譜を編集・移調・再生・書き出しできます。", benefits: ["新規PDF・画像の楽譜1曲 · 最大5ページ", "この楽譜専用の処理クレジット10回分 · 有効期限なし", "楽譜の編集・移調・再生・書き出し", "認識とレンダリング書き出しで消費。失敗時は返還", "アカウントの既存ストレージ容量を使用"], remaining: "残り処理クレジット", unused: "次の楽譜に利用可能", open: "楽譜を開く", paid: "1曲パスが利用可能です。PDFまたは画像をアップロードしてください。" },
  ko: { name: "한 곡 이용권", once: "일회성 결제 · 구독 없음", action: "악보 한 곡 처리", body: "한 곡만 완성하고 싶으신가요? 한 번 결제로 편집, 조옮김, 재생, 내보내기를 이용하세요.", benefits: ["새 PDF 또는 이미지 악보 1곡 · 최대 5페이지", "해당 악보 전용 처리 크레딧 10개 · 유효기간 없음", "악보 편집, 조옮김, 재생 및 내보내기", "인식 및 렌더링 내보내기 시 차감, 실패 시 반환", "계정의 기존 저장 공간 한도 사용"], remaining: "남은 처리 크레딧", unused: "다음 악보에 사용 가능", open: "악보 열기", paid: "한 곡 이용권이 준비되었습니다. PDF 또는 이미지를 업로드하세요." },
  fr: { name: "Pass une partition", once: "Paiement unique · Sans abonnement", action: "Traiter une partition", body: "Une seule partition à terminer ? Payez une fois pour la modifier, la transposer, l’écouter et l’exporter.", benefits: ["1 nouvelle partition PDF ou image · 5 pages maximum", "10 crédits réservés à cette partition · Sans expiration", "Modification, transposition, lecture et export", "Reconnaissance et exports rendus déduits ; crédits restitués en cas d’échec", "Utilise le quota de stockage actuel du compte"], remaining: "Crédits de traitement restants", unused: "Disponible pour votre prochaine partition", open: "Ouvrir la partition", paid: "Votre pass est prêt. Importez un PDF ou une image pour commencer." },
  es: { name: "Pase para una partitura", once: "Pago único · Sin suscripción", action: "Procesar una partitura", body: "¿Solo necesitas terminar una partitura? Paga una vez para editarla, transponerla, escucharla y exportarla.", benefits: ["1 nueva partitura PDF o imagen · Hasta 5 páginas", "10 créditos exclusivos para esta partitura · Sin caducidad", "Edición, transposición, reproducción y exportación", "Reconocimiento y exportaciones renderizadas consumen créditos; los fallos los devuelven", "Usa el espacio de almacenamiento actual de tu cuenta"], remaining: "Créditos de procesamiento restantes", unused: "Disponible para tu próxima partitura", open: "Abrir partitura", paid: "Tu pase está listo. Sube un PDF o una imagen para comenzar." },
  de: { name: "Einzelpartitur-Pass", once: "Einmalzahlung · Kein Abo", action: "Eine Partitur bearbeiten", body: "Nur eine Partitur fertigstellen? Einmal bezahlen, bearbeiten, transponieren, anhören und exportieren.", benefits: ["1 neue Partitur als PDF oder Bild · Bis zu 5 Seiten", "10 Verarbeitungsguthaben für diese Partitur · Ohne Ablaufdatum", "Noten bearbeiten, transponieren, abspielen und exportieren", "Erkennung und gerenderte Exporte verbrauchen Guthaben; bei Fehlern wird es zurückgegeben", "Nutzt das vorhandene Speicherkontingent des Kontos"], remaining: "Verbleibendes Verarbeitungsguthaben", unused: "Für Ihre nächste Partitur verfügbar", open: "Partitur öffnen", paid: "Ihr Pass ist bereit. Laden Sie eine PDF- oder Bilddatei hoch." },
  ru: { name: "Пакет для одной партитуры", once: "Разовая оплата · Без подписки", action: "Обработать партитуру", body: "Нужно закончить только одну партитуру? Оплатите один раз, чтобы редактировать, транспонировать, слушать и экспортировать её.", benefits: ["1 новая партитура в PDF или изображении · До 5 страниц", "10 кредитов только для этой партитуры · Без срока действия", "Редактирование, транспонирование, воспроизведение и экспорт", "Распознавание и рендеринг экспорта расходуют кредиты; при ошибке они возвращаются", "Используется текущая квота хранения аккаунта"], remaining: "Осталось кредитов обработки", unused: "Доступен для следующей партитуры", open: "Открыть партитуру", paid: "Пакет готов к использованию. Загрузите PDF или изображение." },
};
export const getSingleScorePassCopy = (locale: SupportedLocale): Copy => catalog[locale];
