import type { StaticMarketingLocalization } from "../types";

export const deStaticMarketing = {
  openGraphLocale: "de_DE",
  homeBreadcrumb: "Startseite",
  about: {
    metadata: { title: "Über den Online-Notenarbeitsbereich, Kontakt und Hilfe | ScoreTransposer", description: "Erfahren Sie mehr über den MusicXML-Arbeitsbereich für Scanprüfung, Jianpu-Konvertierung, Transposition, Bearbeitung, Wiedergabe, Export, Unterricht, Zugang und Support.", keywords: ["Notensystem zu Jianpu", "Noten-PDF zu Zahlennotation", "Jianpu-Konverter", "Notenerkennung", "Online-Noteneditor"], socialImageAlt: "ScoreTransposer-Noteneditor mit englischer Benutzeroberfläche" },
    registrationLabel: "Registrierung",
    hero: { eyebrow: "Über uns / Kontakt / Hilfe", title: "Über ScoreTransposer: Zweck, Zielgruppe und Zugang", body: "ScoreTransposer ist ein Online-Notenarbeitsbereich auf Basis von MusicXML und Score JSON. Die Website erklärt die Abläufe; die App übernimmt Import, Korrektur, Transposition, Übung, Unterricht und Export.", checkoutAction: "Kaufweg ansehen", appAction: "App öffnen", supportAction: "Support kontaktieren" },
    position: { eyebrow: "Produktposition", title: "Vom Notensystem-zu-Jianpu-Einstieg zum vollständigen strukturierten Notenarbeitsbereich", body: "Prüfen Sie Dateitypen, kostenlosen Umfang und Erkennungsgrenzen, bevor Sie die App öffnen. Erkannte Kandidaten sollten immer von Menschen kontrolliert werden.", steps: [["01", "Aus einem Scan bearbeitbare Noten erstellen", "Laden Sie ein Notensystem-PDF oder Bild hoch, prüfen Sie den Erkennungskandidaten und arbeiten Sie im selben Notenprojekt weiter."], ["02", "Zuerst den Umfang verstehen", "Die Erkennung erzeugt einen Kandidaten, der Korrekturen benötigen kann. Ein kostenloses Konto kann aus einem vollständigen mehrseitigen PDF oder Notenbild ein lebenslanges Projekt erstellen."], ["03", "In der App weiterarbeiten", "Melden Sie sich an, um Kandidaten hochzuladen und zu prüfen. Das kostenlose Projekt enthält die aktuell verfügbaren Werkzeuge für Bearbeitung, Wiedergabe, Transposition, Jianpu, Versionen, Teilen und Export; Bezahlpläne erhöhen Verarbeitung und Speicher."]] },
    audience: { eyebrow: "Geeignet für", title: "Für wen ScoreTransposer gedacht ist", metrics: [["Unterricht", "Materialvorbereitung", "Für Lehrkräfte und Musikschulen, die aus bestehenden Noten-PDFs schneller Jianpu-Unterlagen erstellen möchten."], ["Probe", "Kulturübergreifend", "Für Gruppen, die mit einer Quelle sowohl Notensystem- als auch Jianpu-Lesende versorgen."], ["Produktion", "Prüfbare Entwürfe", "Für Arrangeure, Notensetzer und Verlage, die Automatisierung mit menschlicher Kontrolle kombinieren."]] },
    support: { eyebrow: "Kontakt und Support", title: "Support für den Zahlennotations-Konverter und den Zugang", body: "Nutzen Sie das Formular bei Fragen zu Konto, Aktivierung, Upload, Erkennung oder Download.", steps: [["A", "Fragen vor Kauf und Zahlung", "Klären Sie Zugangsweg, Aktivierungscodes, Zahlungsrückleitung oder Funktionsumfang vor dem Kauf."], ["B", "Fragen nach Kauf und zu Dateien", "Support hilft auch bei Einlösung, Bestellprüfung, unerwarteten Upload-Ergebnissen und manuellen Löschanfragen."], ["C", "Hilfreiche Angaben", "E-Mail, Aktivierungscode, Zahlungsbild, Kaufzeit oder Dateiname beschleunigen die Prüfung."]], operatorAriaLabel: "Öffentliche Betreiberinformationen", serviceBrandLabel: "Servicemarke", canonicalWebsitePrefix: "Offizielle Website", customerSupportLabel: "Kundensupport", customerSupportBody: "Dieser Kontakt bearbeitet Konto-, Datei-, Datenschutz-, Urheberrechts- und Bestellfragen.", legalOperatorLabel: "Rechtlicher Betreiber", legalOperatorFallback: "Dieser Name stammt aus der öffentlichen Produktionskonfiguration.", requestAction: "Supportanfrage öffnen", privacyAction: "Datenschutz öffnen", termsAction: "Nutzungsbedingungen öffnen" },
    commerce: { eyebrow: "Zugangsweg", availableTitle: "Zusammenspiel von Website, Zahlung und Aktivierungscodes", pendingTitle: "Checkout öffnet nach Prüfung der Produktionstransaktionen", availableStatus: "Internationaler Checkout", pendingStatus: "Prüfung ausstehend", availableBody: "Internationale Besucher können den gehosteten Checkout nutzen; nach erfolgreicher Zahlung wird das Abonnement direkt dem registrierten Konto zugeordnet.", pendingBody: "Derzeit wird nichts berechnet. Der Zugang bleibt aus, bis Erfolg, Fehler, Erstattung und Berechtigungsvergabe geprüft sind.", mainlandStatus: "Codes für Festlandchina", mainlandAvailableBody: "Kunden in Festlandchina können über einen geprüften Kanal einen Aktivierungscode kaufen und in der App einlösen.", mainlandPendingBody: "Auch die Codeverteilung bleibt bis zur Prüfung von Bestellung und Berechtigung geschlossen.", registerAction: "Konto erstellen", checkoutAction: "Zum Checkout" },
    useCases: { eyebrow: "Anwendungsfälle", title: "Vorhandene Noten in einen strukturierten Ablauf überführen", body: "Ob Noten-PDF, Bild oder Jianpu: Prüfen Sie den Import, bevor Sie bearbeiten, transponieren, üben oder exportieren.", items: [["Sie haben ein Notensystem-PDF oder Bild", "Die Erkennung erstellt einen strukturierten Kandidaten, den Sie prüfen und weiterverarbeiten können."], ["Sie arbeiten mit Notensystem und Jianpu", "Eine strukturierte Partitur dient für Anzeige, Jianpu-Konvertierung, Transposition, Übung und Export."], ["Sie können automatische Erkennung prüfen", "Komplexe Rhythmen, schwache Scans und mehrstimmige Noten können Korrekturen brauchen; Kandidaten und Diagnosen bleiben prüfbar."]] },
    startingPoints: { eyebrow: "Häufige Ausgangspunkte", title: "Den passenden Einstieg für das Quellmaterial wählen", metrics: [["PDF oder Bild", "Notenerkennung", "Laden Sie ein klares, gerades, unbeschnittenes vollständiges mehrseitiges PDF oder Notenbild hoch und prüfen Sie den Kandidaten."], ["Notensystem und Jianpu", "Konvertierung", "Prüfen Sie die strukturierte Partitur vor Jianpu-Konvertierung, Transposition, Wiedergabe oder Übung."], ["Notationsdatei oder Sicherung", "Weiter bearbeiten", "Importieren Sie MusicXML, MIDI oder eine Sicherung direkt, wenn das Format im aktuellen Plan enthalten ist."]] },
    learnMore: { eyebrow: "Mehr erfahren", title: "Weiter zu Datenschutz, Bedingungen und Zugang", body: "Nach Produktposition und Support folgen meist Datenschutz, Nutzungsbedingungen und Zugangsweg.", privacyAction: "Datenschutz", termsAction: "Nutzungsbedingungen", checkoutAction: "Kaufweg ansehen" },
    next: { eyebrow: "Nächster Schritt", title: "Ein vollständiges Notenprojekt kostenlos erstellen oder die Hilfe lesen.", body: "Kehren Sie zur Startseite zurück, öffnen Sie die App für ein vollständiges kostenloses Projekt oder lesen Sie Datenschutz und Bedingungen zu den Grenzen des Dienstes.", homeAction: "Zur Startseite", appAction: "App öffnen" },
  },
  faq: {
    metadata: { title: "FAQ zu Notenscan, Jianpu, Transposition und Export | ScoreTransposer", description: "Häufige Fragen zu Scanprüfung, Notensystem-Jianpu-Konvertierung, Transposition, Bearbeitung, Wiedergabe, Export, Kauf und Support.", keywords: ["Notenscan FAQ", "Notensystem zu Jianpu", "OMR-Kandidat", "Online-Noteneditor", "ScoreTransposer Support"], socialImageAlt: "ScoreTransposer-Notenvorschau mit englischer Benutzeroberfläche" },
    hero: { eyebrow: "FAQ / Produkt und Support", title: "Fragen zu Scan, Bearbeitung, Konvertierung und Zugang", body: "Prüfen Sie unterstützte Eingaben, Erkennungsgrenzen, bearbeitbare Ergebnisse, Jianpu, Kontozugang und Support, bevor Sie fortfahren.", checkoutAction: "Kaufweg ansehen", supportPageAction: "Support öffnen", contactAction: "Support kontaktieren" },
    groups: [
      { title: "Kauf und Zugang", items: [["Was ist heute tatsächlich verfügbar?", "Registrierte Nutzer können aus einem vollständigen mehrseitigen Noten-PDF oder Bild ein lebenslanges kostenloses Projekt mit aktuellen Korrektur-, Wiedergabe-, Transpositions-, Jianpu-, Versions-, Freigabe- und Exportwerkzeugen erstellen. Bezahlpläne erhöhen die Kapazität."], { question: "Nutzen internationale Kunden und Kunden in Festlandchina denselben Weg?", availableAnswer: "Nicht ganz. Internationale Kunden zahlen direkt online; Kunden in Festlandchina können auch Codevertrieb und Einlösung in der App nutzen.", pendingAnswer: "Der Online-Checkout ist noch geschlossen. Er öffnet nach Prüfung von Paddle-Produktionszahlungen, Erstattungen und Berechtigungen; das vollständige kostenlose Projekt bleibt verfügbar." }, { question: "Was erhalte ich nach der Zahlung?", availableAnswer: "Nach erfolgreicher Zahlung wird das Abonnement direkt mit dem registrierten Konto verknüpft; ein Aktivierungscode ist nicht nötig.", pendingAnswer: "Derzeit wird nichts berechnet. Nach Öffnung laufen Bestellbestätigung und Kontoberechtigung automatisch über den geprüften Produktionsablauf." }] },
      { title: "Uploads und Ergebnisse", items: [["Welche Eingabeformate werden aktuell unterstützt?", "Der kostenlose Einstieg akzeptiert ein vollständiges mehrseitiges PDF oder ein PNG-, JPG-, WebP- oder TIFF-Notenbild. Starter und Converter Pro erlauben mehr Projekte und aktuell verfügbare MusicXML/MXL-, MIDI-, strukturierte Jianpu- und Score-JSON-Importe. Audiotranskription bleibt experimentell."], ["Warum wird die Erkennung als Kandidat markiert?", "OMR kann Tonhöhe, Dauer, Stimmen oder Taktstruktur falsch lesen. Das Ergebnis bleibt daher ein Kandidat zur menschlichen Prüfung mit Konfidenz und Warnungen und wird nicht als publikationsreif ausgegeben."], ["Was tun bei fehlgeschlagenem Upload oder Download?", "Bewahren Sie Dateinamen, Jobzeit und Fehlerbild auf und senden Sie das Supportformular, damit der betroffene Job schneller gefunden wird."]] },
      { title: "Support und Konten", items: [["Wie behandle ich Zahlungs- oder Aktivierungsprobleme?", "Nutzen Sie zuerst das Formular und wählen Sie Zahlung oder Aktivierung. Das Team kann die Anfrage über die Referenznummer verfolgen."], ["Was passiert nach dem Absenden?", "Das Formular sendet an die API, erstellt eine gespeicherte Anfrage und schickt automatisch eine Bestätigung an die Kontaktadresse. Ohne eingerichteten E-Mail-Dienst protokolliert die API weiterhin eine Testvorschau."], ["Wo vergleiche ich Notensystem- und Jianpu-Konvertierung?", "Öffnen Sie den Zahlennotations-Konverter und wählen Sie Notensystem zu Jianpu oder Jianpu zu Notensystem. Beide halten das Ergebnis in einem bearbeitbaren strukturierten Projekt."]] },
    ],
    workflow: { eyebrow: "Arbeitsablauf wählen", title: "Mit der aktuellen Aufgabe beginnen", body: "Scan, bidirektionale Zahlennotation und Online-Bearbeitung haben eigene Anleitungen für klare Ein- und Ausgaben.", metrics: [["Scan", "PDF und Bilder", "Einen prüfbaren MusicXML-Kandidaten erstellen."], ["Notation", "Notensystem ⇄ Jianpu", "Eine eindeutige Richtung wählen."], ["Weiter", "Bearbeiten und transponieren", "Akzeptierte Noten korrigieren, abspielen, transponieren und exportieren."]], scannerAction: "Notenscanner öffnen", converterAction: "Jianpu-Konverter öffnen" },
    verification: { eyebrow: "Weiter prüfen", title: "Keine Antwort? Anleitungen lesen oder Support kontaktieren", steps: [["01", "Zuerst Produktumfang prüfen", "Bestätigen Sie, dass Erkennung, Jianpu und strukturierter Ablauf zur Aufgabe passen."], ["02", "Checkout und Support prüfen", "Verstehen Sie vor der Zahlung die tatsächlichen Wege für checkout, activation und support."], ["03", "Dann Zugang wählen", "Gehen Sie nur zum Checkout, wenn der aktuelle Umfang zum Anwendungsfall passt."]] },
    next: { eyebrow: "Nächster Schritt", title: "Noch unsicher? Weiter zu Support, Über uns oder Checkout", supportAction: "Support öffnen", requestAction: "Anfrage senden", aboutAction: "Über uns", checkoutAction: "Checkout" },
    related: { eyebrow: "Weitere Hilfe", title: "Support, Datenschutz und Bedingungen lesen", body: "Diese Seiten bieten Kontakte, Informationen zur Datenverarbeitung und Dienstgrenzen.", privacyAction: "Datenschutz", termsAction: "Bedingungen", supportAction: "Supportseite" },
  },
  readingGuide: {
    metadata: { title: "Noten lesen lernen: Noten, Rhythmus und Symbole | ScoreTransposer", description: "Lernen Sie Noten über Notensystem, Schlüssel und Tonhöhen zu lesen, verstehen Sie Notenwerte, Takt, Tonart und Symbole und üben Sie online.", keywords: ["Noten lesen lernen", "Notensystem Anfänger", "Notenwerte", "Notenschlüssel", "Musiksymbole"], socialImageAlt: "Notenvorschau mit englischer Oberfläche zum Lernen von Noten und Symbolen" },
    eyebrow: "Notenlesen für Anfänger", title: "Noten lesen: mit den Tönen im Notensystem beginnen", intro: "Sie müssen nicht alle Symbole auf einmal auswendig lernen. Beginnen Sie mit Schlüssel und Referenzton und lesen Sie Position und Rhythmus Schritt für Schritt. Schwierige Noten lassen sich im Online-Editor abspielen, verlangsamen und taktweise prüfen.", basicsEyebrow: "Grundlagen", summaryTitle: "Mit vier Elementen beginnen", summaryBody: "Die meisten Anfängerpartituren werden verständlich, wenn Position, Schlüssel, Rhythmus und Tonart getrennt betrachtet werden.", concepts: [["Notensystem und Tonhöhe", "Fünf Linien und vier Zwischenräume stehen für Tonhöhen; höher platzierte Noten klingen meist höher."], ["Schlüssel", "Der Violinschlüssel deckt oft hohe, der Bassschlüssel tiefe Töne und die linke Klavierhand ab."], ["Notenwerte und Rhythmus", "Ganze, halbe, Viertel- und Achtelnoten zeigen die Dauer eines Klangs."], ["Takt- und Tonartangabe", "Die Taktangabe ordnet Schläge; die Tonart legt wiederkehrende Kreuze oder Bes fest."]],
    orderEyebrow: "Lesereihenfolge", stepsTitle: "Einen Takt in dieser Reihenfolge lesen", stepsBody: "Zuerst den Kontext bestimmen, dann Tonhöhe und Rhythmus verbinden und zuletzt Ausdruck ergänzen.", steps: [["Schlüssel und Tonart prüfen", "Lesen Sie links die Tonhöhenbezüge und wiederkehrenden Vorzeichen."], ["Noten im System erkennen", "Linien und Zwischenräume liefern die Tonnamen; Hilfslinien setzen das Muster nach oben und unten fort."], ["Jeden Notenwert zählen", "Verbinden Sie Notenform, Punkte, Bindebögen, Triolen und Pausen, damit der Takt aufgeht."], ["Versetzungszeichen anwenden", "Kreuz, Be oder Auflösungszeichen gilt gewöhnlich für folgende gleichnamige Töne im Takt."], ["Langsam spielen und prüfen", "Lesen Sie zunächst mit stabilem Puls und ergänzen Sie Dynamik, Artikulation und Tempo."]],
    symbolsEyebrow: "Notationssymbole", symbolsTitle: "Häufige Musiksymbole", symbolsBody: "Notenlesen verbindet Tonhöhe, Zeit und Ausdruck statt nur Tonnamen.", symbols: [["♯, ♭ und ♮", "Kreuz, Be und Auflösungszeichen verändern die notierte Tonhöhe."], ["Pausen", "Eine Pause ist gemessene Stille und Teil des Rhythmus."], ["Phrasierungs- und Haltebögen", "Der eine gruppiert eine Phrase, der andere verbindet die Dauer gleicher Tonhöhen."], ["p, f, Crescendo, Diminuendo", "Dynamikzeichen beschreiben Lautstärke und ihre Veränderung."]],
    practiceEyebrow: "Üben", practiceTitle: "Mit echten, bearbeitbaren Noten üben", practiceBody: "Öffnen oder laden Sie erlaubte Noten hoch, prüfen Sie jeden Erkennungskandidaten und bearbeiten, spielen, transponieren oder erzeugen Sie Jianpu im selben Projekt.", editAction: "Online-Noteneditor öffnen", scanAction: "PDF oder Notenbild scannen", playAction: "Online-Notenplayer verwenden", faqEyebrow: "FAQ", faqTitle: "Fragen zum Notenlesen", faqs: [["Muss ich alle Notenpositionen auswendig lernen?", "Nein. Lernen Sie einige Referenztöne im Violin- und Bassschlüssel und leiten Sie Nachbartöne schrittweise ab."], ["Warum hat Klaviermusik zwei Systeme?", "Klavier nutzt meist das große System: Violinschlüssel oben und Bassschlüssel unten, damit beide Hände zusammen gelesen werden."], ["Kann ich gescannte Noten sofort verwenden?", "Prüfen Sie zuerst Tonhöhe, Rhythmus, Tonart und Takte. Optische Notenerkennung erstellt Kandidaten und garantiert bei komplexen Noten kein perfektes Ergebnis."]],
  },
  numberedNotation: {
    metadata: { title: "Konverter für Notensystem und Jianpu-Zahlennotation | ScoreTransposer", description: "Konvertieren Sie Notensystem zu Jianpu oder Jianpu zu Notensystem und bearbeiten, transponieren, spielen oder exportieren Sie dieselbe strukturierte Partitur.", keywords: ["Zahlennotation Konverter", "Notensystem zu Jianpu", "Jianpu zu Notensystem", "Ziffernnotation", "MusicXML Jianpu"], socialImageAlt: "Strukturierter Notensystem-Jianpu-Arbeitsbereich mit englischer Oberfläche" },
    eyebrow: "Bidirektionale Notationskonvertierung", title: "Konverter für Notensystem und Jianpu-Zahlennotation", intro: "Wählen Sie die Richtung. Beide Wege verwenden strukturiertes MusicXML und Score JSON, statt PDF-Pixel oder Bildtext als bearbeitbare Notation zu behandeln.", directionOneEyebrow: "Richtung eins", staffTitle: "Notensystem zu Jianpu", staffBody: "Strukturierte Noten in Zahlennotation mit Tonzentrum, Skalenstufen, Oktavpunkten, Dauer, Text und Akkordkontext umwandeln.", staffAction: "Notensystem zu Jianpu öffnen", directionTwoEyebrow: "Richtung zwei", jianpuTitle: "Jianpu zu Notensystem", jianpuBody: "Strukturiertes Jianpu eingeben und prüfbares, korrigierbares, exportierbares Notensystem, MusicXML und Score JSON erstellen.", jianpuAction: "Jianpu zu Notensystem öffnen", modelTitle: "Warum strukturierte Notation zählt", modelBody: "Das Ergebnis bleibt bearbeitbar, transponierbar, abspielbar und exportierbar, statt ein nicht korrigierbares flaches Bild zu werden.", limitsTitle: "Vor der Konvertierung", limitsBody: "Ein gescanntes PDF muss zuerst durch Erkennung und Korrektur. Der aktuelle Jianpu-zu-Notensystem-Weg erwartet eingegebenen oder eingefügten strukturierten Jianpu-Text.", faqEyebrow: "FAQ", faqTitle: "Fragen zur Zahlennotation", faqs: [["Kann ich Noten nach der Konvertierung bearbeiten?", "Ja. Das Ergebnis gelangt in das gemeinsame Score-JSON-Projekt, wo Tonhöhe, Rhythmus, Tonart und Takte korrigierbar bleiben."], ["Kann jedes gescannte Jianpu-Bild in Notensystem umgewandelt werden?", "Noch nicht. Der aktuelle Weg priorisiert strukturierten Jianpu-Text; beliebige Bilderkennung bleibt eine spätere Importfunktion."]],
  },
} as const satisfies StaticMarketingLocalization;
