import type { StaticMarketingLocalization } from "../types";

export const esStaticMarketing = {
  openGraphLocale: "es_ES",
  homeBreadcrumb: "Inicio",
  about: {
    metadata: { title: "Acerca del espacio de partituras, contacto y soporte | ScoreTransposer", description: "Conoce el espacio basado en MusicXML para revisar escaneos, convertir Jianpu, transponer, editar, reproducir, exportar y enseñar, además de las vías de acceso y soporte.", keywords: ["pentagrama a Jianpu", "PDF de partitura a notación numerada", "convertidor Jianpu", "reconocimiento de partituras", "editor de partituras online"], socialImageAlt: "Espacio de edición de partituras ScoreTransposer con interfaz en inglés" },
    registrationLabel: "Registro",
    hero: { eyebrow: "Acerca de / Contacto / Soporte", title: "Acerca de ScoreTransposer: qué es, para quién sirve y cómo acceder", body: "ScoreTransposer es un espacio online de partituras basado en MusicXML y Score JSON. El sitio explica cada flujo y la aplicación gestiona importación, corrección, transposición, práctica, enseñanza y exportación.", checkoutAction: "Ver vía de compra", appAction: "Abrir la aplicación", supportAction: "Contactar con soporte" },
    position: { eyebrow: "Posición del producto", title: "De la conversión pentagrama–Jianpu a un espacio completo de partitura estructurada", body: "Comprueba tipos de archivo, alcance gratuito y límites de reconocimiento antes de entrar en la aplicación. Las propuestas reconocidas siempre requieren revisión humana.", steps: [["01", "Crear una partitura editable desde un escaneo", "Sube un PDF de pentagrama o una imagen, revisa la propuesta reconocida y sigue trabajando en el mismo proyecto."], ["02", "Entender primero el alcance", "El reconocimiento produce una propuesta que puede necesitar correcciones. Una cuenta gratuita puede crear un proyecto vitalicio desde un PDF completo de varias páginas o una imagen de partitura."], ["03", "Continuar en la aplicación", "Inicia sesión para subir y revisar propuestas. El proyecto gratuito incluye las herramientas actuales de edición, reproducción, transposición, Jianpu, versiones, uso compartido y exportación; los planes de pago añaden capacidad de proceso y almacenamiento."]] },
    audience: { eyebrow: "Para quién", title: "A quién le conviene ScoreTransposer", metrics: [["Enseñanza", "Preparación de materiales", "Para docentes y academias que preparan material Jianpu desde PDF de pentagrama."], ["Ensayo", "Uso intercultural", "Para grupos que atienden a lectores de pentagrama y Jianpu desde una sola fuente."], ["Producción", "Propuestas revisables", "Para arreglistas, copistas y editores que aceptan automatización con revisión humana."]] },
    support: { eyebrow: "Contacto y soporte", title: "Cómo funciona el soporte del convertidor de notación numerada y el acceso", body: "Usa el formulario para dudas de cuenta, activación, subida, reconocimiento o descarga.", steps: [["A", "Preguntas antes de comprar o pagar", "Consulta la vía de acceso, códigos de activación, problemas de retorno del pago o alcance antes de comprar."], ["B", "Preguntas posteriores y sobre archivos", "Soporte también atiende canjes fallidos, comprobación de pedidos, subidas inesperadas o solicitudes de borrado manual."], ["C", "Qué incluir al contactar", "Correo, código, captura del pago, fecha de compra o nombre del archivo agilizan la revisión."]], operatorAriaLabel: "Información pública del operador", serviceBrandLabel: "Marca del servicio", canonicalWebsitePrefix: "Sitio oficial", customerSupportLabel: "Atención al cliente", customerSupportBody: "Este contacto gestiona cuentas, archivos, privacidad, derechos de autor y pedidos.", legalOperatorLabel: "Operador legal", legalOperatorFallback: "Este nombre procede de la configuración pública de producción.", requestAction: "Abrir solicitud", privacyAction: "Abrir política de privacidad", termsAction: "Abrir condiciones del servicio" },
    commerce: { eyebrow: "Vía comercial", availableTitle: "Cómo se coordinan sitio, pago y códigos de activación", pendingTitle: "El pago se abrirá tras validar transacciones de producción", availableStatus: "Pago internacional", pendingStatus: "Pendiente de validación", availableBody: "Los visitantes internacionales pueden usar el pago alojado; tras un pago correcto, la suscripción queda vinculada directamente a la cuenta registrada.", pendingBody: "Ahora no se cobra. La entrada seguirá desactivada hasta validar éxito, fallo, reembolso y asignación de derechos.", mainlandStatus: "Códigos para China continental", mainlandAvailableBody: "Los clientes de China continental pueden comprar un código por un canal verificado y canjearlo en la aplicación.", mainlandPendingBody: "La distribución de códigos también espera la validación de pedidos y derechos.", registerAction: "Crear cuenta", checkoutAction: "Ir al pago" },
    useCases: { eyebrow: "Casos de uso", title: "Lleva una partitura existente a un flujo estructurado", body: "Empieces con PDF de pentagrama, imagen o Jianpu, revisa el resultado importado antes de editar, transponer, practicar o exportar.", items: [["Ya tienes un PDF o imagen de pentagrama", "Usa el reconocimiento para crear una propuesta estructurada que puedas revisar y seguir trabajando."], ["Trabajas con pentagrama y notación numerada", "Una partitura estructurada sirve para ver pentagrama, convertir Jianpu, transponer, practicar y exportar."], ["Puedes revisar el reconocimiento automático", "Ritmos complejos, escaneos deficientes y varias partes pueden requerir corrección; propuestas y diagnósticos siguen disponibles."]] },
    startingPoints: { eyebrow: "Puntos de partida", title: "Elige la entrada adecuada para tu material", metrics: [["PDF o imagen", "Reconocimiento", "Sube un PDF completo de varias páginas o una imagen nítida, recta y sin recortes, y revisa la propuesta."], ["Pentagrama y Jianpu", "Conversión", "Revisa la partitura estructurada antes de convertir a Jianpu, transponer, reproducir o practicar."], ["Archivo de notación o copia", "Seguir editando", "Importa MusicXML, MIDI o una copia cuando ese formato esté incluido en el plan actual."]] },
    learnMore: { eyebrow: "Más información", title: "Continúa con privacidad, condiciones y acceso", body: "Después de conocer producto y soporte, revisa la política de privacidad, las condiciones y la vía de acceso.", privacyAction: "Política de privacidad", termsAction: "Condiciones", checkoutAction: "Ver vía de compra" },
    next: { eyebrow: "Siguiente paso", title: "Crea gratis un proyecto de partitura completo o consulta la ayuda.", body: "Vuelve al inicio para ver funciones, abre la aplicación para crear un proyecto gratuito completo o consulta privacidad y condiciones para conocer los límites.", homeAction: "Volver al inicio", appAction: "Abrir la aplicación" },
  },
  faq: {
    metadata: { title: "FAQ de escaneo, Jianpu, transposición y exportación | ScoreTransposer", description: "Preguntas frecuentes sobre escaneo y revisión, conversión pentagrama–Jianpu, transposición, edición, reproducción, exportación, compra y soporte.", keywords: ["FAQ escaneo de partituras", "pentagrama a Jianpu", "propuesta OMR", "editor de partituras online", "soporte ScoreTransposer"], socialImageAlt: "Vista de partitura ScoreTransposer con interfaz en inglés" },
    hero: { eyebrow: "FAQ / Producto y soporte", title: "Preguntas sobre escaneo, edición, conversión y acceso", body: "Comprueba entradas compatibles, límites de reconocimiento, resultados editables, Jianpu, acceso de cuenta y soporte antes de continuar.", checkoutAction: "Ver vía de compra", supportPageAction: "Abrir soporte", contactAction: "Contactar con soporte" },
    groups: [
      { title: "Compra y acceso", items: [["¿Qué está disponible realmente hoy?", "Un usuario registrado puede crear un proyecto gratuito vitalicio desde un PDF completo de varias páginas o una imagen de partitura, con las herramientas actuales de corrección, reproducción, transposición, Jianpu, versiones, uso compartido y exportación. Los planes de pago añaden capacidad."], { question: "¿Siguen la misma vía los usuarios internacionales y de China continental?", availableAnswer: "No exactamente. Los internacionales pagan online; en China continental también puede usarse la distribución de códigos y el canje en la aplicación.", pendingAnswer: "El pago online aún no está abierto. Se habilitará tras validar pagos Paddle de producción, reembolsos y derechos; el proyecto gratuito completo sigue disponible." }, { question: "¿Qué recibo tras pagar?", availableAnswer: "Tras un pago correcto, la suscripción se vincula directamente a la cuenta registrada y no hace falta canjear un código.", pendingAnswer: "Ahora no se cobra. Cuando abra el pago, la confirmación del pedido y los derechos de cuenta se entregarán automáticamente mediante el flujo de producción validado." }] },
      { title: "Subidas y resultados", items: [["¿Qué formatos de entrada se admiten ahora?", "La entrada gratuita admite un PDF completo de varias páginas o una imagen PNG, JPG, WebP o TIFF. Starter y Converter Pro añaden proyectos e importaciones actuales de MusicXML/MXL, MIDI, Jianpu estructurado y Score JSON. La transcripción de audio sigue siendo experimental."], ["¿Por qué el reconocimiento aparece como propuesta?", "OMR puede interpretar mal altura, duración, voces o estructura de compás. Por eso el resultado queda como propuesta para revisión humana, con confianza y avisos, sin fingir calidad de publicación."], ["¿Qué hago si falla la subida o descarga?", "Conserva nombre del archivo, hora del trabajo y captura del error, y envía el formulario para localizar antes la tarea afectada."]] },
      { title: "Soporte y cuentas", items: [["¿Cómo resuelvo problemas de pago o activación?", "Usa primero el formulario del sitio. Selecciona pago o activación y el equipo podrá seguir la solicitud mediante su referencia."], ["¿Qué ocurre al enviar el formulario?", "El formulario llama a la API, crea una solicitud almacenada y envía automáticamente una confirmación al correo de contacto. Sin correo transaccional configurado, la API guarda una vista previa de prueba."], ["¿Dónde comparo las conversiones de pentagrama y Jianpu?", "Abre el convertidor de notación numerada y elige pentagrama a Jianpu o Jianpu a pentagrama. Ambas vías guardan el resultado en un proyecto estructurado editable."]] },
    ],
    workflow: { eyebrow: "Elegir un flujo", title: "Empieza por la tarea que necesitas", body: "Escaneo, conversión bidireccional y edición online tienen guías separadas para aclarar entradas y salidas.", metrics: [["Escaneo", "PDF e imágenes", "Crea una propuesta MusicXML revisable."], ["Notación", "Pentagrama ⇄ Jianpu", "Elige una dirección explícita."], ["Continuar", "Editar y transponer", "Corrige, reproduce, transpone y exporta la partitura aceptada."]], scannerAction: "Abrir escáner de partituras", converterAction: "Abrir convertidor Jianpu" },
    verification: { eyebrow: "Seguir comprobando", title: "Si no encuentras respuesta, consulta las guías o soporte", steps: [["01", "Comprueba primero el alcance", "Confirma que el reconocimiento, Jianpu y el flujo estructurado encajan con tu tarea."], ["02", "Comprueba pago y soporte", "Entiende los recorridos reales de checkout, activation y support antes de pagar."], ["03", "Después accede", "Continúa al pago solo si el alcance actual se ajusta a tu caso."]] },
    next: { eyebrow: "Siguiente paso", title: "¿Aún tienes dudas? Ve a soporte, presentación o pago", supportAction: "Abrir soporte", requestAction: "Enviar solicitud", aboutAction: "Ver presentación", checkoutAction: "Pago" },
    related: { eyebrow: "Ayuda relacionada", title: "Continúa con soporte, privacidad y condiciones", body: "Estas páginas ofrecen contactos, información de datos y límites del servicio.", privacyAction: "Privacidad", termsAction: "Condiciones", supportAction: "Página de soporte" },
  },
  readingGuide: {
    metadata: { title: "Cómo leer partituras: notas, ritmo y símbolos | ScoreTransposer", description: "Aprende a leer partituras con pentagrama, claves y notas; comprende valores, compases, armaduras y símbolos, y practica con una partitura online.", keywords: ["cómo leer partituras", "aprender solfeo", "duración de notas", "claves musicales", "símbolos musicales"], socialImageAlt: "Vista de partitura con interfaz en inglés para aprender notas y símbolos" },
    eyebrow: "Guía de lectura para principiantes", title: "Cómo leer partituras: empieza por las notas del pentagrama", intro: "No necesitas memorizar todos los símbolos de una vez. Empieza por la clave y una nota de referencia, y lee posición y ritmo paso a paso. Para una partitura difícil, usa el editor online para reproducir, ralentizar y revisar cada compás.", basicsEyebrow: "Bases de lectura", summaryTitle: "Empieza por cuatro elementos", summaryBody: "La mayoría de partituras iniciales se entienden al separar posición, clave, ritmo y tonalidad.", concepts: [["Pentagrama y altura", "Cinco líneas y cuatro espacios representan alturas; una nota más alta suele sonar más aguda."], ["Claves", "La clave de sol suele cubrir el registro agudo; la de fa, el grave y la mano izquierda del piano."], ["Valores y ritmo", "Redondas, blancas, negras y corcheas indican cuánto dura un sonido."], ["Compás y armadura", "La indicación de compás organiza los pulsos; la armadura fija sostenidos o bemoles recurrentes."]],
    orderEyebrow: "Orden de lectura", stepsTitle: "Lee un compás en este orden", stepsBody: "Establece primero el contexto, combina altura y ritmo y añade después la expresión.", steps: [["Comprueba clave y armadura", "Lee los símbolos de la izquierda para fijar referencias y alteraciones recurrentes."], ["Identifica las notas", "Usa líneas y espacios; las líneas adicionales prolongan el mismo patrón arriba y abajo."], ["Cuenta cada valor", "Combina figuras, puntillos, ligaduras, grupos irregulares y silencios para completar el compás."], ["Aplica alteraciones", "Un sostenido, bemol o becuadro suele afectar a las notas posteriores del mismo nombre dentro del compás."], ["Reproduce despacio y verifica", "Empieza con pulso estable y añade dinámica, articulación y cambios de tempo."]],
    symbolsEyebrow: "Símbolos de notación", symbolsTitle: "Símbolos musicales habituales", symbolsBody: "Leer música combina altura, tiempo y expresión, no solo nombres de notas.", symbols: [["♯, ♭ y ♮", "Sostenidos, bemoles y becuadros cambian la altura escrita."], ["Silencios", "Un silencio representa una duración sin sonido y cuenta en el ritmo."], ["Ligaduras de expresión y unión", "Una agrupa una frase; la otra suma la duración de notas de igual altura."], ["p, f, crescendo, diminuendo", "Las dinámicas indican volumen y su evolución."]],
    practiceEyebrow: "Práctica", practiceTitle: "Practica con una partitura real y editable", practiceBody: "Abre o sube una partitura autorizada, revisa cualquier propuesta reconocida y edita, reproduce, transpone o crea Jianpu en el mismo proyecto.", editAction: "Abrir editor de partituras", scanAction: "Escanear PDF o imagen", playAction: "Usar reproductor de partituras", faqEyebrow: "FAQ", faqTitle: "Preguntas sobre lectura musical", faqs: [["¿Debo memorizar todas las notas del pentagrama?", "No. Aprende unas notas de referencia en clave de sol y fa, y deduce las cercanas por pasos."], ["¿Por qué el piano usa dos pentagramas?", "Suele usar un gran pentagrama: clave de sol arriba y de fa abajo para leer ambas manos juntas."], ["¿Puedo confiar enseguida en una partitura escaneada?", "Revisa altura, ritmo, armadura y compases. El reconocimiento óptico crea una propuesta y no garantiza perfección en toda partitura compleja."]],
  },
  numberedNotation: {
    metadata: { title: "Convertidor de pentagrama y notación Jianpu | ScoreTransposer", description: "Convierte pentagrama a Jianpu o Jianpu a pentagrama y sigue editando, transponiendo, reproduciendo o exportando la misma partitura estructurada.", keywords: ["convertidor de notación numerada", "pentagrama a Jianpu", "Jianpu a pentagrama", "notación cifrada", "MusicXML Jianpu"], socialImageAlt: "Espacio estructurado pentagrama–Jianpu con interfaz en inglés" },
    eyebrow: "Conversión bidireccional", title: "Convertidor de pentagrama y notación numerada Jianpu", intro: "Elige la dirección. Ambas vías usan MusicXML y Score JSON estructurados, sin tratar píxeles de PDF o texto de imagen como notación editable.", directionOneEyebrow: "Dirección uno", staffTitle: "Pentagrama a Jianpu", staffBody: "Convierte pentagrama estructurado a notación numerada con centro tonal, grados, puntos de octava, duración, letra y contexto armónico.", staffAction: "Abrir pentagrama a Jianpu", directionTwoEyebrow: "Dirección dos", jianpuTitle: "Jianpu a pentagrama", jianpuBody: "Introduce Jianpu estructurado para crear pentagrama, MusicXML y Score JSON que se puedan previsualizar, corregir y exportar.", jianpuAction: "Abrir Jianpu a pentagrama", modelTitle: "Por qué importa la notación estructurada", modelBody: "El resultado sigue siendo editable, transponible, reproducible y exportable, en vez de convertirse en una imagen plana imposible de corregir.", limitsTitle: "Antes de convertir", limitsBody: "Un PDF escaneado debe pasar primero por reconocimiento y corrección. La vía actual Jianpu→pentagrama espera texto Jianpu estructurado escrito o pegado.", faqEyebrow: "FAQ", faqTitle: "Preguntas sobre notación numerada", faqs: [["¿Puedo editar notas después de convertir?", "Sí. El resultado entra en el proyecto Score JSON común, donde altura, ritmo, tonalidad y compases siguen siendo corregibles."], ["¿Cualquier imagen Jianpu escaneada puede convertirse en pentagrama?", "Todavía no. La vía actual prioriza texto Jianpu estructurado; el reconocimiento de imágenes arbitrarias queda para una futura importación."]],
  },
} as const satisfies StaticMarketingLocalization;
