import type { StaticMarketingLocalization } from "../types";

export const frStaticMarketing = {
  openGraphLocale: "fr_FR",
  homeBreadcrumb: "Accueil",
  about: {
    metadata: { title: "À propos de l’espace de partitions, contact et assistance | ScoreTransposer", description: "Découvrez cet espace MusicXML pour vérifier les scans, convertir le Jianpu, transposer, éditer, écouter, exporter et enseigner, ainsi que les parcours d’accès et d’assistance.", keywords: ["portée vers Jianpu", "PDF de partition vers notation chiffrée", "convertisseur Jianpu", "reconnaissance de partition", "édition de partition en ligne"], socialImageAlt: "Espace d’édition de partitions ScoreTransposer avec interface en anglais" },
    registrationLabel: "Immatriculation",
    hero: { eyebrow: "À propos / Contact / Assistance", title: "À propos de ScoreTransposer : son rôle, son public et son mode d’accès", body: "ScoreTransposer est un espace de partitions en ligne fondé sur MusicXML et Score JSON. Le site explique chaque parcours ; l’application gère l’import, la correction, la transposition, l’entraînement, l’enseignement et l’export.", checkoutAction: "Voir le parcours d’achat", appAction: "Ouvrir l’application", supportAction: "Contacter l’assistance" },
    position: { eyebrow: "Positionnement", title: "De la conversion portée–Jianpu à un espace complet de partition structurée", body: "Vérifiez les types de fichiers, le périmètre gratuit et les limites de reconnaissance avant d’ouvrir l’application. Toute proposition reconnue mérite une vérification humaine.", steps: [["01", "Créer une partition modifiable depuis un scan", "Importez un PDF de portée ou une image, examinez la proposition reconnue puis poursuivez dans le même projet de partition."], ["02", "Comprendre d’abord le périmètre", "La reconnaissance produit une proposition qui peut nécessiter des corrections. Un compte gratuit peut créer un projet conservé à vie depuis un PDF multipage complet ou une image de partition."], ["03", "Continuer dans l’application", "Connectez-vous pour importer et vérifier les propositions. Le projet gratuit inclut les outils actuellement disponibles d’édition, lecture, transposition, Jianpu, versions, partage et export ; les offres payantes ajoutent de la capacité de traitement et de stockage."]] },
    audience: { eyebrow: "Pour qui", title: "À qui s’adresse ScoreTransposer", metrics: [["Enseignement", "Préparation de supports", "Pour les enseignants et écoles qui veulent préparer plus vite des supports Jianpu depuis des PDF en portée."], ["Répétition", "Usage interculturel", "Pour les ensembles qui servent des lecteurs de portée et de Jianpu depuis une même source."], ["Production", "Propositions vérifiables", "Pour les arrangeurs, graveurs et éditeurs qui acceptent un flux automatisé avec validation humaine."]] },
    support: { eyebrow: "Contact et assistance", title: "Assistance pour le convertisseur de notation chiffrée et l’accès", body: "Utilisez le formulaire pour les questions de compte, activation, import, reconnaissance ou téléchargement.", steps: [["A", "Questions avant achat et paiement", "Demandez des précisions sur l’accès, les codes d’activation, le retour de paiement ou le périmètre avant d’acheter."], ["B", "Questions après achat et sur les fichiers", "L’assistance traite aussi les échecs d’activation, la vérification des commandes, les imports inattendus et les demandes de suppression manuelle."], ["C", "Informations utiles pour nous contacter", "Adresse e-mail, code d’activation, capture du paiement, date d’achat ou nom du fichier accélèrent la vérification."]], operatorAriaLabel: "Informations publiques sur l’exploitant", serviceBrandLabel: "Marque du service", canonicalWebsitePrefix: "Site officiel", customerSupportLabel: "Assistance clientèle", customerSupportBody: "Ce contact traite les questions de compte, fichiers, confidentialité, droits d’auteur et commandes.", legalOperatorLabel: "Exploitant légal", legalOperatorFallback: "Ce nom provient de la configuration publique de production.", requestAction: "Ouvrir une demande", privacyAction: "Ouvrir la politique de confidentialité", termsAction: "Ouvrir les conditions d’utilisation" },
    commerce: { eyebrow: "Parcours commercial", availableTitle: "Articulation entre site, paiement et codes d’activation", pendingTitle: "Le paiement ouvrira après validation des transactions en production", availableStatus: "Paiement international", pendingStatus: "Validation en attente", availableBody: "Les visiteurs internationaux peuvent utiliser le paiement hébergé ; après paiement, l’abonnement est directement rattaché au compte enregistré.", pendingBody: "Aucun paiement n’est encaissé actuellement. L’accès reste désactivé jusqu’à validation des succès, échecs, remboursements et droits.", mainlandStatus: "Codes pour la Chine continentale", mainlandAvailableBody: "Les clients de Chine continentale peuvent acheter un code par un canal vérifié puis l’activer dans l’application.", mainlandPendingBody: "La distribution de codes reste fermée jusqu’à validation du contrôle des commandes et de l’attribution des droits.", registerAction: "Créer un compte", checkoutAction: "Accéder au paiement" },
    useCases: { eyebrow: "Cas d’usage", title: "Faire entrer une partition existante dans un flux structuré", body: "Que vous partiez d’un PDF en portée, d’une image ou de Jianpu, vérifiez le résultat importé avant l’édition, la transposition, l’entraînement ou l’export.", items: [["Vous disposez d’un PDF ou d’une image en portée", "La reconnaissance crée une proposition structurée que vous pouvez examiner et continuer à travailler."], ["Vous utilisez portée et notation chiffrée", "Une même partition structurée sert à l’affichage en portée, au Jianpu, à la transposition, à l’entraînement et aux exports."], ["Vous pouvez vérifier la reconnaissance automatique", "Rythmes complexes, scans faibles et partitions à plusieurs parties peuvent demander des corrections ; propositions et diagnostics restent consultables."]] },
    startingPoints: { eyebrow: "Points de départ", title: "Choisir l’entrée adaptée à votre source", metrics: [["PDF ou image", "Reconnaissance", "Importez un PDF multipage complet ou une image de partition nette, droite et non rognée, puis vérifiez la proposition."], ["Portée et Jianpu", "Conversion", "Vérifiez la partition structurée avant de créer le Jianpu, transposer, lire ou vous entraîner."], ["Fichier de notation ou sauvegarde", "Poursuivre l’édition", "Importez directement MusicXML, MIDI ou une sauvegarde lorsque ce format est inclus dans l’offre actuelle."]] },
    learnMore: { eyebrow: "En savoir plus", title: "Poursuivre vers la confidentialité, les conditions et l’accès", body: "Après le positionnement et l’assistance, vérifiez généralement la confidentialité, les conditions et le parcours d’accès.", privacyAction: "Politique de confidentialité", termsAction: "Conditions d’utilisation", checkoutAction: "Voir le parcours d’achat" },
    next: { eyebrow: "Étape suivante", title: "Créez gratuitement un projet de partition complet ou consultez l’aide.", body: "Revenez à l’accueil pour voir les fonctions, ouvrez l’application pour créer un projet gratuit complet, ou consultez confidentialité et conditions pour les limites du service.", homeAction: "Retour à l’accueil", appAction: "Ouvrir l’application" },
  },
  faq: {
    metadata: { title: "FAQ : scan de partitions, Jianpu, transposition et export | ScoreTransposer", description: "Questions fréquentes sur le scan et la vérification, la conversion portée–Jianpu, la transposition, l’édition, la lecture, l’export, l’achat et l’assistance.", keywords: ["FAQ scan de partition", "portée vers Jianpu", "proposition OMR", "éditeur de partition en ligne", "assistance ScoreTransposer"], socialImageAlt: "Aperçu de partition ScoreTransposer avec interface en anglais" },
    hero: { eyebrow: "FAQ / Produit et assistance", title: "Questions sur le scan, l’édition, la conversion et l’accès", body: "Vérifiez les entrées prises en charge, les limites de reconnaissance, les résultats modifiables, le Jianpu, les droits du compte et l’assistance avant de continuer.", checkoutAction: "Voir le parcours d’achat", supportPageAction: "Ouvrir l’assistance", contactAction: "Contacter l’assistance" },
    groups: [
      { title: "Achat et accès", items: [["Qu’est-ce qui est réellement disponible aujourd’hui ?", "Un utilisateur inscrit peut créer un projet gratuit à vie depuis un PDF de partition multipage complet ou une image, avec les outils actuels de correction, lecture, transposition, Jianpu, versions, partage et export. Les offres payantes ajoutent de la capacité."], { question: "Les clients internationaux et de Chine continentale suivent-ils le même parcours ?", availableAnswer: "Pas exactement. Les clients internationaux paient directement en ligne ; ceux de Chine continentale peuvent aussi utiliser un canal de codes et les activer dans l’application.", pendingAnswer: "Le paiement en ligne n’est pas encore ouvert. Il sera activé après validation des paiements Paddle en production, remboursements et droits ; le projet gratuit complet reste disponible." }, { question: "Que reçois-je après paiement ?", availableAnswer: "Après un paiement réussi, l’abonnement est directement lié au compte enregistré, sans code à activer.", pendingAnswer: "Aucun paiement n’est encaissé actuellement. À l’ouverture, confirmation de commande et droits du compte seront attribués automatiquement par le flux de production validé." }] },
      { title: "Imports et résultats", items: [["Quels formats d’entrée sont pris en charge ?", "L’accès gratuit accepte un PDF multipage complet ou une image PNG, JPG, WebP ou TIFF. Starter et Converter Pro ajoutent des projets et les imports MusicXML/MXL, MIDI, Jianpu structuré et Score JSON actuellement disponibles. La transcription audio reste expérimentale."], ["Pourquoi la reconnaissance est-elle marquée comme proposition ?", "L’OMR peut mal lire hauteur, durée, voix ou structure de mesure. Le résultat reste donc une proposition à vérifier, avec confiance et alertes, sans prétendre être prêt pour publication."], ["Que faire si l’import ou le téléchargement échoue ?", "Conservez le nom du fichier, l’heure du traitement et une capture de l’erreur, puis envoyez le formulaire d’assistance pour retrouver plus vite la tâche concernée."]] },
      { title: "Assistance et comptes", items: [["Comment traiter un problème de paiement ou de code ?", "Utilisez d’abord le formulaire du site. Choisissez la catégorie paiement ou activation ; l’équipe suivra la demande avec son numéro de référence."], ["Que se passe-t-il après l’envoi du formulaire ?", "Le formulaire appelle l’API, crée une demande enregistrée et envoie automatiquement une confirmation à l’adresse de contact. Sans service e-mail actif, l’API consigne encore un aperçu de test."], ["Où comparer les conversions portée et Jianpu ?", "Ouvrez le convertisseur de notation chiffrée puis choisissez portée vers Jianpu ou Jianpu vers portée. Les deux conservent le résultat dans un projet structuré modifiable."]] },
    ],
    workflow: { eyebrow: "Choisir un flux", title: "Partir de la tâche à accomplir", body: "Scan, conversion bidirectionnelle et édition en ligne disposent chacun d’un guide ciblé pour clarifier entrées et sorties.", metrics: [["Scan", "PDF et images", "Créer une proposition MusicXML vérifiable."], ["Notation", "Portée ⇄ Jianpu", "Choisir un sens de conversion explicite."], ["Continuer", "Éditer et transposer", "Corriger, lire, transposer et exporter la partition acceptée."]], scannerAction: "Ouvrir le scanner de partitions", converterAction: "Ouvrir le convertisseur Jianpu" },
    verification: { eyebrow: "Poursuivre la vérification", title: "Sans réponse, consultez les guides ou contactez l’assistance", steps: [["01", "Vérifier d’abord le périmètre", "Confirmez que la reconnaissance, le Jianpu et le flux de partition structurée correspondent à votre tâche."], ["02", "Vérifier paiement et assistance", "Comprenez les véritables parcours checkout, activation et support avant de payer."], ["03", "Puis passer à l’accès", "Ne poursuivez vers le paiement que si le périmètre actuel répond à votre besoin."]] },
    next: { eyebrow: "Étape suivante", title: "Encore un doute ? Passez à l’assistance, à la présentation ou au paiement", supportAction: "Ouvrir l’assistance", requestAction: "Envoyer une demande", aboutAction: "Voir la présentation", checkoutAction: "Paiement" },
    related: { eyebrow: "Aide associée", title: "Consulter assistance, confidentialité et conditions", body: "Ces pages donnent les contacts, le traitement des données et les limites du service.", privacyAction: "Confidentialité", termsAction: "Conditions", supportAction: "Page d’assistance" },
  },
  readingGuide: {
    metadata: { title: "Comment lire une partition : notes, rythme et symboles | ScoreTransposer", description: "Apprenez à lire une partition avec la portée, les clés et les notes, puis les durées, mesures, armures et symboles courants, et entraînez-vous en ligne.", keywords: ["comment lire une partition", "apprendre le solfège", "durée des notes", "clés musicales", "symboles de notation"], socialImageAlt: "Aperçu de partition en interface anglaise pour apprendre notes et symboles" },
    eyebrow: "Guide de lecture pour débutants", title: "Comment lire une partition : commencer par les notes sur la portée", intro: "Inutile de mémoriser tous les symboles d’un coup. Repérez la clé et une note de référence, puis lisez progressivement position et rythme. Pour une partition difficile, utilisez l’éditeur en ligne afin d’écouter, ralentir et vérifier chaque mesure.", basicsEyebrow: "Bases de lecture", summaryTitle: "Commencer par quatre éléments", summaryBody: "La plupart des partitions débutantes deviennent lisibles en séparant position sur la portée, clé, rythme et tonalité.", concepts: [["Portée et hauteur", "Cinq lignes et quatre interlignes représentent les hauteurs ; une note placée plus haut sonne généralement plus aiguë."], ["Clés", "La clé de sol couvre souvent l’aigu ; la clé de fa le grave et la main gauche du piano."], ["Valeurs et rythme", "Rondes, blanches, noires et croches indiquent la durée du son."], ["Mesure et armure", "La signature rythmique organise les temps ; l’armure établit les dièses ou bémols récurrents."]],
    orderEyebrow: "Ordre de lecture", stepsTitle: "Lire une mesure dans cet ordre", stepsBody: "Établissez d’abord le contexte, combinez hauteur et rythme, puis ajoutez l’expression.", steps: [["Vérifier la clé et l’armure", "Lisez les symboles à gauche pour établir les repères de hauteur et altérations récurrentes."], ["Identifier les notes", "Utilisez lignes et interlignes ; les lignes supplémentaires prolongent le même motif au-dessus et au-dessous."], ["Compter chaque valeur", "Combinez formes, points, liaisons, triolets et silences pour compléter correctement la mesure."], ["Appliquer les altérations", "Dièse, bémol ou bécarre affecte normalement les notes suivantes de même nom dans la mesure."], ["Écouter lentement et vérifier", "Commencez avec une pulsation stable, puis ajoutez nuances, articulations et changements de tempo."]],
    symbolsEyebrow: "Symboles de notation", symbolsTitle: "Symboles musicaux courants", symbolsBody: "Lire une partition, c’est combiner hauteur, temps et expression, pas seulement nommer les notes.", symbols: [["♯, ♭ et ♮", "Dièses, bémols et bécarres modifient la hauteur écrite."], ["Silences", "Un silence représente une durée sans son et compte dans le rythme."], ["Liaisons de phrasé et de prolongation", "La première regroupe une phrase ; la seconde additionne la durée de notes identiques."], ["p, f, crescendo, diminuendo", "Les nuances indiquent le volume et son évolution."]],
    practiceEyebrow: "Pratique", practiceTitle: "S’entraîner avec une vraie partition modifiable", practiceBody: "Ouvrez ou importez une partition autorisée, vérifiez toute proposition reconnue, puis éditez, écoutez, transposez ou créez le Jianpu dans le même projet.", editAction: "Ouvrir l’éditeur de partitions", scanAction: "Scanner un PDF ou une image", playAction: "Utiliser le lecteur de partitions", faqEyebrow: "FAQ", faqTitle: "Questions sur la lecture de partitions", faqs: [["Faut-il mémoriser toutes les notes de la portée ?", "Non. Apprenez quelques notes repères en clé de sol et de fa, puis déduisez les voisines par degrés."], ["Pourquoi une partition de piano a-t-elle deux portées ?", "Le piano utilise souvent une grande portée : clé de sol en haut et clé de fa en bas, pour lire les deux mains ensemble."], ["Puis-je utiliser immédiatement une partition scannée ?", "Vérifiez d’abord hauteurs, rythme, armure et mesures. La reconnaissance optique crée une proposition et ne garantit pas un résultat parfait pour toute partition complexe."]],
  },
  numberedNotation: {
    metadata: { title: "Convertisseur portée et notation chiffrée Jianpu | ScoreTransposer", description: "Convertissez portée vers Jianpu ou Jianpu vers portée, puis éditez, transposez, écoutez ou exportez la même partition structurée.", keywords: ["convertisseur notation chiffrée", "portée vers Jianpu", "Jianpu vers portée", "notation numérotée", "MusicXML Jianpu"], socialImageAlt: "Espace structuré portée–Jianpu avec interface en anglais" },
    eyebrow: "Conversion bidirectionnelle", title: "Convertisseur de portée et de notation chiffrée Jianpu", intro: "Choisissez le sens voulu. Les deux parcours utilisent MusicXML et Score JSON structurés, sans traiter les pixels d’un PDF ou le texte d’une image comme une notation modifiable.", directionOneEyebrow: "Sens 1", staffTitle: "Portée vers Jianpu", staffBody: "Convertissez la portée structurée en notation chiffrée avec centre tonal, degrés, points d’octave, durées, paroles et contexte harmonique.", staffAction: "Ouvrir portée vers Jianpu", directionTwoEyebrow: "Sens 2", jianpuTitle: "Jianpu vers portée", jianpuBody: "Saisissez du Jianpu structuré pour créer portée, MusicXML et Score JSON prévisualisables, corrigeables et exportables.", jianpuAction: "Ouvrir Jianpu vers portée", modelTitle: "Pourquoi une notation structurée", modelBody: "Le résultat reste éditable, transposable, lisible et exportable au lieu de devenir une image plate impossible à corriger.", limitsTitle: "À savoir avant la conversion", limitsBody: "Un PDF scanné doit d’abord passer par reconnaissance et correction. Le parcours Jianpu vers portée attend actuellement un texte Jianpu structuré saisi ou collé.", faqEyebrow: "FAQ", faqTitle: "Questions sur la notation chiffrée", faqs: [["Puis-je modifier les notes après conversion ?", "Oui. Le résultat rejoint le projet Score JSON commun, où hauteur, rythme, tonalité et mesures restent corrigeables."], ["Toute image Jianpu scannée peut-elle devenir une portée ?", "Pas encore. Le parcours actuel privilégie le texte Jianpu structuré ; la reconnaissance d’images quelconques reste une future capacité d’import."]],
  },
} as const satisfies StaticMarketingLocalization;
