import type { SupportLegalLocalization } from "../types";

export const deSupportLegal = {
  openGraphLocale: "de_DE", homeBreadcrumb: "Startseite",
  legalReviewNotice: { eyebrow: "Hinweis zur Rechtsübersetzung", title: "Diese Übersetzung ist ein ungeprüfter Entwurf", body: "Diese Übersetzung dient nur zur Orientierung und muss von qualifizierten Rechtsfachleuten geprüft werden. Bei Widersprüchen gilt die englische Fassung.", ariaLabel: "Hinweis zur Prüfung der Rechtsübersetzung" },
  support: {
    metadata: { title: "Support, Kontakt und Bestellprüfung | ScoreTransposer", description: "Kontaktieren Sie ScoreTransposer bei Fragen zu Konto, Aktivierung, Notenerkennung, Ergebnisbereitstellung und Datenschutz.", keywords: ["ScoreTransposer Support", "Aktivierung Hilfe", "Notenupload Support", "Bestellprüfung", "Datenschutzanfrage"], socialImageAlt: "ScoreTransposer-Ergebnisvorschau mit englischer Benutzeroberfläche" },
    schemaName: "ScoreTransposer Support", schemaContactType: "Kundensupport",
    hero: { eyebrow: "Support / Kontakt / Prüfung", title: "Brauchen Sie Hilfe? Beschreiben Sie, was passiert ist", body: "Senden Sie hier Fragen zu Konto, Aktivierung, Erkennung, Download oder Datenschutz. Vollständige Angaben beschleunigen Prüfung und Antwort.", submitAction: "Supportanfrage senden", faqAction: "FAQ öffnen", checkoutAction: "Kaufweg ansehen" },
    form: {
      eyebrow: "Anfrage senden", title: "Supportformular auf der Website", body: "Senden Sie Ihre Anfrage direkt über die Website. Das Formular ruft die API auf, erstellt einen nachverfolgbaren Vorgang und sendet automatisch eine Bestätigung an Ihre Kontaktadresse.", categoryLabel: "Supportkategorie", categoryAriaLabel: "Supportkategorie auswählen", nameLabel: "Kontaktname (optional)", contactEmailLabel: "Kontakt-E-Mail", accountEmailLabel: "Konto-E-Mail (optional)", orderReferenceLabel: "Bestell-/Zahlungsreferenz (optional)", jobReferenceLabel: "Auftragsnummer / Dateiname (optional)", subjectLabel: "Betreff", messageLabel: "Problembeschreibung", messageHint: "Nennen Sie Schritte, ungefähre Zeit, sichtbaren Fehler oder Symptom und bereits versuchte Maßnahmen.", honeypotLabel: "Website", submitting: "Wird gesendet...", submit: "Supportanfrage senden", emailAction: "Öffentliche Support-E-Mail verwenden", emailFallback: "Wenn automatische E-Mails vorübergehend ausfallen, schreiben Sie direkt an {supportEmail}.", successSent: "Ihre Anfrage wurde unter {referenceCode} angenommen. Die Bestätigung wurde gesendet.", successPreview: "Ihre Anfrage wurde unter {referenceCode} angenommen. Transaktions-E-Mail ist hier nicht eingerichtet; die Bestätigung wurde in den API-Vorschaulog geschrieben.", successFailed: "Ihre Anfrage wurde unter {referenceCode} angenommen, aber die Bestätigung konnte nicht automatisch versendet werden. Nennen Sie diese Referenz bei direktem Kontakt.",
      categories: { payment: { label: "Zahlung / Bestellung", helper: "Fehlender Zugang nach Zahlung, Rückleitungsprobleme, Doppelbelastung oder manuelle Prüfung.", subject: "Anfrage zur Zahlungs-/Bestellprüfung" }, activation: { label: "Aktivierung / Zugang", helper: "Einlösung fehlgeschlagen, Zugang fehlt oder Berechtigungsdaten sind falsch.", subject: "Aktivierungs-/Berechtigungsproblem" }, job: { label: "Upload / Ergebnis", helper: "Uploadfehler, blockierter Auftrag, defekter Download oder final/draft-Frage.", subject: "Supportanfrage zu Upload / Ergebnis" }, privacy: { label: "Datenschutz / Löschung", helper: "Löschung, Export oder andere Datenschutzprüfung.", subject: "Datenschutz-/Löschanfrage" }, general: { label: "Allgemein", helper: "Andere Anliegen oder wenn der Support die Zuordnung übernehmen soll.", subject: "Allgemeine Supportanfrage" } },
    },
    workflows: { eyebrow: "Supportkategorien", title: "Problem zuerst einordnen, dann manuell prüfen lassen", items: [["01", "Zahlung und Bestellung", "Bei erfolgreicher Zahlung ohne Kontozugang, unvollständiger Rückleitung, Doppelbelastungsverdacht oder notwendiger Bestellprüfung."], ["02", "Aktivierung und Berechtigung", "Bei fehlgeschlagener Einlösung, fehlendem Zugang, falschen Laufzeiten oder erforderlicher Prüfung des Kontoumfangs."], ["03", "Upload und Ergebnis", "Bei fehlgeschlagenem PDF, blockiertem Auftrag, defektem Download oder final/draft-Ergebnis mit nötigem menschlichem Kontext."]] },
    evidence: { eyebrow: "Hilfreiche Angaben", title: "Ausreichende Details beschleunigen meist den manuellen Support", status: "Empfohlene Nachweise", points: ["Kontakt- oder Konto-E-Mail", "Kaufzeit, Zahlungsanbieter und Zahlungsbild", "Code, Bestellung, Auftrag oder Dateiname", "Fehlerbild, Auslösungsschritte und ungefähre Zeit"] },
    boundary: { eyebrow: "Supportumfang", title: "Wobei Support helfen kann", body: "Support umfasst Kontozugang, Aktivierungscodes, Uploads, Erkennungsaufträge, Ergebnisanzeige und -download sowie Datenschutzanfragen.", metrics: [["Produkthilfe", "Konten und Noten", "Konto, Zahlung, Aktivierung, Upload, Auftrag und Ergebnisbereitstellung."], ["Erkennung", "Prüfung erforderlich", "Automatische Erkennung kann Korrektur brauchen. Fügen Sie bei komplexen Noten Quelle und Screenshot bei."], ["Manuelle Prüfung", "Verfügbar", "Bestellung, Einlösung, Downloadprobleme und Löschanfragen."]] },
    after: { eyebrow: "Nach dem Absenden", title: "Was danach geschieht", body: "Eine erfolgreiche Anfrage erhält eine Referenz, die Sie aufbewahren sollten. Wenn Benachrichtigungen verfügbar sind, wird auch eine Bestätigung gesendet.", aboutAction: "Über uns öffnen", privacyAction: "Datenschutz", termsAction: "Bedingungen" },
    final: { title: "Supportanfrage senden", body: "Wählen Sie den Typ und nennen Sie Konto-E-Mail, Auftrag, Datei, ungefähre Zeit und relevante Screenshots.", formAction: "Supportformular öffnen", faqAction: "FAQ", checkoutAction: "Checkout" },
  },
  copyright: {
    metadata: { title: "Verfahren für Urheberrechtsbeschwerden | ScoreTransposer", description: "Melden Sie Partituren, Aufnahmen oder Freigabelinks, erhalten Sie einen privaten Abfragecode und sehen Sie öffentliche Fallupdates.", keywords: ["Urheberrechtsbeschwerde", "Noten entfernen", "verletzende URL", "Copyright Fallstatus", "ScoreTransposer Urheberrecht"], socialImageAlt: "ScoreTransposer-Notenvorschau mit englischer Oberfläche für das Urheberrechtsverfahren" },
    hero: { eyebrow: "Urheberrecht und Compliance", title: "Urheberrechtsbeschwerde und Fallstatus", body: "Strukturierte Einreichung, private Abfrage, öffentliche Updates und interne Prüfung bleiben getrennt. 48 Stunden sind das Ziel für eine erste Antwort, keine rechtliche Entscheidung oder garantierte Lösungsfrist." }, faqTitle: "Häufige Fragen",
    faqs: [["Welche URLs kann ich melden?", "Senden Sie konkrete URLs der ScoreTransposer-Website, App oder öffentlichen Freigabedomains."], ["Warum wird der Zugangscode nur einmal gezeigt?", "Es wird nur ein Hash gespeichert; der ursprüngliche Code kann nicht aus der Datenbank wiederhergestellt werden."], ["Wird Inhalt nach Einreichung automatisch entfernt?", "Nein. Die Unterlagen werden geprüft; Informationsanfragen, Maßnahmen oder Ablehnungsgründe erscheinen in der öffentlichen Fallhistorie."]],
    form: { submitTitle: "Urheberrechtsbeschwerde einreichen", submitBody: "Nennen Sie Rechtsgrundlage, Originalwerk und Ziel-URLs auf der Plattform. Sie erhalten Referenz und einmaligen Zugangscode.", submitFormAriaLabel: "Formular für Urheberrechtsbeschwerden", name: "Name der beschwerdeführenden Person", email: "Kontakt-E-Mail", organization: "Organisation / Verlag (optional)", relationship: "Beziehung zum Werk", owner: "Urheberrechtsinhaber", agent: "Bevollmächtigte Vertretung", work: "Originalwerk und Rechtsbeschreibung", workHint: "Nennen Sie Titel, Urheber, Erstveröffentlichung oder Registrierung und den beanspruchten Rechtsumfang.", targets: "Angeblich verletzende ScoreTransposer-URLs", targetsHint: "Eine Plattform-URL pro Zeile, höchstens 20.", evidence: "Beleglinks (optional)", evidenceHint: "Eine öffentlich erreichbare URL pro Zeile, höchstens 10. Keine sensiblen personenbezogenen Daten in Links.", action: "Verlangte Maßnahme der Plattform", goodFaith: "Ich bin nach bestem Wissen überzeugt, dass die Nutzung weder durch Rechtsinhaber, Vertretung noch Gesetz erlaubt ist.", accuracy: "Ich bestätige die Richtigkeit und meine Befugnis, für den betroffenen Rechtsinhaber zu handeln.", signature: "Elektronische Unterschrift (rechtlichen Namen eingeben)", honeypotLabel: "Website", submit: "Beschwerde senden", submitting: "Wird gesendet...", receiptTitle: "Beschwerde registriert", receiptStatus: "Eingegangen", receiptBody: "Speichern Sie Referenz und Zugangscode jetzt. Aus Sicherheitsgründen wird der Code nicht erneut angezeigt.", receiptAriaLabel: "Eingangsbestätigung der Urheberrechtsbeschwerde", due: "Ziel für erste Antwort", trackTitle: "Beschwerdestatus verfolgen", trackBody: "Die Abfrage verwendet POST, damit der Code nicht in URL oder Browserverlauf steht.", trackFormAriaLabel: "Formular zur Statusabfrage einer Urheberrechtsbeschwerde", reference: "Beschwerdereferenz", access: "Zugangscode", lookup: "Status prüfen", lookingUp: "Wird geprüft...", current: "Aktueller Status", actionTaken: "Ergriffene Maßnahme", history: "Öffentliche Fallhistorie", emptyHistory: "Noch keine öffentlichen Fallupdates verfügbar.", statuses: { received: "Eingegangen", validating: "Wird validiert", info_required: "Informationen erforderlich", reviewing: "In Prüfung", actioned: "Maßnahme ergriffen", rejected: "Abgelehnt", closed: "Geschlossen" } },
  },
  privacy: {
    metadata: { title: "Datenschutzerklärung der Notenplattform | ScoreTransposer", description: "Erfahren Sie, wie Konto-, Noten- und Mediendaten, Ergebnisse, Exporte, Löschfristen und Aufbewahrung behandelt werden.", keywords: ["ScoreTransposer Datenschutz", "Notendateien Aufbewahrung", "Konto löschen", "Musikdaten Datenschutz", "Analyse Einwilligung"], socialImageAlt: "ScoreTransposer-Notenvorschau mit englischer Oberfläche für die Datenschutzerklärung" },
    hero: { eyebrow: "Datenschutzerklärung", title: "Aktueller Datenschutzrahmen für scoretransposer.com", body: "Diese Erklärung beschreibt den Umgang mit Kontodaten, hochgeladenen Noten und Medien, strukturierten Revisionen, Ergebnissen und Supportakten.", updatedPrefix: "Zuletzt aktualisiert", termsAction: "Bedingungen ansehen" },
    sections: [
      { title: "Erhobene Informationen", points: ["Kontodaten wie E-Mail, Passwort-Hash, Aktivierungsstatus und Berechtigungsdaten.", "Hochgeladene Noten, Scans, Audio oder Video, strukturiertes MusicXML und Score JSON, Exporte und Korrekturhistorie.", "Betriebsmetadaten wie Uploadzeit, Auftragsstatus, Dateinamen und Supportkontakte."] },
      { title: "Nutzung der Daten", points: ["Authentifizierung, Prüfung bezahlten Zugangs und Bereitstellung von Scan, Bearbeitung, Konvertierung, Transposition, Wiedergabe, Übung und Export.", "Aufbewahrung von Quellen und Ergebnissen zur Ansicht und zum Download durch angemeldete Nutzer.", "Untersuchung fehlgeschlagener Aufträge, Supportantworten und Verbesserung heuristischer Konvertierung."] },
      { title: "Aufbewahrung und Löschung", points: ["Konto- und Berechtigungsdaten bleiben während der Aktivität und für erforderlichen Folgesupport gespeichert.", "Quellen und Ergebnisse bleiben für Download, Prüfung und Fehlerbehebung gespeichert.", "Angemeldete Nutzer können strukturierte Daten herunterladen und nach Passwortprüfung löschen lassen. Es gilt eine 14-tägige Widerrufsfrist.", "Danach werden Noten, Unterrichtsdaten, Supportakten und Dateien gelöscht; notwendige Zahlungsdaten werden desidentifiziert."] },
      { title: "Datenweitergabe", points: ["Kundendateien werden nicht verkauft.", "Anbieter für Verkehr, Hosting, DNS, Speicher, Logging und Bereitstellung können notwendige Betriebsdaten verarbeiten.", "Daten können bei gesetzlicher Pflicht oder zum Schutz vor Missbrauch, Betrug oder Sicherheitsvorfällen offengelegt werden."] },
      { title: "Cookies und Analyse", points: ["Ein funktionales Sprach-Cookie merkt sich die Oberflächensprache.", "Cloudflare Web Analytics Real User Measurement (RUM) ist global aktiviert, um Seitenaufrufe und Ladeleistung zu messen. Es verwendet keine Cookies, liest keinen Browser-Speicher und verwirft Besucher-IP-Adressen am Cloudflare-Edge.", "GA4 oder Microsoft Clarity wird nur nach ausdrücklicher Einwilligung und bei aktivierter Produktionsanalyse geladen.", "Die Ablehnung einwilligungspflichtiger Analysen beschränkt weder öffentliche Inhalte noch Produktabläufe."] },
      { title: "Sicherheitsbasis", points: ["Der Konverter erfordert Authentifizierung und aktivierungsbasierte Berechtigungsprüfungen.", "Produktionszugang sollte auf autorisierte Personen begrenzt sein; Geheimnisse gehören in die Hostingplattform, nicht in den Quellcode.", "Nutzer müssen rechtswidrige oder unbefugte Uploads vermeiden und musikalische Richtigkeit vor Veröffentlichung oder Aufführung prüfen."] },
    ],
    contact: { title: "Kontakt und Änderungen", body: "Datenexport und Kontolöschung sind im angemeldeten Dashboard verfügbar. Wenn Sie sich nicht anmelden können oder Erläuterungen brauchen, nutzen Sie den öffentlichen Support und bestätigen Sie Ihre Identität.", note: "Wir aktualisieren diese Erklärung bei wesentlichen Änderungen an Hosting, Speicher, Analyse, Zahlung oder Kontoverarbeitung.", action: "Datenschutzanfrage öffnen" },
    related: { eyebrow: "Verwandte Informationen", title: "Weiter zu Bedingungen und Produktinformationen", body: "Wer über Suche oder Checkout hierher gelangt, möchte oft auch Position, Grenzen und Kaufweg prüfen.", aboutAction: "Über uns und Support öffnen", termsAction: "Bedingungen öffnen", checkoutAction: "Kaufweg ansehen" },
    continue: { eyebrow: "Weiter", title: "Häufig folgen Support, Bedingungen und Kaufinformationen.", body: "Bei Fragen zu Daten, Kontolöschung oder Datenschutzrechten nutzen Sie das Supportformular.", supportAction: "Support kontaktieren", homeAction: "Zur Startseite" },
  },
  terms: {
    metadata: { title: "Nutzungsbedingungen der Notenplattform | ScoreTransposer", description: "Bedingungen für MusicXML-Import, Bearbeitung, Transposition, Jianpu, Wiedergabe, Export, Unterricht, Urheberrecht und zulässige Nutzung.", keywords: ["ScoreTransposer Bedingungen", "Noten Abonnement", "Upload Regeln", "Abonnement kündigen", "Urheberrecht zulässige Nutzung"], socialImageAlt: "ScoreTransposer-Notenvorschau mit englischer Oberfläche für die Nutzungsbedingungen" },
    hero: { eyebrow: "Nutzungsbedingungen", title: "ScoreTransposer Nutzungsbedingungen", body: "Diese Bedingungen erklären kostenlosen Zugang, Aktivierung, automatische Verlängerung, Kündigung, Ergebnisbereitstellung und Nutzerpflichten.", updatedPrefix: "Zuletzt aktualisiert", privacyAction: "Datenschutz ansehen" },
    sections: [
      { title: "Leistungsumfang", points: ["Der Dienst unterstützt Notenprojekte, strukturierte Importe, Notensystem/Jianpu-Konvertierung, Transposition, Korrektur, Wiedergabe, Unterricht und konfigurierte Exporte.", "OMR, PDF/Bild-Ausgabe, hochwertige Audioausgabe und Audiotranskription benötigen externe Werkzeuge und können in einer Bereitstellung fehlen.", "Website, App und Ausgaben können sich entwickeln; beim Kauf gilt nur der veröffentlichte aktuelle Umfang."] },
      { title: "Konten und Abonnementzugang", points: ["Ein registriertes Free-Konto kann innerhalb der veröffentlichten monatlichen Auftrags- und Speichergrenzen ein vollständiges Notenprojekt erstellen, ohne Zahlungskarte oder Aktivierungscode.", "Bezahlter Zugang kann nach Bestätigung durch den Zahlungsanbieter automatisch oder durch einen gültigen Code aus autorisiertem Kanal aktiviert werden.", "Zugang ist an den Berechtigungszeitraum gebunden und kann wegen Betrug, Missbrauch, Zahlungsstreit oder Regelverstoß ausgesetzt werden.", "Kunden müssen Zugangsdaten geheim halten und verantworten alle Kontoaktivitäten."] },
      { title: "Uploads und Ergebnisse", points: ["Nutzer dürfen nur Inhalte hochladen, die sie verarbeiten dürfen.", "Kann das System ein Ergebnis nicht sicher hochstufen, wird es als final PDF oder draft-Paket geliefert.", "Vor Veröffentlichung, Unterricht, Probe oder Aufführung müssen Nutzer musikalische Richtigkeit, Urheberrecht und Eignung prüfen."] },
      { title: "Abrechnung, Verlängerung, Kündigung und Erstattung", points: ["Starter und Converter Pro sind monatlich oder jährlich wiederkehrende Abonnements nach Preis, Währung, Steuer und Intervall im Checkout.", "Ohne Kündigung verlängert sich das Abonnement und die gespeicherte Zahlungsart wird zu Beginn jeder Periode belastet.", "Kunden können in Billing kündigen oder vor der nächsten Verlängerung den Support kontaktieren. Künftige Verlängerungen enden; Zugang bleibt normalerweise bis Periodenende, außer bei Erstattung, Streit, Betrugsprüfung oder Rechtspflicht.", "Erstattungen können beim Support beantragt werden. Es gelten Kaufbedingungen, Anbieterregeln und zwingendes Verbraucherrecht; eine volle Erstattung kann den bezahlten Zugang beenden."] },
      { title: "Zulässige Nutzung", points: ["Malware, rechtsverletzende Inhalte und Dateien zur Störung der Plattform dürfen nicht hochgeladen werden.", "Automatisierter Missbrauch, Teilen von Zugangsdaten, Auslesen privater Kundendaten und Umgehen von Berechtigungen sind verboten.", "ScoreTransposer kann Zugang bei Missbrauch, Sicherheitsrisiko oder rechtlicher Gefahr aussetzen oder beenden."] },
    ],
    purchase: { title: "Kauf- und Erstattungshinweise", body: "Preis, Intervall, Steuer und Zahlungsart folgen dem Checkout; Kündigung und Erstattung folgen diesen Bedingungen, Kaufhinweisen und Anbieterregeln.", note: "Wir aktualisieren die Hinweise bei wesentlichen Änderungen an Plänen, Preisen, Verlängerung oder Umfang.", supportAction: "Supportanfrage öffnen" },
    related: { eyebrow: "Verwandte Seiten", title: "Weiter zu Datenschutz, Produkt und Support", body: "Nach der Prüfung der Grenzen können Sie Datenverarbeitung, Supportwege und tatsächliche Aktivierung prüfen.", privacyAction: "Datenschutz öffnen", copyrightAction: "Urheberrechtsbeschwerde senden", aboutAction: "Über uns und Support öffnen", checkoutAction: "Kaufweg ansehen" },
    help: { eyebrow: "Hilfe", title: "Fragen zu Bedingungen oder Kontozugang?", body: "Lesen Sie Datenschutz und Produktinformationen oder senden Sie eine konkrete Frage über das Supportformular.", supportAction: "Support kontaktieren", homeAction: "Zur Startseite" },
  },
} as const satisfies SupportLegalLocalization;
