import type { SupportLegalLocalization } from "../types";

export const esSupportLegal = {
  openGraphLocale: "es_ES", homeBreadcrumb: "Inicio",
  legalReviewNotice: { eyebrow: "Aviso de traducción jurídica", title: "Esta traducción es un borrador sin revisar", body: "Esta traducción se ofrece solo como referencia y debe revisarla un profesional jurídico cualificado. Si entra en conflicto con la versión inglesa, prevalece la versión inglesa.", ariaLabel: "Aviso de revisión de traducción jurídica" },
  support: {
    metadata: { title: "Soporte, contacto y revisión de pedidos | ScoreTransposer", description: "Contacta con soporte de ScoreTransposer sobre cuentas, activación, reconocimiento de partituras, entrega de resultados y privacidad.", keywords: ["soporte ScoreTransposer", "ayuda de activación", "soporte de partituras", "revisión de pedido", "solicitud de privacidad"], socialImageAlt: "Vista del resultado de ScoreTransposer con interfaz en inglés" },
    schemaName: "Soporte de ScoreTransposer", schemaContactType: "atención al cliente",
    hero: { eyebrow: "Soporte / Contacto / Revisión", title: "¿Necesitas ayuda? Cuéntanos qué ha ocurrido", body: "Envía aquí preguntas sobre cuenta, activación, reconocimiento, descarga o privacidad. Cuantos más detalles incluyas, antes podremos investigar y responder.", submitAction: "Enviar solicitud", faqAction: "Abrir FAQ", checkoutAction: "Ver vía de compra" },
    form: {
      eyebrow: "Enviar solicitud", title: "Formulario de soporte del sitio", body: "Envía una solicitud de soporte y guarda su referencia para el seguimiento. Si el envío de correo está disponible, recibirás una confirmación en tu dirección de contacto.", categoryLabel: "Categoría de soporte", categoryAriaLabel: "Elegir categoría de soporte", nameLabel: "Nombre de contacto (opcional)", contactEmailLabel: "Correo de contacto", accountEmailLabel: "Correo de la cuenta (opcional)", orderReferenceLabel: "Pedido / referencia de pago (opcional)", jobReferenceLabel: "Tarea / nombre de archivo (opcional)", subjectLabel: "Asunto", messageLabel: "Detalles del problema", messageHint: "Incluye los pasos, hora aproximada, error o síntoma visible y lo que ya hayas probado.", honeypotLabel: "Sitio web", submitting: "Enviando...", submit: "Enviar solicitud", emailAction: "Usar correo público de soporte", emailFallback: "Si el correo automático no está disponible temporalmente, escribe directamente a {supportEmail}.", successSent: "Hemos recibido tu solicitud con la referencia {referenceCode}. Se ha enviado el correo de confirmación.", successPreview: "Hemos recibido tu solicitud con la referencia {referenceCode}. No se ha enviado un correo de confirmación. Guarda esta referencia y contacta directamente con soporte si necesitas hacer un seguimiento.", successFailed: "Hemos recibido tu solicitud con la referencia {referenceCode}, pero no se pudo enviar la confirmación automáticamente. Usa esta referencia si contactas directamente.",
      categories: { payment: { label: "Pago / pedido", helper: "Acceso ausente tras el pago, retorno incompleto, posible doble cargo o revisión manual.", subject: "Solicitud de revisión de pago / pedido" }, activation: { label: "Activación / acceso", helper: "Fallo al canjear, acceso ausente o fechas de derechos incorrectas.", subject: "Problema de activación / derechos" }, job: { label: "Carga / resultado", helper: "Problemas de subida, tareas detenidas, descargas que fallan o dudas sobre resultados finales y borradores.", subject: "Solicitud sobre carga / resultado" }, privacy: { label: "Privacidad / eliminación", helper: "Eliminación, exportación u otra revisión manual de privacidad.", subject: "Solicitud de privacidad / eliminación" }, general: { label: "General", helper: "Cualquier otro asunto o si necesitas que soporte lo derive.", subject: "Solicitud general de soporte" } },
    },
    workflows: { eyebrow: "Categorías", title: "Clasifica primero el problema y después pasa a la revisión manual", items: [["01", "Pago y pedido", "Para un pago correcto sin acceso de cuenta, retorno incompleto, posible doble cargo o un pedido que requiere revisión manual."], ["02", "Activación y derechos", "Para canjes fallidos, acceso sin activar, fechas incorrectas o comprobación del alcance de la cuenta."], ["03", "Carga y resultado", "Para fallos al subir PDF, tareas detenidas, descargas que fallan o resultados finales y borradores que necesitan revisión."]] },
    evidence: { eyebrow: "Qué incluir", title: "El soporte manual suele avanzar antes con suficiente detalle", status: "Pruebas recomendadas", points: ["Correo de contacto o de cuenta", "Fecha de compra, proveedor y captura del pago", "Referencia del pedido, de la tarea o nombre del archivo. No envíes contraseñas, códigos de activación completos ni códigos privados de consulta de reclamaciones.", "Captura del error, pasos y hora aproximada"] },
    boundary: { eyebrow: "Alcance del soporte", title: "En qué puede ayudarte soporte", body: "Soporte cubre acceso de cuenta, códigos, cargas, tareas de reconocimiento, visualización y descarga de resultados y solicitudes de privacidad.", metrics: [["Ayuda del producto", "Cuentas y partituras", "Cuenta, pago, activación, carga, tarea y entrega del resultado."], ["Reconocimiento", "Revisión necesaria", "El reconocimiento automático puede requerir corrección. Para partituras complejas, adjunta la fuente y una captura."], ["Revisión manual", "Disponible", "Pedidos, canjes, anomalías de descarga y eliminación."]] },
    after: { eyebrow: "Después del envío", title: "Qué ocurre tras enviarlo", body: "Al aceptar la solicitud se crea una referencia que debes guardar. Si hay notificaciones disponibles, recibirás una confirmación por correo.", aboutAction: "Ver presentación", privacyAction: "Privacidad", termsAction: "Condiciones" },
    final: { title: "Enviar una solicitud de soporte", body: "Elige el tipo e incluye correo de cuenta, tarea, archivo, hora aproximada y capturas relevantes.", formAction: "Abrir formulario", faqAction: "FAQ", checkoutAction: "Pago" },
  },
  copyright: {
    metadata: { title: "Proceso de reclamación de derechos de autor | ScoreTransposer", description: "Reclama sobre una partitura, grabación o enlace compartido, recibe un código privado y consulta las actualizaciones públicas del caso.", keywords: ["reclamación derechos de autor", "retirada de partitura", "URL infractora", "estado reclamación copyright", "copyright ScoreTransposer"], socialImageAlt: "Vista de ScoreTransposer con interfaz en inglés para la reclamación de derechos" },
    hero: { eyebrow: "Derechos de autor y cumplimiento", title: "Reclamación de derechos de autor y estado del caso", body: "El envío estructurado, la consulta privada, las actualizaciones públicas y la auditoría interna permanecen separados. El objetivo de 48 horas es para una primera respuesta, no una conclusión jurídica ni un plazo garantizado de resolución." }, faqTitle: "Preguntas frecuentes",
    faqs: [["¿Qué URL puedo denunciar?", "Envía URL concretas del sitio, la aplicación o los dominios públicos de uso compartido de ScoreTransposer."], ["¿Por qué el código solo se muestra una vez?", "Solo se almacena su hash, por lo que el código original no puede recuperarse de la base de datos."], ["¿El contenido se elimina automáticamente al enviar la reclamación?", "No. La plataforma revisa el material y registra públicamente solicitudes de información, medidas o motivos de rechazo."]],
    form: { submitTitle: "Enviar reclamación de derechos de autor", submitBody: "Describe tus derechos, la obra original y las URL correspondientes de la plataforma. Recibirás una referencia y un código privado de consulta. El código solo se muestra una vez; guárdalo para consultar el estado más adelante.", submitFormAriaLabel: "Formulario de reclamación de derechos de autor", name: "Nombre del reclamante", email: "Correo de contacto", organization: "Organización / editorial (opcional)", relationship: "Relación con la obra", owner: "Titular de derechos", agent: "Representante autorizado", work: "Obra original y descripción de derechos", workHint: "Incluye título, autor, primera publicación o registro y alcance de los derechos reclamados.", targets: "URL de ScoreTransposer presuntamente infractoras", targetsHint: "Una URL de la plataforma por línea, hasta 20.", evidence: "Enlaces de prueba (opcional)", evidenceHint: "Una URL de acceso público por línea, hasta 10. No incluyas datos personales sensibles en los enlaces.", action: "Medida solicitada a la plataforma", goodFaith: "Creo de buena fe que el uso no está autorizado por el titular, su representante ni la ley.", accuracy: "Confirmo que la información es exacta y que estoy autorizado para actuar por el titular correspondiente.", signature: "Firma electrónica (nombre legal)", honeypotLabel: "Sitio web", submit: "Enviar reclamación", submitting: "Enviando...", receiptTitle: "Reclamación registrada", receiptStatus: "Recibida", receiptBody: "Guarda ahora la referencia y el código. Por seguridad, el código no volverá a mostrarse en el sitio.", receiptAriaLabel: "Justificante de reclamación de derechos", due: "Objetivo de primera respuesta", trackTitle: "Consultar estado", trackBody: "La consulta usa POST para que el código no aparezca en la URL ni en el historial del navegador.", trackFormAriaLabel: "Formulario de seguimiento de reclamación", reference: "Referencia de reclamación", access: "Código de acceso", lookup: "Consultar estado", lookingUp: "Consultando...", current: "Estado actual", actionTaken: "Medida tomada", history: "Historial público", emptyHistory: "Todavía no hay actualizaciones públicas del caso.", statuses: { received: "Recibida", validating: "Validando", info_required: "Información necesaria", reviewing: "En revisión", actioned: "Medida tomada", rejected: "Rechazada", closed: "Cerrada" } },
  },
  privacy: {
    metadata: { title: "Política de privacidad de la plataforma musical | ScoreTransposer", description: "Consulta cómo se tratan las cuentas, partituras y medios cargados, resultados, exportaciones, plazos de eliminación y conservación.", keywords: ["privacidad ScoreTransposer", "conservación partituras", "eliminar cuenta", "privacidad datos musicales", "consentimiento analítica"], socialImageAlt: "Vista de ScoreTransposer con interfaz en inglés para la política de privacidad" },
    hero: { eyebrow: "Política de privacidad", title: "Base de privacidad actual de scoretransposer.com", body: "Esta política explica el tratamiento de datos de cuenta, partituras y medios cargados, revisiones estructuradas, resultados generados y registros de soporte.", updatedPrefix: "Última actualización", termsAction: "Ver condiciones" },
    sections: [
      { title: "Información recopilada", points: ["Datos de cuenta como correo, hash de contraseña, estado de activación y fechas de derechos.", "Partituras, escaneos, audio o vídeo cargados, MusicXML y Score JSON estructurados, exportaciones y historial de correcciones.", "Metadatos operativos como fecha de carga, estado de tareas, nombres de archivo y contactos con soporte."] },
      { title: "Uso de los datos", points: ["Autenticar, verificar acceso de pago y ofrecer escaneo, edición, conversión, transposición, reproducción, práctica y exportación.", "Conservar fuentes y resultados para que el usuario conectado los revise y descargue en la aplicación.", "Investigar tareas fallidas, responder a soporte y mejorar la calidad de conversión heurística."] },
      { title: "Conservación y eliminación", points: ["Las cuentas y derechos se conservan mientras la cuenta esté activa y para el soporte posterior necesario.", "Fuentes y resultados se conservan para descarga, revisión y resolución de incidencias.", "El usuario conectado puede descargar una copia estructurada y pedir eliminación tras verificar la contraseña. Hay 14 días para cancelar la eliminación.", "Tras ese plazo se eliminan partituras, datos de aula, registros de soporte y archivos; los pagos necesarios para auditoría se desidentifican."] },
      { title: "Intercambio de datos", points: ["Los archivos de clientes no se venden.", "Proveedores de tráfico, alojamiento, DNS, almacenamiento, registros y despliegue pueden tratar datos operativos necesarios.", "Los datos pueden divulgarse por obligación legal o para proteger el servicio de abuso, fraude o incidentes de seguridad."] },
      { title: "Cookies y analítica", points: ["Una cookie funcional recuerda el idioma de interfaz elegido.", "GA4 o Microsoft Clarity solo se carga con consentimiento explícito y analítica de producción activa.", "Rechazar la analítica no impide acceder al contenido público ni a los flujos del producto."] },
      { title: "Base de seguridad", points: ["Los flujos de la cuenta requieren autenticación. Las comprobaciones de acceso aplican el plan gratuito, las compras confirmadas, las suscripciones o los códigos canjeados vinculados a la cuenta.", "El acceso de producción debe limitarse a operadores autorizados y los secretos deben gestionarse en el alojamiento, no en el código.", "El usuario debe evitar cargas ilícitas o no autorizadas y verificar la exactitud musical antes de publicar o interpretar."] },
    ],
    contact: { title: "Contacto y cambios de política", body: "La exportación y eliminación de cuenta están disponibles en el panel con sesión iniciada. Si no puedes entrar o necesitas aclaraciones, usa el soporte público y confirma tu identidad.", note: "Actualizaremos esta política cuando haya cambios importantes en alojamiento, almacenamiento, analítica, pagos o cuentas.", action: "Abrir solicitud de privacidad" },
    related: { eyebrow: "Información relacionada", title: "Continuar a condiciones y producto", body: "Quien llega desde búsqueda o pago suele querer confirmar también el producto, los límites y la vía de compra.", aboutAction: "Abrir presentación y soporte", termsAction: "Abrir condiciones", checkoutAction: "Ver vía de compra" },
    continue: { eyebrow: "Seguir explorando", title: "Los siguientes destinos habituales son soporte, condiciones y compra.", body: "Para dudas sobre datos, eliminación de cuenta o derechos de privacidad, usa el formulario de soporte.", supportAction: "Contactar con soporte", homeAction: "Volver al inicio" },
  },
  terms: {
    metadata: { title: "Condiciones de la plataforma de partituras | ScoreTransposer", description: "Consulta las condiciones de MusicXML sobre carga, edición, transposición, Jianpu, reproducción, exportación, educación, copyright y uso aceptable.", keywords: ["condiciones ScoreTransposer", "suscripción partituras", "reglas carga partituras", "cancelar suscripción", "copyright uso aceptable"], socialImageAlt: "Vista de ScoreTransposer con interfaz en inglés para las condiciones" },
    hero: { eyebrow: "Condiciones del servicio", title: "Condiciones de ScoreTransposer", body: "Estas condiciones explican el acceso gratuito, las compras únicas, las suscripciones, la renovación, la cancelación, la entrega de resultados y tus responsabilidades.", updatedPrefix: "Última actualización", privacyAction: "Ver privacidad" },
    sections: [
      { title: "Alcance del servicio", points: ["El servicio admite proyectos, importaciones estructuradas, conversión pentagrama/Jianpu, transposición, corrección, reproducción, enseñanza y formatos configurados.", "OMR, salida PDF/imagen, audio de alta calidad y transcripción requieren herramientas externas configuradas y pueden no estar disponibles.", "Sitio, aplicación y resultados pueden cambiar; al comprar, confía solo en el alcance público vigente."] },
      { title: "Cuentas y acceso", points: ["Una cuenta Free registrada puede crear un proyecto completo dentro de los límites mensuales y de almacenamiento publicados, sin tarjeta ni código de activación.", "El acceso de pago se activa cuando el proveedor confirma una compra única o suscripción, o al canjear un código válido de un canal autorizado.", "El acceso de pago se vincula al periodo correspondiente y puede suspenderse por fraude, abuso, disputas de cargos o infracciones de las políticas.", "El cliente debe proteger sus credenciales y responde de toda actividad de la cuenta."] },
      { title: "Cargas y resultados", points: ["Solo puede cargarse contenido que el usuario esté autorizado a procesar.", "Los resultados pueden entregarse como un PDF final o como un paquete de borrador cuando el sistema no puede confirmar su calidad.", "Antes de publicar, enseñar, ensayar o interpretar, el usuario debe revisar exactitud musical, copyright e idoneidad."] },
      { title: "Facturación, renovación, cancelación y reembolsos", points: ["Starter y Converter Pro están disponibles como compra única o suscripción por un mes o un año. La modalidad, el precio, la moneda, los impuestos y el periodo de acceso o facturación se muestran antes de pagar.", "Una compra única finaliza sin renovación automática; otra compra del mismo nivel de plan amplía el acceso. Solo una suscripción elegida expresamente se renueva y cobra el método guardado al comienzo del siguiente periodo.", "Si tienes una suscripción, detén futuras renovaciones en Facturación o contacta con soporte antes de la siguiente renovación. Normalmente conservas el acceso hasta el final del periodo pagado, salvo reembolso, disputa de cargo, revisión por fraude o exigencia legal.", "Los reembolsos se solicitan a soporte. La elegibilidad sigue las condiciones de compra, reglas del proveedor y derecho imperativo de consumo; un reembolso total puede finalizar los derechos pagados."] },
      { title: "Uso aceptable", points: ["Está prohibido cargar malware, contenido infractor o archivos destinados a perturbar la plataforma.", "Se prohíben abuso automatizado, compartir credenciales, extraer datos privados y eludir controles de derechos.", "ScoreTransposer puede suspender o cancelar el acceso al detectar abuso, riesgo de seguridad o exposición legal."] },
    ],
    purchase: { title: "Compra y reembolsos", body: "Precio, ciclo, impuestos y pago siguen el checkout; cancelación y reembolso siguen estas condiciones, la información de compra y las reglas del proveedor.", note: "Actualizaremos esta información si cambian de forma importante planes, precios, renovación o alcance.", supportAction: "Abrir solicitud" },
    related: { eyebrow: "Páginas relacionadas", title: "Continuar a privacidad, producto y soporte", body: "Tras revisar los límites, confirma también el tratamiento de datos, las vías de soporte y la activación real.", privacyAction: "Abrir privacidad", copyrightAction: "Enviar reclamación de copyright", aboutAction: "Abrir presentación y soporte", checkoutAction: "Ver vía de compra" },
    help: { eyebrow: "¿Necesitas ayuda?", title: "¿Dudas sobre estas condiciones o tu acceso?", body: "Consulta privacidad y producto o envía una pregunta concreta mediante el formulario de soporte.", supportAction: "Contactar con soporte", homeAction: "Volver al inicio" },
  },
} as const satisfies SupportLegalLocalization;
