import type { SupportLegalLocalization } from "../types";

export const frSupportLegal = {
  openGraphLocale: "fr_FR", homeBreadcrumb: "Accueil",
  legalReviewNotice: { eyebrow: "Avis sur la traduction juridique", title: "Cette traduction est un projet non validé", body: "Cette traduction est fournie à titre indicatif et doit être examinée par un juriste qualifié. En cas de conflit avec la version anglaise, la version anglaise prévaut.", ariaLabel: "Avis de révision de la traduction juridique" },
  support: {
    metadata: { title: "Assistance, contact et vérification de commande | ScoreTransposer", description: "Contactez l’assistance ScoreTransposer pour les comptes, l’activation, la reconnaissance de partitions, la livraison des résultats et la confidentialité.", keywords: ["assistance ScoreTransposer", "aide activation", "assistance import partition", "vérification commande", "demande confidentialité"], socialImageAlt: "Aperçu du résultat ScoreTransposer avec interface en anglais" },
    schemaName: "Assistance ScoreTransposer", schemaContactType: "assistance clientèle",
    hero: { eyebrow: "Assistance / Contact / Vérification", title: "Besoin d’aide ? Expliquez-nous ce qui s’est passé", body: "Envoyez ici vos questions de compte, activation, reconnaissance, téléchargement ou confidentialité. Des informations complètes accélèrent l’enquête et la réponse.", submitAction: "Envoyer une demande", faqAction: "Ouvrir la FAQ", checkoutAction: "Voir le parcours d’achat" },
    form: {
      eyebrow: "Envoyer une demande", title: "Formulaire d’assistance du site", body: "Envoyez votre demande directement depuis le site. Le formulaire appelle l’API, crée une demande suivie et envoie automatiquement une confirmation à votre adresse de contact.", categoryLabel: "Catégorie d’assistance", categoryAriaLabel: "Choisir une catégorie d’assistance", nameLabel: "Nom du contact (facultatif)", contactEmailLabel: "E-mail de contact", accountEmailLabel: "E-mail du compte (facultatif)", orderReferenceLabel: "Commande / référence de paiement (facultatif)", jobReferenceLabel: "Tâche / nom de fichier (facultatif)", subjectLabel: "Objet", messageLabel: "Détails du problème", messageHint: "Indiquez les étapes, l’heure approximative, l’erreur ou le symptôme visible et ce que vous avez déjà essayé.", honeypotLabel: "Site web", submitting: "Envoi...", submit: "Envoyer la demande", emailAction: "Utiliser l’e-mail public", emailFallback: "Si l’e-mail automatique est momentanément indisponible, écrivez directement à {supportEmail}.", successSent: "Votre demande a été reçue sous la référence {referenceCode}. L’e-mail de confirmation a été envoyé.", successPreview: "Votre demande a été reçue sous la référence {referenceCode}. L’e-mail transactionnel n’est pas configuré ici ; la confirmation figure dans les journaux d’aperçu de l’API.", successFailed: "Votre demande a été reçue sous la référence {referenceCode}, mais la confirmation n’a pas pu être envoyée automatiquement. Mentionnez cette référence en nous contactant directement.",
      categories: { payment: { label: "Paiement / commande", helper: "Accès absent après paiement, retour incomplet, risque de double débit ou vérification manuelle.", subject: "Demande de vérification de paiement / commande" }, activation: { label: "Activation / accès", helper: "Échec d’activation, accès absent ou dates de droits incorrectes.", subject: "Problème d’activation / de droits" }, job: { label: "Import / résultat", helper: "Échec d’import, tâche bloquée, téléchargement cassé ou question final/draft.", subject: "Demande d’assistance import / résultat" }, privacy: { label: "Confidentialité / suppression", helper: "Suppression, export ou autre examen manuel lié à la confidentialité.", subject: "Demande de confidentialité / suppression" }, general: { label: "Général", helper: "Tout autre sujet ou demande à faire orienter par l’assistance.", subject: "Demande d’assistance générale" } },
    },
    workflows: { eyebrow: "Catégories", title: "Classez d’abord le problème, puis passez à la vérification humaine", items: [["01", "Paiement et commande", "Pour un paiement réussi sans accès au compte, un retour incomplet, un doute de double débit ou une commande à vérifier manuellement."], ["02", "Activation et droits", "Pour un échec d’activation, un accès absent, une date de droit erronée ou une portée de compte à vérifier."], ["03", "Import et résultat", "Pour un échec de PDF, une tâche bloquée, un téléchargement défaillant ou un résultat final/draft nécessitant du contexte humain."]] },
    evidence: { eyebrow: "Informations utiles", title: "Une demande détaillée accélère généralement l’assistance humaine", status: "Éléments recommandés", points: ["E-mail de contact ou du compte", "Date d’achat, prestataire et capture du paiement", "Code, commande, tâche ou nom de fichier disponible", "Capture de l’erreur, étapes et heure approximative"] },
    boundary: { eyebrow: "Périmètre", title: "Ce que l’assistance peut traiter", body: "L’assistance couvre les comptes, codes d’activation, imports, tâches de reconnaissance, consultation et téléchargement des résultats, ainsi que les demandes de confidentialité.", metrics: [["Aide produit", "Comptes et partitions", "Compte, paiement, activation, import, tâche et livraison du résultat."], ["Reconnaissance", "Vérification requise", "La reconnaissance automatique peut nécessiter des corrections. Pour une partition complexe, joignez la source et une capture."], ["Examen humain", "Disponible", "Commandes, activation, téléchargements anormaux et suppressions."]] },
    after: { eyebrow: "Après l’envoi", title: "Ce qui se passe après l’envoi", body: "Une demande acceptée reçoit une référence à conserver. Si les notifications sont disponibles, une confirmation est aussi envoyée à votre adresse.", aboutAction: "Voir la présentation", privacyAction: "Confidentialité", termsAction: "Conditions" },
    final: { title: "Envoyer une demande d’assistance", body: "Choisissez le type de problème et ajoutez l’e-mail du compte, la tâche, le fichier, l’heure approximative et les captures utiles.", formAction: "Ouvrir le formulaire", faqAction: "FAQ", checkoutAction: "Paiement" },
  },
  copyright: {
    metadata: { title: "Procédure de plainte pour atteinte au droit d’auteur | ScoreTransposer", description: "Signalez une partition, un enregistrement ou un lien partagé, recevez un code de suivi privé et consultez les mises à jour publiques du dossier.", keywords: ["plainte droit d’auteur", "retrait partition", "URL contrefaisante", "suivi plainte copyright", "copyright ScoreTransposer"], socialImageAlt: "Aperçu ScoreTransposer en interface anglaise pour la procédure de droit d’auteur" },
    hero: { eyebrow: "Droit d’auteur et conformité", title: "Plainte pour atteinte au droit d’auteur et état du dossier", body: "Le dépôt structuré, la consultation privée, les mises à jour publiques et l’audit interne restent séparés. Le délai de 48 heures vise une première réponse, sans constituer une décision juridique ni garantir la résolution." }, faqTitle: "Questions fréquentes",
    faqs: [["Quelles URL puis-je signaler ?", "Fournissez des URL précises du site, de l’application ou des domaines de partage publics ScoreTransposer."], ["Pourquoi le code d’accès n’est-il affiché qu’une fois ?", "Seul son hachage est conservé ; le code d’origine ne peut donc pas être récupéré dans la base."], ["Le dépôt entraîne-t-il un retrait automatique ?", "Non. La plateforme examine les éléments et consigne publiquement les demandes d’information, mesures ou motifs de rejet."]],
    form: { submitTitle: "Déposer une plainte pour atteinte au droit d’auteur", submitBody: "Indiquez le fondement de vos droits, l’œuvre originale et les URL visées sur la plateforme. Le dépôt crée une référence et un code d’accès à usage unique.", submitFormAriaLabel: "Formulaire de plainte pour atteinte au droit d’auteur", name: "Nom du plaignant", email: "E-mail de contact", organization: "Organisation / éditeur (facultatif)", relationship: "Lien avec l’œuvre", owner: "Titulaire des droits", agent: "Mandataire autorisé", work: "Œuvre originale et description des droits", workHint: "Indiquez titre, auteur, première publication ou enregistrement et étendue des droits revendiqués.", targets: "URL ScoreTransposer prétendument contrefaisantes", targetsHint: "Une URL de la plateforme par ligne, 20 au maximum.", evidence: "Liens de preuve (facultatif)", evidenceHint: "Une URL publiquement accessible par ligne, 10 au maximum. N’y placez aucune donnée personnelle sensible.", action: "Mesure demandée à la plateforme", goodFaith: "Je crois de bonne foi que cette utilisation n’est autorisée ni par le titulaire, ni par son mandataire, ni par la loi.", accuracy: "Je confirme l’exactitude des informations et mon habilitation à agir pour le titulaire concerné.", signature: "Signature électronique (nom légal)", honeypotLabel: "Site web", submit: "Déposer la plainte", submitting: "Envoi...", receiptTitle: "Plainte enregistrée", receiptStatus: "Reçue", receiptBody: "Conservez immédiatement la référence et le code d’accès. Par sécurité, ce code ne sera plus affiché sur le site.", receiptAriaLabel: "Récépissé de plainte pour droit d’auteur", due: "Objectif de première réponse", trackTitle: "Suivre la plainte", trackBody: "La consultation utilise POST afin que le code ne figure ni dans l’URL ni dans l’historique du navigateur.", trackFormAriaLabel: "Formulaire de suivi d’une plainte pour droit d’auteur", reference: "Référence de plainte", access: "Code d’accès", lookup: "Consulter l’état", lookingUp: "Consultation...", current: "État actuel", actionTaken: "Mesure prise", history: "Historique public", emptyHistory: "Aucune mise à jour publique n’est encore disponible.", statuses: { received: "Reçue", validating: "Validation", info_required: "Informations requises", reviewing: "En examen", actioned: "Mesure prise", rejected: "Rejetée", closed: "Clôturée" } },
  },
  privacy: {
    metadata: { title: "Politique de confidentialité de la plateforme musicale | ScoreTransposer", description: "Découvrez le traitement des comptes, partitions et médias importés, résultats, exports, délais de suppression et durées de conservation.", keywords: ["confidentialité ScoreTransposer", "conservation partitions", "suppression compte", "données musicales", "consentement analytique"], socialImageAlt: "Aperçu ScoreTransposer en interface anglaise pour la politique de confidentialité" },
    hero: { eyebrow: "Politique de confidentialité", title: "Règles de confidentialité actuelles de scoretransposer.com", body: "Cette politique décrit le traitement des données de compte, partitions et médias importés, révisions structurées, résultats produits et dossiers d’assistance.", updatedPrefix: "Dernière mise à jour", termsAction: "Voir les conditions" },
    sections: [
      { title: "Informations collectées", points: ["Données de compte : adresse e-mail, hachage du mot de passe, état d’activation et dates des droits.", "Partitions, scans, audio ou vidéo importés, MusicXML et Score JSON structurés, exports produits et historique des corrections.", "Métadonnées opérationnelles : date d’import, état des tâches, noms de fichiers et contacts avec l’assistance."] },
      { title: "Utilisation des données", points: ["Authentifier, vérifier l’accès payant et fournir scan, édition, conversion, transposition, lecture, entraînement et export.", "Conserver les sources et résultats afin que l’utilisateur connecté puisse les consulter et les télécharger dans l’application.", "Enquêter sur les tâches échouées, répondre à l’assistance et améliorer la qualité des conversions heuristiques."] },
      { title: "Conservation et suppression", points: ["Les comptes et droits sont conservés tant que le compte est actif et pour le suivi nécessaire.", "Les sources et résultats sont conservés pour le téléchargement, la vérification et le dépannage.", "L’utilisateur connecté peut télécharger une copie structurée et demander la suppression après vérification du mot de passe. Un délai d’annulation de 14 jours s’applique.", "Après ce délai, partitions, données de classe, dossiers d’assistance et fichiers sont supprimés ; les données de paiement nécessaires à l’audit sont désidentifiées."] },
      { title: "Partage des données", points: ["Les fichiers clients ne sont pas vendus.", "Les prestataires de trafic, hébergement, DNS, stockage, journalisation et déploiement peuvent traiter les données nécessaires au service.", "Des données peuvent être communiquées si la loi l’exige ou pour protéger le service contre abus, fraude ou incident de sécurité."] },
      { title: "Cookies et mesure d’audience", points: ["Un cookie fonctionnel mémorise la langue d’interface choisie.", "La mesure des utilisateurs réels (RUM) de Cloudflare Web Analytics est activée globalement pour mesurer les pages vues et les performances de chargement. Elle n’utilise pas de cookie, ne lit pas le stockage du navigateur et supprime l’adresse IP du visiteur à la périphérie de Cloudflare.", "GA4 ou Microsoft Clarity ne se charge qu’après consentement explicite et lorsque l’analyse de production est active.", "Refuser les analyses soumises au consentement ne retire pas l’accès au contenu public ni aux fonctions du produit."] },
      { title: "Socle de sécurité", points: ["L’outil de conversion exige une authentification et une vérification des droits fondée sur l’activation.", "L’accès de production doit être limité aux opérateurs autorisés ; les secrets doivent être gérés par l’hébergeur et non dans le code source.", "L’utilisateur doit éviter tout import illicite ou non autorisé et vérifier l’exactitude musicale avant publication ou exécution."] },
    ],
    contact: { title: "Contact et évolution de la politique", body: "L’export et la suppression du compte sont disponibles dans le tableau de bord connecté. Si vous ne pouvez pas vous connecter ou souhaitez une explication, utilisez l’assistance publique et confirmez votre identité.", note: "Nous actualiserons cette politique lors de changements importants d’hébergement, stockage, analyse, paiement ou gestion des comptes.", action: "Ouvrir une demande de confidentialité" },
    related: { eyebrow: "Informations associées", title: "Poursuivre vers les conditions et le produit", body: "Après une arrivée depuis la recherche ou le paiement, vérifiez aussi le positionnement, les limites du service et le parcours d’achat.", aboutAction: "Ouvrir présentation et assistance", termsAction: "Ouvrir les conditions", checkoutAction: "Voir le parcours d’achat" },
    continue: { eyebrow: "Continuer", title: "Les destinations suivantes sont souvent l’assistance, les conditions et l’achat.", body: "Pour toute question sur les données, la suppression du compte ou vos droits, contactez-nous par le formulaire d’assistance.", supportAction: "Contacter l’assistance", homeAction: "Retour à l’accueil" },
  },
  terms: {
    metadata: { title: "Conditions d’utilisation de la plateforme musicale | ScoreTransposer", description: "Consultez les conditions MusicXML sur l’import, l’édition, la transposition, le Jianpu, la lecture, l’export, l’enseignement, le droit d’auteur et l’usage acceptable.", keywords: ["conditions ScoreTransposer", "abonnement partition", "règles import partition", "résiliation abonnement", "droit d’auteur usage acceptable"], socialImageAlt: "Aperçu ScoreTransposer en interface anglaise pour les conditions d’utilisation" },
    hero: { eyebrow: "Conditions d’utilisation", title: "Conditions d’utilisation de ScoreTransposer", body: "Ces conditions expliquent l’accès gratuit, l’activation des abonnements, le renouvellement automatique, la résiliation, la livraison des résultats et les responsabilités.", updatedPrefix: "Dernière mise à jour", privacyAction: "Voir la confidentialité" },
    sections: [
      { title: "Périmètre du service", points: ["Le service couvre projets de partitions, imports structurés, conversion portée/Jianpu, transposition, correction, lecture, enseignement et formats d’export configurés.", "OMR, sortie PDF/image, audio haute qualité et transcription audio exigent des outils externes configurés et peuvent manquer dans un déploiement.", "Le site, l’application et les sorties peuvent évoluer ; lors d’un achat, fiez-vous uniquement au périmètre public alors en vigueur."] },
      { title: "Comptes et accès par abonnement", points: ["Un compte Free inscrit peut créer un projet de partition complet dans les limites mensuelles de tâches et de stockage publiées, sans carte ni code d’activation.", "L’accès payant peut être activé après confirmation de l’abonnement par le prestataire ou par un code valide issu d’un canal autorisé.", "L’accès est lié à la période de droits et peut être suspendu pour fraude, abus, contestation de paiement ou violation des règles.", "Le client doit protéger ses identifiants et répond de toute activité effectuée avec son compte."] },
      { title: "Imports et résultats", points: ["L’utilisateur ne peut importer que du contenu qu’il est autorisé à traiter.", "Si le système ne peut pas valider le résultat avec confiance, la livraison peut être un PDF final ou un paquet draft.", "Avant publication, enseignement, répétition ou exécution, l’utilisateur doit vérifier exactitude musicale, droits et adéquation."] },
      { title: "Facturation, renouvellement, résiliation et remboursements", points: ["Starter et Converter Pro sont des abonnements récurrents mensuels ou annuels, selon prix, devise, taxes et cycle affichés au paiement.", "Sans résiliation, l’abonnement se renouvelle et le moyen enregistré est débité au début de chaque période.", "Le client peut résilier dans Billing ou contacter l’assistance avant le prochain renouvellement. La résiliation arrête les renouvellements ; l’accès reste normalement actif jusqu’à la fin de la période, sauf remboursement, litige, fraude ou obligation légale.", "Les remboursements se demandent par l’assistance. L’éligibilité suit les conditions d’achat, les règles du prestataire et le droit impératif de la consommation ; un remboursement total peut mettre fin aux droits payants concernés."] },
      { title: "Utilisation acceptable", points: ["Il est interdit d’importer logiciels malveillants, contenus contrefaisants ou fichiers destinés à perturber la plateforme.", "Abus automatisé, partage d’identifiants, extraction de données clients privées et contournement des droits sont interdits.", "ScoreTransposer peut suspendre ou résilier l’accès en cas d’abus, de risque de sécurité ou d’exposition juridique."] },
    ],
    purchase: { title: "Achat et remboursement", body: "Prix, cycle, taxes et moyen de paiement suivent le checkout ; résiliation et remboursement suivent ces conditions, les informations d’achat et les règles du prestataire.", note: "Nous actualiserons ces informations lors de changements importants de plans, prix, renouvellement ou périmètre.", supportAction: "Ouvrir une demande" },
    related: { eyebrow: "Pages associées", title: "Consulter confidentialité, produit et assistance", body: "Après avoir vérifié les limites du service, confirmez aussi le traitement des données, les voies d’assistance et l’activation réelle.", privacyAction: "Ouvrir la confidentialité", copyrightAction: "Déposer une plainte copyright", aboutAction: "Ouvrir présentation et assistance", checkoutAction: "Voir le parcours d’achat" },
    help: { eyebrow: "Besoin d’aide", title: "Une question sur ces conditions ou votre accès ?", body: "Consultez la confidentialité et le produit ou envoyez une question précise avec le formulaire d’assistance.", supportAction: "Contacter l’assistance", homeAction: "Retour à l’accueil" },
  },
} as const satisfies SupportLegalLocalization;
