import { tool } from "./types";

export const de = {
  "sheet-music-scanner": tool({
    title: "Notenscanner für PDF und Bilder — Kostenlose Online-OMR", description: "Mit dem Notenscanner PDF oder Fotos einlesen, erkannte Noten korrigieren, transponieren und als MusicXML, MIDI oder PDF exportieren. Kostenlos ausprobieren, ohne Installation.",
    h1: "Notenscanner für PDF und Bilder", intro: "Dieser Notenscanner wandelt gedruckte Noten aus PDF oder Fotos in bearbeitbare Noten um. Vergleichen Sie das Ergebnis mit der Vorlage, korrigieren Sie Fehler und transponieren, hören oder exportieren Sie die Partitur.",
    moduleTitle: "Notenscanner für gedruckte Partituren", modules: [["PDF und Fotos", "Laden Sie ein vollständiges PDF oder PNG, JPG, WebP oder TIFF hoch."], ["Notenerkennung", "Lesen Sie Tonhöhen und Rhythmen aus gedruckter Notation."], ["MusicXML speichern", "Bearbeiten Sie die Noten in kompatiblen Notensatzprogrammen weiter."], ["Fehler korrigieren", "Vergleichen Sie Noten, Pausen und Takte mit der Vorlage."]],
    workflowTitle: "So scannen Sie Noten aus einem PDF", workflow: [["Klare Vorlage hochladen", "Verwenden Sie ein PDF oder ein vollständiges Foto gedruckter Noten."], ["Noten erkennen lassen", "Öffnen Sie nach Abschluss der Verarbeitung die erkannte Partitur."], ["Prüfen und exportieren", "Kontrollieren Sie Tonhöhen, Notenwerte und Takte und hören Sie das Ergebnis an."]],
    details: [["Notenscanner für Handyfotos", "Fotografieren Sie die ganze Seite bei gleichmäßiger Beleuchtung. Halten Sie die Kamera parallel zum Papier und vermeiden Sie Unschärfe."], ["Wie genau ist der Notenscanner?", "Das hängt von Bildqualität und Notation ab. Dichte Akkorde und ungewöhnliche Zeichen können manuelle Korrekturen erfordern."]],
    faq: [["Ist der Notenscanner kostenlos?", "Ein kostenloses Konto umfasst ein vollständiges Notenprojekt und 25 Credits pro Monat. Auch ein mehrseitiges PDF kann ein Projekt bilden. Entsprechende Serveraufträge verbrauchen Credits; zusätzliche Projekte oder Kapazität sind kostenpflichtig."], ["Kann er handgeschriebene Noten lesen?", "Die Erkennung ist für gedruckte Noten gedacht. Handschrift wird nicht zuverlässig unterstützt. Bereiten Sie stattdessen MusicXML vor oder geben Sie strukturierten Jianpu-Text ein."], ["Funktioniert er mit Handyfotos?", "Ja, in den unterstützten Bildformaten. Notenlinien und Notenköpfe müssen gut lesbar sein. Prüfen Sie anschließend die erkannten Noten."], ["Wie lange dauert der Scan einer Seite?", "Es gibt keine feste Dauer. Bildqualität, Seitenzahl, Komplexität und Warteschlange beeinflussen die Verarbeitung. Die Anwendung zeigt den Status an."], ["Kann ich Fehler nach dem Scannen korrigieren?", "Ja. Ändern Sie Tonhöhen, Notenwerte, Pausen und Takteinstellungen im Editor und hören Sie vor dem Export noch einmal hinein."]],
    links: ["Korrigieren Sie das Ergebnis im ", ["Noteneditor", "/score-editor"], ", ", ["transponieren Sie die Noten", "/transpose-score"], " und ", ["exportieren Sie MIDI", "/musicxml-midi"], ". Für eine bearbeitbare Datei nutzen Sie ", ["PDF in MusicXML", "/pdf-to-musicxml"], "."],
  }, "FAQ"),
  "pdf-to-musicxml": tool({
    title: "PDF in MusicXML umwandeln — Online-Konverter", description: "Laden Sie ein Noten-PDF oder Foto hoch und erhalten Sie bearbeitbares MusicXML: falsch erkannte Noten korrigieren, transponieren, abspielen und exportieren. Kostenlos ausprobieren, ohne Installation.",
    h1: "PDF in MusicXML umwandeln", intro: "Wandeln Sie PDF in MusicXML um, um Noten aus einem PDF oder Foto zu bearbeiten. Korrigieren Sie Erkennungsfehler, transponieren Sie, hören Sie das Ergebnis an und laden Sie MusicXML herunter.",
    moduleTitle: "PDF in MusicXML mit bearbeitbaren Noten", modules: [["Vorlage importieren", "Verwenden Sie ein Noten-PDF oder ein deutliches Scanbild."], ["Noten lesen", "Erkennen Sie gedruckte Tonhöhen und Rhythmen."], ["Notation korrigieren", "Prüfen Sie Noten und Takte anhand der Vorlage."], ["MusicXML herunterladen", "Nutzen Sie das Ergebnis in einem kompatiblen Noteneditor."]],
    workflowTitle: "So wandeln Sie ein PDF in MusicXML um", workflow: [["PDF oder Bild hochladen", "Achten Sie auf gut erkennbare Notenlinien und Notenköpfe."], ["Erkannte Noten prüfen", "Korrigieren Sie Tonhöhen, Notenwerte und Takte."], ["MusicXML exportieren", "Prüfen Sie die Darstellung auch im Zielprogramm."]],
    details: [["Von OMR falsch erkannte Noten korrigieren", "Ändern Sie Noten und Rhythmen im Editor und hören Sie die Partitur vor dem Export an."], ["Auch gescannte Bilder in MusicXML umwandeln", "Das PDF braucht keinen auswählbaren Text. OMR kann gedruckte Noten aus ausreichend klaren Bildern lesen."]],
    faq: [["Kann das Tool handgeschriebene Noten lesen?", "Der Konverter für PDF in MusicXML erkennt Handschrift nicht zuverlässig. Verwenden Sie klar gedruckte Noten."], ["Wie genau ist der PDF-Import?", "Die Genauigkeit hängt von Bildqualität, Akkorden und Symbolen ab. Ein fester Prozentsatz wird nicht garantiert; prüfen Sie Tonhöhen, Rhythmen und Takte."], ["Was ist, wenn die Datei ein gescanntes Bild enthält?", "OMR kann solche Seiten verarbeiten. Auch PNG, JPG, WebP und TIFF sind direkt möglich, sofern Notenlinien und Notenköpfe lesbar sind."]],
    links: ["Korrigieren Sie nach der Erkennung einzelne Noten im ", ["Noteneditor", "/score-editor"], ", ", ["transponieren Sie die Partitur", "/transpose-score"], " und ", ["wandeln Sie sie in MIDI um", "/musicxml-midi"], ". Hinweise zu Fotos finden Sie beim ", ["Notenscanner", "/sheet-music-scanner"], "."],
  }, "FAQ"),
  "score-editor": tool({
    title: "Noten erstellen und online bearbeiten — Schreiben, korrigieren, transponieren", description: "Erstellen Sie Noten online oder importieren Sie MusicXML, MIDI, Jianpu oder einen Scan. Korrigieren Sie Noten, extrahieren Sie Stimmen, transponieren Sie und exportieren Sie PDF oder MIDI. Kostenlos im Browser ausprobieren.",
    h1: "Noten erstellen und online bearbeiten", intro: "Noten erstellen Sie hier aus eingegebenem Jianpu-Text oder importierten MusicXML-, MIDI- und gescannten Partituren. Korrigieren Sie Noten und Rhythmen, kopieren Sie Stimmen, transponieren Sie und exportieren Sie PDF oder MIDI.",
    moduleTitle: "Noten erstellen: Werkzeuge zum Schreiben und Bearbeiten", modules: [["Notenvorschau", "Prüfen Sie Tonhöhen und Rhythmen in der dargestellten Partitur."], ["Änderungen speichern", "Bewahren Sie gespeicherte Bearbeitungen zum späteren Vergleich auf."], ["Noteneditor", "Wählen, ergänzen oder löschen Sie Noten und ändern Sie Notenwerte."], ["Stimmenauszug", "Kopieren Sie vorhandene Instrumentalstimmen in eine eigene Übepartitur; Beta."], ["Frühere Versionen", "Kehren Sie bei Bedarf zu einer gespeicherten Fassung zurück."], ["Teilen und Zusammenarbeit", "Vergeben Sie Lese- oder Schreibrechte; Echtzeit-Zusammenarbeit ist in Beta."]],
    workflowTitle: "So erstellen Sie Noten online", workflow: [["Eingeben oder importieren", "Starten Sie mit strukturiertem Jianpu, einer Datei oder einem geprüften Scan."], ["Notation bearbeiten", "Korrigieren Sie Noten und Takte, transponieren Sie oder kopieren Sie eine Stimme."], ["Anhören und exportieren", "Prüfen Sie das Ergebnis und laden Sie PDF, MIDI oder MusicXML herunter."]],
    details: [["Importierte MusicXML- oder MIDI-Dateien bearbeiten", "Ausdrucksvolles MIDI-Timing kann komplexe Pausen und Haltebögen erzeugen. Bereinigen Sie die Notation vor dem Drucken."], ["Stimmen aus einer Partitur extrahieren", "Kopieren Sie eine bereits getrennte Stimme. Die Beta-Funktion trennt keine Instrumente, die in derselben Stimme vermischt sind."]],
    faq: [["Brauche ich Musiktheorie, um das Tool zu nutzen?", "Sie können zunächst vorhandene Noten importieren und mit der Vorlage vergleichen. Wenn Sie Noten erstellen oder korrigieren, helfen Kenntnisse über Tonhöhen, Rhythmus, Tonarten und Taktarten."], ["Kann ich eine MIDI-Datei nach dem Import bearbeiten?", "Ja. Sie können Noten, Pausen, Notenwerte und Takte ändern. Kleine Zeitabweichungen einer Einspielung müssen eventuell von Hand bereinigt werden."], ["Wie extrahiere ich nur die Violinstimme?", "Öffnen Sie eine Partitur mit einer getrennten Violinstimme und wählen Sie diese im Werkzeug zum Kopieren von Stimmen. Die Funktion ist in Beta."], ["Kann ich ohne Datei-Upload Noten erstellen?", "Sie können strukturierten Jianpu-Text mit Tonart, Takt und Notenwerten eingeben und in Notenschrift umwandeln. Vollständiger freier Notensatz und detaillierte Seitenlayouts sind noch in Entwicklung."]],
    links: ["Für Papiernoten beginnen Sie beim ", ["Notenscanner", "/sheet-music-scanner"], " oder mit ", ["PDF in MusicXML", "/pdf-to-musicxml"], ". Danach können Sie die ", ["Noten transponieren", "/transpose-score"], " oder ", ["MIDI exportieren", "/musicxml-midi"], "."],
  }, "FAQ"),
  "musicxml-midi": tool({
    title: "MIDI in Noten und Noten in MIDI umwandeln", description: "Laden Sie eine MIDI-Datei hoch und erhalten Sie bearbeitbare Noten im Browser: Notation bereinigen, transponieren, abspielen und als MusicXML, PDF oder neue MIDI-Datei exportieren. Kostenlos ausprobieren.",
    h1: "MIDI in Noten und Noten in MIDI umwandeln", intro: "Wandeln Sie MIDI in Noten um, um die Notation zu prüfen und zu bearbeiten. Korrigieren Sie Rhythmen, transponieren Sie und exportieren Sie MusicXML, PDF oder MIDI. Auch Noten lassen sich als MIDI speichern.",
    moduleTitle: "MIDI in Noten importieren und wieder exportieren", modules: [["MusicXML und MXL", "Importieren Sie bearbeitbare Notendateien."], ["MIDI-Import", "Lesen Sie Noten aus .mid- oder .midi-Dateien."], ["MIDI-Export", "Speichern Sie die korrigierten Noten und ihr Timing."], ["Druck und Bilder", "Verwenden Sie die verfügbaren PDF-, SVG- oder PNG-Exporte."], ["Wiedergabe", "Prüfen Sie Noten und Rhythmen vor dem Download."]],
    workflowTitle: "So wandeln Sie MIDI in Noten um", workflow: [["MIDI importieren", "Öffnen Sie die Datei und prüfen Sie die erzeugte Notation."], ["Rhythmen bereinigen", "Kontrollieren Sie Pausen, Haltebögen, Takte und Stimmen."], ["Anhören und herunterladen", "Exportieren Sie MusicXML, PDF oder eine neue MIDI-Datei."]],
    details: [["Einen unübersichtlichen MIDI-Import bereinigen", "Einspielungen enthalten oft kleine Zeitabweichungen und überlappende Noten. Überarbeiten Sie Rhythmen und Takte im Editor."], ["MusicXML in MIDI umwandeln", "Importieren Sie MusicXML, prüfen Sie Noten und Tempo und exportieren Sie MIDI für andere Musikprogramme."]],
    faq: [["Bleiben Tempo und Dynamik erhalten?", "Bei MIDI in Noten werden unterstützte Tempo- und Spieldaten eingelesen. MIDI bildet jedoch nicht jedes gedruckte Ausdruckszeichen ab. Prüfen Sie das Ergebnis nach der Umwandlung."], ["Klingt die MIDI-Datei wie das Original?", "MIDI speichert musikalische Ereignisse statt aufgenommenem Klang. Die Klangfarbe hängt vom Instrument oder der Soundbibliothek ab, die die Datei abspielt."], ["Kann ich PDF-Noten in MIDI umwandeln?", "Scannen Sie zuerst das PDF oder Foto und korrigieren Sie die erkannten Noten. Danach exportieren Sie die bearbeitbare Partitur als MIDI."]],
    links: ["Bei Papiernoten starten Sie mit ", ["PDF in MusicXML", "/pdf-to-musicxml"], ", korrigieren im ", ["Noteneditor", "/score-editor"], " und ", ["transponieren bei Bedarf", "/transpose-score"], ", bevor Sie MIDI exportieren."],
  }, "FAQ"),
  "transpose-score": tool({
    title: "Noten transponieren online — Tonart in Halbtonschritten ändern", description: "Noten transponieren nach Halbtonzahl, Zieltonart oder Instrument. Behalten Sie das Original, prüfen Sie Noten und Tonumfang und exportieren Sie die Partitur zum Üben.",
    h1: "Noten transponieren online", intro: "Noten transponieren Sie nach Halbtonzahl, Zieltonart oder Instrument. Vergleichen Sie das Ergebnis mit dem Original, prüfen Sie Versetzungszeichen und Tonumfang und hören Sie vor dem Export hinein.",
    moduleTitle: "Noten transponieren nach Tonart, Halbtönen oder Instrument", modules: [["Halbtonschritte", "Verschieben Sie die Noten um die gewählte Zahl nach oben oder unten."], ["Zieltonart", "Passen Sie die Tonart an Stimme oder Ensemble an."], ["Transponierende Instrumente", "Nutzen Sie unterstützte Profile für B♭-, A-, E♭- oder F-Instrumente."], ["Tonumfang", "Prüfen Sie Noten außerhalb des gewählten Stimm- oder Instrumentalumfangs."]],
    workflowTitle: "So transponieren Sie Noten online", workflow: [["Bearbeitbare Noten öffnen", "Importieren Sie eine Datei oder korrigieren Sie einen erkannten Scan."], ["Transposition wählen", "Geben Sie Halbtonzahl, Tonart oder Instrumentenprofil an."], ["Prüfen und exportieren", "Kontrollieren Sie Versetzungszeichen und Umfang und hören Sie das Ergebnis an."]],
    details: [["Tonart in Halbtonschritten ändern", "Von C-Dur nach D-Dur verschieben Sie um zwei Halbtöne nach oben. Prüfen Sie danach den Tonumfang."], ["Stimmen für transponierende Instrumente vorbereiten", "Klären Sie vor der Profilwahl, ob die Vorlage klingend oder bereits transponiert notiert ist."]],
    faq: [["Kann ich Noten aus einem PDF transponieren?", "Scannen Sie das PDF und korrigieren Sie die Erkennung. Anschließend können Sie die bearbeitbaren Noten transponieren."], ["Wird das Original überschrieben?", "Nein. Die Transposition wird als neue Version gespeichert und lässt sich mit der Vorlage vergleichen."], ["Welche transponierenden Instrumente werden unterstützt?", "Es gibt Profile für B♭, A, E♭ und F. Prüfen Sie die Ausgangsnotation und den resultierenden Tonumfang."]],
    links: ["Nutzen Sie für PDF den ", ["Notenscanner", "/sheet-music-scanner"], ", korrigieren Sie die Noten im ", ["Editor", "/score-editor"], " und ", ["exportieren Sie die transponierte Partitur als MIDI", "/musicxml-midi"], "."],
  }, "FAQ"),
};
