import { tool } from "./types";

export const fr = {
  "sheet-music-scanner": tool({
    title: "Scanner de partitions PDF et images — OMR gratuit en ligne", description: "Utilisez le scanner de partitions pour lire un PDF ou une photo, corriger les notes, transposer et exporter en MusicXML, MIDI ou PDF. Essai gratuit, sans installation.",
    h1: "Scanner de partitions PDF et images", intro: "Ce scanner de partitions transforme un PDF ou une photo de musique imprimée en notes modifiables. Comparez le résultat à l’original, corrigez les erreurs, puis transposez, écoutez ou exportez. Essai gratuit, sans installation.",
    moduleTitle: "Scanner de partitions imprimées", modules: [["PDF et photos", "Importez un PDF complet ou une image PNG, JPG, WebP ou TIFF."], ["Reconnaissance des notes", "Lisez les hauteurs et les rythmes de la notation imprimée."], ["Fichier MusicXML", "Conservez une partition modifiable dans un logiciel compatible."], ["Correction des erreurs", "Comparez les notes, les silences et les mesures à l’original."]],
    workflowTitle: "Comment scanner une partition PDF", workflow: [["Importer une page nette", "Choisissez un PDF ou une photo complète d’une partition imprimée."], ["Reconnaître les notes", "Attendez la fin du traitement, puis ouvrez la partition obtenue."], ["Corriger et exporter", "Vérifiez les hauteurs, les durées et les mesures avant l’écoute et l’export."]],
    details: [["Scanner de partitions à partir de photos de téléphone", "Photographiez toute la page, avec une lumière uniforme et l’appareil parallèle au papier. Évitez le flou."], ["Quelle est la précision du scanner de partitions ?", "Elle dépend de la qualité de l’image et de la complexité de la notation. Les accords denses et les symboles inhabituels peuvent nécessiter des corrections."]],
    faq: [["Le scanner de partitions est-il gratuit ?", "Un compte gratuit comprend un projet de partition complet et 25 crédits par mois. Un PDF de plusieurs pages peut former ce projet. Les traitements serveur concernés consomment des crédits ; des projets ou une capacité supplémentaires nécessitent une formule payante."], ["Peut-il lire des partitions manuscrites ?", "La reconnaissance vise les partitions imprimées. Elle ne prend pas en charge l’écriture manuscrite de manière fiable. Préparez plutôt un fichier MusicXML ou saisissez du Jianpu structuré."], ["Fonctionne-t-il avec des photos de téléphone ?", "Oui, dans les formats d’image pris en charge. Les portées et les têtes de notes doivent être nettes ; vérifiez ensuite le résultat."], ["Combien de temps faut-il pour scanner une page ?", "Il n’y a pas de durée fixe. Elle dépend de l’image, du nombre de pages, de la complexité et de la file d’attente. L’application affiche l’état du traitement."], ["Puis-je corriger les erreurs après le scan ?", "Oui. Modifiez les hauteurs, les durées, les silences et les mesures dans l’éditeur, puis écoutez avant d’exporter."]],
    links: ["Après le scan, utilisez l’", ["éditeur de partitions", "/score-editor"], ", puis ", ["transposez la partition", "/transpose-score"], " et ", ["exportez en MIDI", "/musicxml-midi"], ". Pour conserver un fichier modifiable, consultez ", ["PDF vers MusicXML", "/pdf-to-musicxml"], "."],
  }, "FAQ"),
  "pdf-to-musicxml": tool({
    title: "Convertisseur PDF vers MusicXML en ligne", description: "Importez un PDF de partition ou une photo pour obtenir un fichier MusicXML modifiable : corrigez les notes mal lues, transposez, écoutez et exportez. Essai gratuit, sans installation.",
    h1: "Convertisseur PDF vers MusicXML", intro: "Ce convertisseur PDF vers MusicXML transforme une partition PDF ou une photo en notes modifiables. Corrigez les erreurs, transposez, écoutez, puis téléchargez le fichier MusicXML. Essai gratuit, sans installation.",
    moduleTitle: "PDF vers MusicXML avec des notes modifiables", modules: [["Importer la source", "Utilisez un PDF de partition ou une image numérisée nette."], ["Lire les notes", "Reconnaissez les hauteurs et les rythmes imprimés."], ["Corriger la notation", "Vérifiez les notes et les mesures en regardant l’original."], ["Télécharger MusicXML", "Poursuivez le travail dans un éditeur compatible."]],
    workflowTitle: "Comment convertir un PDF en MusicXML", workflow: [["Importer le PDF ou la photo", "Vérifiez que les portées et les notes sont lisibles."], ["Relire la partition", "Corrigez les hauteurs, les durées et les mesures."], ["Exporter MusicXML", "Ouvrez le fichier dans le logiciel souhaité et vérifiez sa présentation."]],
    details: [["Corriger les notes mal reconnues par l’OMR", "Modifiez les notes et les rythmes dans l’éditeur, puis écoutez la partition avant l’export."], ["Convertir une image numérisée en MusicXML", "Le PDF n’a pas besoin de texte sélectionnable : l’OMR peut lire une image de notation imprimée suffisamment nette."]],
    faq: [["Peut-il lire des partitions manuscrites ?", "Le convertisseur PDF vers MusicXML ne reconnaît pas l’écriture manuscrite de manière fiable. Utilisez une partition imprimée nette."], ["Quelle est la précision de l’import PDF ?", "Elle varie selon la qualité du document, les accords et les symboles. Aucun pourcentage fixe n’est garanti ; vérifiez les hauteurs, les rythmes et les mesures."], ["Et si le fichier contient une image numérisée ?", "L’OMR peut traiter ces pages. Vous pouvez aussi importer directement un PNG, JPG, WebP ou TIFF dont les portées et les notes sont lisibles."]],
    links: ["Après la reconnaissance, corrigez chaque note dans l’", ["éditeur de partitions", "/score-editor"], ", puis ", ["transposez la partition", "/transpose-score"], " et ", ["convertissez-la en MIDI", "/musicxml-midi"], ". Pour préparer une photo, consultez le ", ["scanner de partitions", "/sheet-music-scanner"], "."],
  }, "FAQ"),
  "score-editor": tool({
    title: "Créateur de partitions et éditeur en ligne — Créer, corriger et transposer", description: "Créez une partition en ligne ou importez MusicXML, MIDI, Jianpu ou un scan. Corrigez les notes, extrayez des parties, transposez et exportez en PDF ou MIDI. Essai gratuit dans votre navigateur.",
    h1: "Créateur de partitions et éditeur de notation en ligne", intro: "Ce créateur de partitions permet de commencer avec du Jianpu structuré ou d’importer MusicXML, MIDI et des partitions scannées. Corrigez les notes, extrayez des parties, transposez et exportez en PDF ou MIDI.",
    moduleTitle: "Créateur de partitions : écrire et modifier les notes", modules: [["Aperçu sur portée", "Vérifiez les hauteurs et les rythmes sur la partition affichée."], ["Enregistrement", "Conservez les modifications enregistrées pour les consulter plus tard."], ["Édition des notes", "Sélectionnez, ajoutez ou supprimez des notes et ajustez les durées."], ["Extraction de parties", "Copiez une partie instrumentale existante dans une partition séparée ; fonction bêta."], ["Versions précédentes", "Revenez à une version enregistrée si nécessaire."], ["Partage et collaboration", "Attribuez des droits de lecture ou d’édition ; collaboration en temps réel en bêta."]],
    workflowTitle: "Comment créer une partition en ligne", workflow: [["Saisir ou importer", "Commencez avec du Jianpu structuré, un fichier ou un scan relu."], ["Modifier la notation", "Corrigez les notes et les mesures, puis transposez ou extrayez une partie."], ["Écouter et exporter", "Vérifiez le résultat avant de télécharger PDF, MIDI ou MusicXML."]],
    details: [["Modifier un fichier MusicXML ou MIDI importé", "Le timing expressif du MIDI peut produire des silences et des liaisons complexes. Relisez la notation avant l’impression."], ["Extraire des parties d’une partition", "Copiez une partie déjà distincte. Cette fonction bêta ne sépare pas automatiquement des instruments mélangés dans une même partie."]],
    faq: [["Faut-il connaître le solfège pour l’utiliser ?", "Vous pouvez commencer dans le créateur de partitions en important un document et en le comparant à l’original. Comprendre les hauteurs, rythmes, armures et mesures facilite les corrections."], ["Puis-je modifier un fichier MIDI après l’import ?", "Oui, vous pouvez modifier les notes, silences, durées et mesures. Les petites variations de timing d’une interprétation peuvent demander un nettoyage manuel."], ["Comment extraire uniquement la partie de violon ?", "Ouvrez une partition contenant une partie de violon distincte et sélectionnez-la dans l’outil de copie de parties. L’extraction est en bêta."], ["Puis-je créer une partition sans importer de fichier ?", "Vous pouvez saisir du Jianpu structuré avec tonalité, mesure et durées, puis le convertir en portée. La gravure libre complète et le contrôle détaillé de la mise en page sont encore en développement."]],
    links: ["Pour une source papier, commencez par le ", ["scanner de partitions", "/sheet-music-scanner"], " ou ", ["PDF vers MusicXML", "/pdf-to-musicxml"], ". Après l’édition, ", ["transposez la partition", "/transpose-score"], " ou ", ["exportez en MIDI", "/musicxml-midi"], "."],
  }, "FAQ"),
  "musicxml-midi": tool({
    title: "Convertisseur MIDI en partition et partition en MIDI", description: "Importez un fichier MIDI pour obtenir une partition modifiable dans votre navigateur : nettoyez la notation, transposez, écoutez et exportez en MusicXML, PDF ou dans un nouveau MIDI. Essai gratuit.",
    h1: "Convertisseur MIDI en partition et partition en MIDI", intro: "Convertissez un MIDI en partition pour relire et modifier les notes. Corrigez les rythmes, transposez et écoutez avant d’exporter MusicXML, PDF ou MIDI. La conversion d’une partition en MIDI est également disponible.",
    moduleTitle: "MIDI en partition et export dans l’autre sens", modules: [["MusicXML et MXL", "Importez un fichier de notation modifiable."], ["Import MIDI", "Lisez les notes d’un fichier .mid ou .midi."], ["Export MIDI", "Enregistrez les notes et le timing de la partition corrigée."], ["Impression et images", "Utilisez les exports PDF, SVG ou PNG disponibles."], ["Écoute", "Contrôlez les notes et le rythme avant le téléchargement."]],
    workflowTitle: "Comment convertir un MIDI en partition", workflow: [["Importer le MIDI", "Ouvrez le fichier et inspectez la notation obtenue."], ["Nettoyer les rythmes", "Vérifiez les silences, liaisons, mesures et parties."], ["Écouter et télécharger", "Exportez MusicXML, PDF ou un nouveau fichier MIDI."]],
    details: [["Nettoyer un import MIDI désordonné", "Une interprétation comporte souvent des décalages et des notes qui se chevauchent. Corrigez les rythmes et les mesures dans l’éditeur."], ["MusicXML vers MIDI", "Importez MusicXML, vérifiez les notes et le tempo, puis exportez un MIDI pour votre logiciel musical."]],
    faq: [["Le tempo et les nuances sont-ils conservés ?", "La conversion MIDI en partition lit les informations de tempo et d’interprétation prises en charge, mais le MIDI ne représente pas toutes les indications imprimées. Vérifiez le résultat."], ["Le MIDI sonnera-t-il comme l’original ?", "Le MIDI contient des événements musicaux, pas un enregistrement. Le timbre dépend de l’instrument ou de la banque de sons utilisée pour le lire."], ["Puis-je convertir une partition PDF en MIDI ?", "Scannez d’abord le PDF ou la photo, corrigez les notes reconnues, puis exportez la partition en MIDI."]],
    links: ["Pour le papier, commencez par ", ["PDF vers MusicXML", "/pdf-to-musicxml"], ". Corrigez les notes dans l’", ["éditeur de partitions", "/score-editor"], " et ", ["transposez", "/transpose-score"], " si nécessaire avant l’export MIDI."],
  }, "FAQ"),
  "transpose-score": tool({
    title: "Transposer une partition en ligne — Changer de tonalité par demi-tons", description: "Transposez une partition par demi-tons, tonalité cible ou instrument. Conservez l’original, vérifiez les notes et la tessiture, puis exportez pour travailler votre morceau.",
    h1: "Transposer une partition en ligne", intro: "Pour transposer une partition, choisissez un nombre de demi-tons, une tonalité cible ou un instrument. Comparez le résultat à l’original, vérifiez les altérations et la tessiture, puis écoutez avant l’export.",
    moduleTitle: "Transposer une partition par tonalité, demi-tons ou instrument", modules: [["Demi-tons", "Montez ou descendez les notes du nombre choisi."], ["Tonalité cible", "Adaptez la partition à la voix ou à l’ensemble."], ["Instruments transpositeurs", "Utilisez les profils pris en charge en si bémol, la, mi bémol ou fa."], ["Tessiture", "Repérez les notes hors de la tessiture sélectionnée."]],
    workflowTitle: "Comment transposer une partition en ligne", workflow: [["Ouvrir une partition modifiable", "Importez un fichier ou corrigez un PDF reconnu."], ["Choisir la transposition", "Indiquez les demi-tons, la tonalité ou le profil instrumental."], ["Vérifier et exporter", "Contrôlez les altérations et la tessiture, puis écoutez et enregistrez."]],
    details: [["Changer de tonalité par demi-tons", "Pour passer de do majeur à ré majeur, montez de deux demi-tons puis vérifiez le résultat."], ["Préparer une partie pour instrument transpositeur", "Vérifiez si la source est au diapason réel ou déjà transposée avant de choisir le profil."]],
    faq: [["Puis-je transposer une partition PDF ?", "Scannez le PDF et corrigez les notes pour obtenir une partition modifiable avant de la transposer."], ["La transposition remplace-t-elle l’original ?", "Non. Elle est enregistrée comme une nouvelle version, que vous pouvez comparer à l’original."], ["Quels instruments transpositeurs sont pris en charge ?", "Des profils en si bémol, la, mi bémol et fa sont disponibles. Vérifiez la notation de départ et la tessiture obtenue."]],
    links: ["Importez le PDF avec le ", ["scanner de partitions", "/sheet-music-scanner"], ", corrigez-le dans l’", ["éditeur", "/score-editor"], " puis ", ["exportez la partition transposée en MIDI", "/musicxml-midi"], "."],
  }, "FAQ"),
};
